import java.lang
import java.util
import org.osgi.dto
import org.osgi.framework.dto
import typing


class ComponentConfigurationDTO(org.osgi.dto.DTO):
    """
    Java class 'org.osgi.service.component.runtime.dto.ComponentConfigurationDTO'
    
        Extends:
            org.osgi.dto.DTO
    
      Constructors:
        * ComponentConfigurationDTO()
    
      Attributes:
        UNSATISFIED_CONFIGURATION (int): final static field
        UNSATISFIED_REFERENCE (int): final static field
        SATISFIED (int): final static field
        ACTIVE (int): final static field
        FAILED_ACTIVATION (int): final static field
        description (org.osgi.service.component.runtime.dto.ComponentDescriptionDTO): field
        state (int): field
        id (long): field
        properties (java.util.Map): field
        satisfiedReferences ([Lorg.osgi.service.component.runtime.dto.SatisfiedReferenceDTO;): field
        unsatisfiedReferences ([Lorg.osgi.service.component.runtime.dto.UnsatisfiedReferenceDTO;): field
        failure (java.lang.String): field
        service (org.osgi.framework.dto.ServiceReferenceDTO): field
    
    """
    UNSATISFIED_CONFIGURATION: typing.ClassVar[int] = ...
    UNSATISFIED_REFERENCE: typing.ClassVar[int] = ...
    SATISFIED: typing.ClassVar[int] = ...
    ACTIVE: typing.ClassVar[int] = ...
    FAILED_ACTIVATION: typing.ClassVar[int] = ...
    description: 'ComponentDescriptionDTO' = ...
    state: int = ...
    id: int = ...
    properties: java.util.Map = ...
    satisfiedReferences: typing.List['SatisfiedReferenceDTO'] = ...
    unsatisfiedReferences: typing.List['UnsatisfiedReferenceDTO'] = ...
    failure: java.lang.String = ...
    service: org.osgi.framework.dto.ServiceReferenceDTO = ...
    def __init__(self): ...

class ComponentDescriptionDTO(org.osgi.dto.DTO):
    """
    Java class 'org.osgi.service.component.runtime.dto.ComponentDescriptionDTO'
    
        Extends:
            org.osgi.dto.DTO
    
      Constructors:
        * ComponentDescriptionDTO()
    
      Attributes:
        name (java.lang.String): field
        bundle (org.osgi.framework.dto.BundleDTO): field
        factory (java.lang.String): field
        scope (java.lang.String): field
        implementationClass (java.lang.String): field
        defaultEnabled (boolean): field
        immediate (boolean): field
        serviceInterfaces ([Ljava.lang.String;): field
        properties (java.util.Map): field
        references ([Lorg.osgi.service.component.runtime.dto.ReferenceDTO;): field
        activate (java.lang.String): field
        deactivate (java.lang.String): field
        modified (java.lang.String): field
        configurationPolicy (java.lang.String): field
        configurationPid ([Ljava.lang.String;): field
        factoryProperties (java.util.Map): field
        activationFields ([Ljava.lang.String;): field
        init (int): field
    
    """
    name: java.lang.String = ...
    bundle: org.osgi.framework.dto.BundleDTO = ...
    factory: java.lang.String = ...
    scope: java.lang.String = ...
    implementationClass: java.lang.String = ...
    defaultEnabled: bool = ...
    immediate: bool = ...
    serviceInterfaces: typing.List[java.lang.String] = ...
    properties: java.util.Map = ...
    references: typing.List['ReferenceDTO'] = ...
    activate: java.lang.String = ...
    deactivate: java.lang.String = ...
    modified: java.lang.String = ...
    configurationPolicy: java.lang.String = ...
    configurationPid: typing.List[java.lang.String] = ...
    factoryProperties: java.util.Map = ...
    activationFields: typing.List[java.lang.String] = ...
    init: int = ...
    def __init__(self): ...

class ReferenceDTO(org.osgi.dto.DTO):
    """
    Java class 'org.osgi.service.component.runtime.dto.ReferenceDTO'
    
        Extends:
            org.osgi.dto.DTO
    
      Constructors:
        * ReferenceDTO()
    
      Attributes:
        name (java.lang.String): field
        interfaceName (java.lang.String): field
        cardinality (java.lang.String): field
        policy (java.lang.String): field
        policyOption (java.lang.String): field
        target (java.lang.String): field
        bind (java.lang.String): field
        unbind (java.lang.String): field
        updated (java.lang.String): field
        field (java.lang.String): field
        fieldOption (java.lang.String): field
        scope (java.lang.String): field
        parameter (java.lang.Integer): field
        collectionType (java.lang.String): field
    
    """
    name: java.lang.String = ...
    interfaceName: java.lang.String = ...
    cardinality: java.lang.String = ...
    policy: java.lang.String = ...
    policyOption: java.lang.String = ...
    target: java.lang.String = ...
    bind: java.lang.String = ...
    unbind: java.lang.String = ...
    updated: java.lang.String = ...
    field: java.lang.String = ...
    fieldOption: java.lang.String = ...
    scope: java.lang.String = ...
    parameter: int = ...
    collectionType: java.lang.String = ...
    def __init__(self): ...

class SatisfiedReferenceDTO(org.osgi.dto.DTO):
    """
    Java class 'org.osgi.service.component.runtime.dto.SatisfiedReferenceDTO'
    
        Extends:
            org.osgi.dto.DTO
    
      Constructors:
        * SatisfiedReferenceDTO()
    
      Attributes:
        name (java.lang.String): field
        target (java.lang.String): field
        boundServices ([Lorg.osgi.framework.dto.ServiceReferenceDTO;): field
    
    """
    name: java.lang.String = ...
    target: java.lang.String = ...
    boundServices: typing.List[org.osgi.framework.dto.ServiceReferenceDTO] = ...
    def __init__(self): ...

class UnsatisfiedReferenceDTO(org.osgi.dto.DTO):
    """
    Java class 'org.osgi.service.component.runtime.dto.UnsatisfiedReferenceDTO'
    
        Extends:
            org.osgi.dto.DTO
    
      Constructors:
        * UnsatisfiedReferenceDTO()
    
      Attributes:
        name (java.lang.String): field
        target (java.lang.String): field
        targetServices ([Lorg.osgi.framework.dto.ServiceReferenceDTO;): field
    
    """
    name: java.lang.String = ...
    target: java.lang.String = ...
    targetServices: typing.List[org.osgi.framework.dto.ServiceReferenceDTO] = ...
    def __init__(self): ...
