import java.lang
import java.util
import org
import org.eclipse.emf.common.util
import org.eclipse.emf.ecore
import typing


class ItemModel(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.items.ItemModel'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getItems(self) -> org.eclipse.emf.common.util.EList['ModelItem']: ...

class ItemsFactory(org.eclipse.emf.ecore.EFactory):
    """
    Java class 'org.openhab.core.model.items.ItemsFactory'
    
        Interfaces:
            org.eclipse.emf.ecore.EFactory
    
      Attributes:
        eINSTANCE (org.openhab.core.model.items.ItemsFactory): final static field
    
    """
    eINSTANCE: typing.ClassVar['ItemsFactory'] = ...
    def createItemModel(self) -> ItemModel: ...
    def createModelBinding(self) -> 'ModelBinding': ...
    def createModelGroupItem(self) -> 'ModelGroupItem': ...
    def createModelItem(self) -> 'ModelItem': ...
    def createModelNormalItem(self) -> 'ModelNormalItem': ...
    def createModelProperty(self) -> 'ModelProperty': ...
    def getItemsPackage(self) -> 'ItemsPackage': ...

class ItemsPackage(org.eclipse.emf.ecore.EPackage):
    """
    Java class 'org.openhab.core.model.items.ItemsPackage'
    
        Interfaces:
            org.eclipse.emf.ecore.EPackage
    
      Attributes:
        eNAME (java.lang.String): final static field
        eNS_URI (java.lang.String): final static field
        eNS_PREFIX (java.lang.String): final static field
        eINSTANCE (org.openhab.core.model.items.ItemsPackage): final static field
        ITEM_MODEL (int): final static field
        ITEM_MODEL__ITEMS (int): final static field
        ITEM_MODEL_FEATURE_COUNT (int): final static field
        MODEL_ITEM (int): final static field
        MODEL_ITEM__NAME (int): final static field
        MODEL_ITEM__LABEL (int): final static field
        MODEL_ITEM__ICON (int): final static field
        MODEL_ITEM__GROUPS (int): final static field
        MODEL_ITEM__TAGS (int): final static field
        MODEL_ITEM__BINDINGS (int): final static field
        MODEL_ITEM__TYPE (int): final static field
        MODEL_ITEM_FEATURE_COUNT (int): final static field
        MODEL_GROUP_ITEM (int): final static field
        MODEL_GROUP_ITEM__NAME (int): final static field
        MODEL_GROUP_ITEM__LABEL (int): final static field
        MODEL_GROUP_ITEM__ICON (int): final static field
        MODEL_GROUP_ITEM__GROUPS (int): final static field
        MODEL_GROUP_ITEM__TAGS (int): final static field
        MODEL_GROUP_ITEM__BINDINGS (int): final static field
        MODEL_GROUP_ITEM__TYPE (int): final static field
        MODEL_GROUP_ITEM__FUNCTION (int): final static field
        MODEL_GROUP_ITEM__ARGS (int): final static field
        MODEL_GROUP_ITEM_FEATURE_COUNT (int): final static field
        MODEL_NORMAL_ITEM (int): final static field
        MODEL_NORMAL_ITEM__NAME (int): final static field
        MODEL_NORMAL_ITEM__LABEL (int): final static field
        MODEL_NORMAL_ITEM__ICON (int): final static field
        MODEL_NORMAL_ITEM__GROUPS (int): final static field
        MODEL_NORMAL_ITEM__TAGS (int): final static field
        MODEL_NORMAL_ITEM__BINDINGS (int): final static field
        MODEL_NORMAL_ITEM__TYPE (int): final static field
        MODEL_NORMAL_ITEM_FEATURE_COUNT (int): final static field
        MODEL_BINDING (int): final static field
        MODEL_BINDING__TYPE (int): final static field
        MODEL_BINDING__CONFIGURATION (int): final static field
        MODEL_BINDING__PROPERTIES (int): final static field
        MODEL_BINDING_FEATURE_COUNT (int): final static field
        MODEL_PROPERTY (int): final static field
        MODEL_PROPERTY__KEY (int): final static field
        MODEL_PROPERTY__VALUE (int): final static field
        MODEL_PROPERTY_FEATURE_COUNT (int): final static field
        MODEL_GROUP_FUNCTION (int): final static field
    
    """
    eNAME: typing.ClassVar[java.lang.String] = ...
    eNS_URI: typing.ClassVar[java.lang.String] = ...
    eNS_PREFIX: typing.ClassVar[java.lang.String] = ...
    eINSTANCE: typing.ClassVar['ItemsPackage'] = ...
    ITEM_MODEL: typing.ClassVar[int] = ...
    ITEM_MODEL__ITEMS: typing.ClassVar[int] = ...
    ITEM_MODEL_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_ITEM: typing.ClassVar[int] = ...
    MODEL_ITEM__NAME: typing.ClassVar[int] = ...
    MODEL_ITEM__LABEL: typing.ClassVar[int] = ...
    MODEL_ITEM__ICON: typing.ClassVar[int] = ...
    MODEL_ITEM__GROUPS: typing.ClassVar[int] = ...
    MODEL_ITEM__TAGS: typing.ClassVar[int] = ...
    MODEL_ITEM__BINDINGS: typing.ClassVar[int] = ...
    MODEL_ITEM__TYPE: typing.ClassVar[int] = ...
    MODEL_ITEM_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__NAME: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__LABEL: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__ICON: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__GROUPS: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__TAGS: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__BINDINGS: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__TYPE: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__FUNCTION: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM__ARGS: typing.ClassVar[int] = ...
    MODEL_GROUP_ITEM_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM__NAME: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM__LABEL: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM__ICON: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM__GROUPS: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM__TAGS: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM__BINDINGS: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM__TYPE: typing.ClassVar[int] = ...
    MODEL_NORMAL_ITEM_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_BINDING: typing.ClassVar[int] = ...
    MODEL_BINDING__TYPE: typing.ClassVar[int] = ...
    MODEL_BINDING__CONFIGURATION: typing.ClassVar[int] = ...
    MODEL_BINDING__PROPERTIES: typing.ClassVar[int] = ...
    MODEL_BINDING_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_PROPERTY: typing.ClassVar[int] = ...
    MODEL_PROPERTY__KEY: typing.ClassVar[int] = ...
    MODEL_PROPERTY__VALUE: typing.ClassVar[int] = ...
    MODEL_PROPERTY_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_GROUP_FUNCTION: typing.ClassVar[int] = ...
    def getItemModel(self) -> org.eclipse.emf.ecore.EClass: ...
    def getItemModel_Items(self) -> org.eclipse.emf.ecore.EReference: ...
    def getItemsFactory(self) -> ItemsFactory: ...
    def getModelBinding(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelBinding_Configuration(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelBinding_Properties(self) -> org.eclipse.emf.ecore.EReference: ...
    def getModelBinding_Type(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelGroupFunction(self) -> org.eclipse.emf.ecore.EEnum: ...
    def getModelGroupItem(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelGroupItem_Args(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelGroupItem_Function(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelItem(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelItem_Bindings(self) -> org.eclipse.emf.ecore.EReference: ...
    def getModelItem_Groups(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelItem_Icon(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelItem_Label(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelItem_Name(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelItem_Tags(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelItem_Type(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelNormalItem(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelProperty(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelProperty_Key(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelProperty_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    class Literals(java.lang.Object):
        """
        Java class 'org.openhab.core.model.items.ItemsPackage$Literals'
        
          Attributes:
            ITEM_MODEL (org.eclipse.emf.ecore.EClass): final static field
            ITEM_MODEL__ITEMS (org.eclipse.emf.ecore.EReference): final static field
            MODEL_ITEM (org.eclipse.emf.ecore.EClass): final static field
            MODEL_ITEM__NAME (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_ITEM__LABEL (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_ITEM__ICON (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_ITEM__GROUPS (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_ITEM__TAGS (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_ITEM__BINDINGS (org.eclipse.emf.ecore.EReference): final static field
            MODEL_ITEM__TYPE (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_GROUP_ITEM (org.eclipse.emf.ecore.EClass): final static field
            MODEL_GROUP_ITEM__FUNCTION (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_GROUP_ITEM__ARGS (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_NORMAL_ITEM (org.eclipse.emf.ecore.EClass): final static field
            MODEL_BINDING (org.eclipse.emf.ecore.EClass): final static field
            MODEL_BINDING__TYPE (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_BINDING__CONFIGURATION (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_BINDING__PROPERTIES (org.eclipse.emf.ecore.EReference): final static field
            MODEL_PROPERTY (org.eclipse.emf.ecore.EClass): final static field
            MODEL_PROPERTY__KEY (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_PROPERTY__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_GROUP_FUNCTION (org.eclipse.emf.ecore.EEnum): final static field
        
        """
        ITEM_MODEL: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        ITEM_MODEL__ITEMS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        MODEL_ITEM: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_ITEM__NAME: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_ITEM__LABEL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_ITEM__ICON: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_ITEM__GROUPS: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_ITEM__TAGS: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_ITEM__BINDINGS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        MODEL_ITEM__TYPE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_GROUP_ITEM: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_GROUP_ITEM__FUNCTION: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_GROUP_ITEM__ARGS: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_NORMAL_ITEM: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_BINDING: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_BINDING__TYPE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_BINDING__CONFIGURATION: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_BINDING__PROPERTIES: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        MODEL_PROPERTY: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_PROPERTY__KEY: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_PROPERTY__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_GROUP_FUNCTION: typing.ClassVar[org.eclipse.emf.ecore.EEnum] = ...

class ModelBinding(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.items.ModelBinding'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getConfiguration(self) -> java.lang.String: ...
    def getProperties(self) -> org.eclipse.emf.common.util.EList['ModelProperty']: ...
    def getType(self) -> java.lang.String: ...
    def setConfiguration(self, value: java.lang.String) -> None: ...
    def setType(self, value: java.lang.String) -> None: ...

class ModelGroupFunction(java.lang.Enum[org.openhab.core.model.items.ModelGroupFunction], org.eclipse.emf.common.util.Enumerator):
    """
    Java class 'org.openhab.core.model.items.ModelGroupFunction'
    
        Extends:
            java.lang.Enum
    
        Interfaces:
            org.eclipse.emf.common.util.Enumerator
    
      Attributes:
        EQUALITY (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        AND (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        OR (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        NAND (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        NOR (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        AVG (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        SUM (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        MAX (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        MIN (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        COUNT (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        LATEST (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        EARLIEST (org.openhab.core.model.items.ModelGroupFunction): final static enum constant
        EQUALITY_VALUE (int): final static field
        AND_VALUE (int): final static field
        OR_VALUE (int): final static field
        NAND_VALUE (int): final static field
        NOR_VALUE (int): final static field
        AVG_VALUE (int): final static field
        SUM_VALUE (int): final static field
        MAX_VALUE (int): final static field
        MIN_VALUE (int): final static field
        COUNT_VALUE (int): final static field
        LATEST_VALUE (int): final static field
        EARLIEST_VALUE (int): final static field
        VALUES (java.util.List): final static field
    
    """
    EQUALITY: typing.ClassVar['ModelGroupFunction'] = ...
    AND: typing.ClassVar['ModelGroupFunction'] = ...
    OR: typing.ClassVar['ModelGroupFunction'] = ...
    NAND: typing.ClassVar['ModelGroupFunction'] = ...
    NOR: typing.ClassVar['ModelGroupFunction'] = ...
    AVG: typing.ClassVar['ModelGroupFunction'] = ...
    SUM: typing.ClassVar['ModelGroupFunction'] = ...
    MAX: typing.ClassVar['ModelGroupFunction'] = ...
    MIN: typing.ClassVar['ModelGroupFunction'] = ...
    COUNT: typing.ClassVar['ModelGroupFunction'] = ...
    LATEST: typing.ClassVar['ModelGroupFunction'] = ...
    EARLIEST: typing.ClassVar['ModelGroupFunction'] = ...
    EQUALITY_VALUE: typing.ClassVar[int] = ...
    AND_VALUE: typing.ClassVar[int] = ...
    OR_VALUE: typing.ClassVar[int] = ...
    NAND_VALUE: typing.ClassVar[int] = ...
    NOR_VALUE: typing.ClassVar[int] = ...
    AVG_VALUE: typing.ClassVar[int] = ...
    SUM_VALUE: typing.ClassVar[int] = ...
    MAX_VALUE: typing.ClassVar[int] = ...
    MIN_VALUE: typing.ClassVar[int] = ...
    COUNT_VALUE: typing.ClassVar[int] = ...
    LATEST_VALUE: typing.ClassVar[int] = ...
    EARLIEST_VALUE: typing.ClassVar[int] = ...
    VALUES: typing.ClassVar[java.util.List] = ...
    @classmethod
    @typing.overload
    def get(cls, value: int) -> 'ModelGroupFunction': ...
    @classmethod
    @typing.overload
    def get(cls, literal: java.lang.String) -> 'ModelGroupFunction': ...
    @classmethod
    def getByName(cls, name: java.lang.String) -> 'ModelGroupFunction': ...
    def getLiteral(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getValue(self) -> int: ...
    def toString(self) -> java.lang.String: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @classmethod
    @typing.overload
    def valueOf(cls, class_: typing.Type[_valueOf_0__T], string: java.lang.String) -> _valueOf_0__T: ...
    @classmethod
    @typing.overload
    def valueOf(cls, name: java.lang.String) -> 'ModelGroupFunction': ...
    @classmethod
    def values(cls) -> typing.List['ModelGroupFunction']: ...

class ModelItem(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.items.ModelItem'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getBindings(self) -> org.eclipse.emf.common.util.EList[ModelBinding]: ...
    def getGroups(self) -> org.eclipse.emf.common.util.EList[java.lang.String]: ...
    def getIcon(self) -> java.lang.String: ...
    def getLabel(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getTags(self) -> org.eclipse.emf.common.util.EList[java.lang.String]: ...
    def getType(self) -> java.lang.String: ...
    def setIcon(self, value: java.lang.String) -> None: ...
    def setLabel(self, value: java.lang.String) -> None: ...
    def setName(self, value: java.lang.String) -> None: ...
    def setType(self, value: java.lang.String) -> None: ...

class ModelProperty(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.items.ModelProperty'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getKey(self) -> java.lang.String: ...
    def getValue(self) -> typing.Any: ...
    def setKey(self, value: java.lang.String) -> None: ...
    def setValue(self, value: typing.Any) -> None: ...

class ModelGroupItem(ModelItem):
    """
    Java class 'org.openhab.core.model.items.ModelGroupItem'
    
        Interfaces:
            org.openhab.core.model.items.ModelItem
    
    """
    def getArgs(self) -> org.eclipse.emf.common.util.EList[java.lang.String]: ...
    def getFunction(self) -> ModelGroupFunction: ...
    def setFunction(self, value: ModelGroupFunction) -> None: ...

class ModelNormalItem(ModelItem):
    """
    Java class 'org.openhab.core.model.items.ModelNormalItem'
    
        Interfaces:
            org.openhab.core.model.items.ModelItem
    
    """
