import java.lang
import java.lang.annotation
import org.openhab.core.automation
import typing


class ActionInput(java.lang.annotation.Annotation):
    """
    Java class 'org.openhab.core.automation.annotation.ActionInput'
    
        Interfaces:
            java.lang.annotation.Annotation
    
    """
    def defaultValue(self) -> java.lang.String: ...
    def description(self) -> java.lang.String: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def label(self) -> java.lang.String: ...
    def name(self) -> java.lang.String: ...
    def reference(self) -> java.lang.String: ...
    def required(self) -> bool: ...
    def tags(self) -> typing.List[java.lang.String]: ...
    def toString(self) -> java.lang.String: ...
    def type(self) -> java.lang.String: ...

class ActionInputs(java.lang.annotation.Annotation):
    """
    Java class 'org.openhab.core.automation.annotation.ActionInputs'
    
        Interfaces:
            java.lang.annotation.Annotation
    
    """
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...
    def value(self) -> typing.List[ActionInput]: ...

class ActionOutput(java.lang.annotation.Annotation):
    """
    Java class 'org.openhab.core.automation.annotation.ActionOutput'
    
        Interfaces:
            java.lang.annotation.Annotation
    
    """
    def defaultValue(self) -> java.lang.String: ...
    def description(self) -> java.lang.String: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def label(self) -> java.lang.String: ...
    def name(self) -> java.lang.String: ...
    def reference(self) -> java.lang.String: ...
    def tags(self) -> typing.List[java.lang.String]: ...
    def toString(self) -> java.lang.String: ...
    def type(self) -> java.lang.String: ...

class ActionOutputs(java.lang.annotation.Annotation):
    """
    Java class 'org.openhab.core.automation.annotation.ActionOutputs'
    
        Interfaces:
            java.lang.annotation.Annotation
    
    """
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...
    def value(self) -> typing.List[ActionOutput]: ...

class ActionScope(java.lang.annotation.Annotation):
    """
    Java class 'org.openhab.core.automation.annotation.ActionScope'
    
        Interfaces:
            java.lang.annotation.Annotation
    
    """
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def name(self) -> java.lang.String: ...
    def toString(self) -> java.lang.String: ...

class RuleAction(java.lang.annotation.Annotation):
    """
    Java class 'org.openhab.core.automation.annotation.RuleAction'
    
        Interfaces:
            java.lang.annotation.Annotation
    
    """
    def description(self) -> java.lang.String: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def label(self) -> java.lang.String: ...
    def tags(self) -> typing.List[java.lang.String]: ...
    def toString(self) -> java.lang.String: ...
    def visibility(self) -> org.openhab.core.automation.Visibility: ...
