import java.lang
import java.net
import java.time
import typing


class EphemerisManager(java.lang.Object):
    """
    @NonNullByDefault public interface EphemerisManager
    
        This service provides functionality around days of the year and is the central service to be used directly by others.
    
    
    """
    @typing.overload
    def getBankHolidayName(self, date: java.time.ZonedDateTime) -> java.lang.String: ...
    @typing.overload
    def getBankHolidayName(self, date: java.time.ZonedDateTime, filename: java.lang.String) -> java.lang.String: ...
    @typing.overload
    def getBankHolidayName(self, date: java.time.ZonedDateTime, resource: java.net.URL) -> java.lang.String: ...
    @typing.overload
    def getDaysUntil(self, from_: java.time.ZonedDateTime, searchedHoliday: java.lang.String) -> int: ...
    @typing.overload
    def getDaysUntil(self, from_: java.time.ZonedDateTime, searchedHoliday: java.lang.String, filename: java.lang.String) -> int: ...
    @typing.overload
    def getDaysUntil(self, from_: java.time.ZonedDateTime, searchedHoliday: java.lang.String, resource: java.net.URL) -> int: ...
    def getHolidayDescription(self, holiday: java.lang.String) -> java.lang.String: ...
    @typing.overload
    def getNextBankHoliday(self, startDate: java.time.ZonedDateTime) -> java.lang.String: ...
    @typing.overload
    def getNextBankHoliday(self, startDate: java.time.ZonedDateTime, filename: java.lang.String) -> java.lang.String: ...
    @typing.overload
    def getNextBankHoliday(self, startDate: java.time.ZonedDateTime, resource: java.net.URL) -> java.lang.String: ...
    @typing.overload
    def isBankHoliday(self, date: java.time.ZonedDateTime) -> bool: ...
    @typing.overload
    def isBankHoliday(self, date: java.time.ZonedDateTime, filename: java.lang.String) -> bool: ...
    @typing.overload
    def isBankHoliday(self, date: java.time.ZonedDateTime, resource: java.net.URL) -> bool: ...
    def isInDayset(self, daysetName: java.lang.String, date: java.time.ZonedDateTime) -> bool: ...
    def isWeekend(self, date: java.time.ZonedDateTime) -> bool: ...
