import java.lang
import typing


class OpenHAB(java.lang.Object):
    """
    Java class 'org.openhab.core.OpenHAB'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * OpenHAB()
    
      Attributes:
        USERDATA_DIR_PROG_ARGUMENT (java.lang.String): final static field
        CONFIG_DIR_PROG_ARGUMENT (java.lang.String): final static field
        DEFAULT_CONFIG_FOLDER (java.lang.String): final static field
        DEFAULT_USERDATA_FOLDER (java.lang.String): final static field
        SERVICE_CONTEXT (java.lang.String): final static field
        SERVICE_CONTEXT_MARKER (java.lang.String): final static field
        ADDONS_SERVICE_PID (java.lang.String): final static field
        CFG_PACKAGE (java.lang.String): final static field
    
    """
    USERDATA_DIR_PROG_ARGUMENT: typing.ClassVar[java.lang.String] = ...
    CONFIG_DIR_PROG_ARGUMENT: typing.ClassVar[java.lang.String] = ...
    DEFAULT_CONFIG_FOLDER: typing.ClassVar[java.lang.String] = ...
    DEFAULT_USERDATA_FOLDER: typing.ClassVar[java.lang.String] = ...
    SERVICE_CONTEXT: typing.ClassVar[java.lang.String] = ...
    SERVICE_CONTEXT_MARKER: typing.ClassVar[java.lang.String] = ...
    ADDONS_SERVICE_PID: typing.ClassVar[java.lang.String] = ...
    CFG_PACKAGE: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    @classmethod
    def buildString(cls) -> java.lang.String: ...
    @classmethod
    def getConfigFolder(cls) -> java.lang.String: ...
    @classmethod
    def getUserDataFolder(cls) -> java.lang.String: ...
    @classmethod
    def getVersion(cls) -> java.lang.String: ...
