import java.lang
import typing


class PermissionAdmin(java.lang.Object):
    """
    Java class 'org.osgi.service.permissionadmin.PermissionAdmin'
    
    """
    def getDefaultPermissions(self) -> typing.List['PermissionInfo']: ...
    def getLocations(self) -> typing.List[java.lang.String]: ...
    def getPermissions(self, string: java.lang.String) -> typing.List['PermissionInfo']: ...
    def setDefaultPermissions(self, permissionInfoArray: typing.List['PermissionInfo']) -> None: ...
    def setPermissions(self, string: java.lang.String, permissionInfoArray: typing.List['PermissionInfo']) -> None: ...

class PermissionInfo(java.lang.Object):
    """
    Java class 'org.osgi.service.permissionadmin.PermissionInfo'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * PermissionInfo(java.lang.String, java.lang.String, java.lang.String)
        * PermissionInfo(java.lang.String)
    
    """
    @typing.overload
    def __init__(self, string: java.lang.String): ...
    @typing.overload
    def __init__(self, string: java.lang.String, string2: java.lang.String, string3: java.lang.String): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getActions(self) -> java.lang.String: ...
    def getEncoded(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getType(self) -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def toString(self) -> java.lang.String: ...
