import org.eclipse.emf.common.notify
import org.eclipse.emf.common.notify.impl
import org.eclipse.emf.ecore
import org.eclipse.emf.ecore.util
import org.openhab.core.model.items
import typing


class ItemsAdapterFactory(org.eclipse.emf.common.notify.impl.AdapterFactoryImpl):
    """
    Java class 'org.openhab.core.model.items.util.ItemsAdapterFactory'
    
        Extends:
            org.eclipse.emf.common.notify.impl.AdapterFactoryImpl
    
      Constructors:
        * ItemsAdapterFactory()
    
    """
    def __init__(self): ...
    def createAdapter(self, target: org.eclipse.emf.common.notify.Notifier) -> org.eclipse.emf.common.notify.Adapter: ...
    def createEObjectAdapter(self) -> org.eclipse.emf.common.notify.Adapter: ...
    def createItemModelAdapter(self) -> org.eclipse.emf.common.notify.Adapter: ...
    def createModelBindingAdapter(self) -> org.eclipse.emf.common.notify.Adapter: ...
    def createModelGroupItemAdapter(self) -> org.eclipse.emf.common.notify.Adapter: ...
    def createModelItemAdapter(self) -> org.eclipse.emf.common.notify.Adapter: ...
    def createModelNormalItemAdapter(self) -> org.eclipse.emf.common.notify.Adapter: ...
    def createModelPropertyAdapter(self) -> org.eclipse.emf.common.notify.Adapter: ...
    def isFactoryForType(self, object: typing.Any) -> bool: ...

_ItemsSwitch__T = typing.TypeVar('_ItemsSwitch__T')  # <T>
class ItemsSwitch(org.eclipse.emf.ecore.util.Switch[_ItemsSwitch__T], typing.Generic[_ItemsSwitch__T]):
    """
    Java class 'org.openhab.core.model.items.util.ItemsSwitch'
    
        Extends:
            org.eclipse.emf.ecore.util.Switch
    
      Constructors:
        * ItemsSwitch()
    
    """
    def __init__(self): ...
    def caseItemModel(self, object: org.openhab.core.model.items.ItemModel) -> _ItemsSwitch__T: ...
    def caseModelBinding(self, object: org.openhab.core.model.items.ModelBinding) -> _ItemsSwitch__T: ...
    def caseModelGroupItem(self, object: org.openhab.core.model.items.ModelGroupItem) -> _ItemsSwitch__T: ...
    def caseModelItem(self, object: org.openhab.core.model.items.ModelItem) -> _ItemsSwitch__T: ...
    def caseModelNormalItem(self, object: org.openhab.core.model.items.ModelNormalItem) -> _ItemsSwitch__T: ...
    def caseModelProperty(self, object: org.openhab.core.model.items.ModelProperty) -> _ItemsSwitch__T: ...
    def defaultCase(self, object: org.eclipse.emf.ecore.EObject) -> _ItemsSwitch__T: ...
