import java.lang
import org.eclipse.emf.ecore
import org.eclipse.xtext.xbase
import typing


class AbstractUnit(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.script.script.AbstractUnit'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getValue(self) -> java.lang.String: ...
    def setValue(self, value: java.lang.String) -> None: ...

class QuantityLiteral(org.eclipse.xtext.xbase.XExpression):
    """
    Java class 'org.openhab.core.model.script.script.QuantityLiteral'
    
        Interfaces:
            org.eclipse.xtext.xbase.XExpression
    
    """
    def getUnit(self) -> AbstractUnit: ...
    def getValue(self) -> java.lang.String: ...
    def setUnit(self, value: AbstractUnit) -> None: ...
    def setValue(self, value: java.lang.String) -> None: ...

class Script(org.eclipse.xtext.xbase.XBlockExpression):
    """
    Java class 'org.openhab.core.model.script.script.Script'
    
        Interfaces:
            org.eclipse.xtext.xbase.XBlockExpression
    
    """

class ScriptFactory(org.eclipse.emf.ecore.EFactory):
    """
    Java class 'org.openhab.core.model.script.script.ScriptFactory'
    
        Interfaces:
            org.eclipse.emf.ecore.EFactory
    
      Attributes:
        eINSTANCE (org.openhab.core.model.script.script.ScriptFactory): final static field
    
    """
    eINSTANCE: typing.ClassVar['ScriptFactory'] = ...
    def createAbstractUnit(self) -> AbstractUnit: ...
    def createIDUnit(self) -> 'IDUnit': ...
    def createQuantityLiteral(self) -> QuantityLiteral: ...
    def createScript(self) -> Script: ...
    def createSpecificUnit(self) -> 'SpecificUnit': ...
    def createStringUnit(self) -> 'StringUnit': ...
    def getScriptPackage(self) -> 'ScriptPackage': ...

class ScriptPackage(org.eclipse.emf.ecore.EPackage):
    """
    Java class 'org.openhab.core.model.script.script.ScriptPackage'
    
        Interfaces:
            org.eclipse.emf.ecore.EPackage
    
      Attributes:
        eNAME (java.lang.String): final static field
        eNS_URI (java.lang.String): final static field
        eNS_PREFIX (java.lang.String): final static field
        eINSTANCE (org.openhab.core.model.script.script.ScriptPackage): final static field
        ABSTRACT_UNIT (int): final static field
        ABSTRACT_UNIT__VALUE (int): final static field
        ABSTRACT_UNIT_FEATURE_COUNT (int): final static field
        STRING_UNIT (int): final static field
        STRING_UNIT__VALUE (int): final static field
        STRING_UNIT_FEATURE_COUNT (int): final static field
        ID_UNIT (int): final static field
        ID_UNIT__VALUE (int): final static field
        ID_UNIT_FEATURE_COUNT (int): final static field
        SPECIFIC_UNIT (int): final static field
        SPECIFIC_UNIT__VALUE (int): final static field
        SPECIFIC_UNIT_FEATURE_COUNT (int): final static field
        SCRIPT (int): final static field
        SCRIPT__EXPRESSIONS (int): final static field
        SCRIPT_FEATURE_COUNT (int): final static field
        QUANTITY_LITERAL (int): final static field
        QUANTITY_LITERAL__VALUE (int): final static field
        QUANTITY_LITERAL__UNIT (int): final static field
        QUANTITY_LITERAL_FEATURE_COUNT (int): final static field
    
    """
    eNAME: typing.ClassVar[java.lang.String] = ...
    eNS_URI: typing.ClassVar[java.lang.String] = ...
    eNS_PREFIX: typing.ClassVar[java.lang.String] = ...
    eINSTANCE: typing.ClassVar['ScriptPackage'] = ...
    ABSTRACT_UNIT: typing.ClassVar[int] = ...
    ABSTRACT_UNIT__VALUE: typing.ClassVar[int] = ...
    ABSTRACT_UNIT_FEATURE_COUNT: typing.ClassVar[int] = ...
    STRING_UNIT: typing.ClassVar[int] = ...
    STRING_UNIT__VALUE: typing.ClassVar[int] = ...
    STRING_UNIT_FEATURE_COUNT: typing.ClassVar[int] = ...
    ID_UNIT: typing.ClassVar[int] = ...
    ID_UNIT__VALUE: typing.ClassVar[int] = ...
    ID_UNIT_FEATURE_COUNT: typing.ClassVar[int] = ...
    SPECIFIC_UNIT: typing.ClassVar[int] = ...
    SPECIFIC_UNIT__VALUE: typing.ClassVar[int] = ...
    SPECIFIC_UNIT_FEATURE_COUNT: typing.ClassVar[int] = ...
    SCRIPT: typing.ClassVar[int] = ...
    SCRIPT__EXPRESSIONS: typing.ClassVar[int] = ...
    SCRIPT_FEATURE_COUNT: typing.ClassVar[int] = ...
    QUANTITY_LITERAL: typing.ClassVar[int] = ...
    QUANTITY_LITERAL__VALUE: typing.ClassVar[int] = ...
    QUANTITY_LITERAL__UNIT: typing.ClassVar[int] = ...
    QUANTITY_LITERAL_FEATURE_COUNT: typing.ClassVar[int] = ...
    def getAbstractUnit(self) -> org.eclipse.emf.ecore.EClass: ...
    def getAbstractUnit_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getIDUnit(self) -> org.eclipse.emf.ecore.EClass: ...
    def getQuantityLiteral(self) -> org.eclipse.emf.ecore.EClass: ...
    def getQuantityLiteral_Unit(self) -> org.eclipse.emf.ecore.EReference: ...
    def getQuantityLiteral_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getScript(self) -> org.eclipse.emf.ecore.EClass: ...
    def getScriptFactory(self) -> ScriptFactory: ...
    def getSpecificUnit(self) -> org.eclipse.emf.ecore.EClass: ...
    def getStringUnit(self) -> org.eclipse.emf.ecore.EClass: ...
    class Literals(java.lang.Object):
        """
        Java class 'org.openhab.core.model.script.script.ScriptPackage$Literals'
        
          Attributes:
            ABSTRACT_UNIT (org.eclipse.emf.ecore.EClass): final static field
            ABSTRACT_UNIT__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            STRING_UNIT (org.eclipse.emf.ecore.EClass): final static field
            ID_UNIT (org.eclipse.emf.ecore.EClass): final static field
            SPECIFIC_UNIT (org.eclipse.emf.ecore.EClass): final static field
            SCRIPT (org.eclipse.emf.ecore.EClass): final static field
            QUANTITY_LITERAL (org.eclipse.emf.ecore.EClass): final static field
            QUANTITY_LITERAL__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            QUANTITY_LITERAL__UNIT (org.eclipse.emf.ecore.EReference): final static field
        
        """
        ABSTRACT_UNIT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        ABSTRACT_UNIT__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        STRING_UNIT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        ID_UNIT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SPECIFIC_UNIT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SCRIPT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        QUANTITY_LITERAL: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        QUANTITY_LITERAL__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        QUANTITY_LITERAL__UNIT: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...

class IDUnit(AbstractUnit):
    """
    Java class 'org.openhab.core.model.script.script.IDUnit'
    
        Interfaces:
            org.openhab.core.model.script.script.AbstractUnit
    
    """

class SpecificUnit(AbstractUnit):
    """
    Java class 'org.openhab.core.model.script.script.SpecificUnit'
    
        Interfaces:
            org.openhab.core.model.script.script.AbstractUnit
    
    """

class StringUnit(AbstractUnit):
    """
    Java class 'org.openhab.core.model.script.script.StringUnit'
    
        Interfaces:
            org.openhab.core.model.script.script.AbstractUnit
    
    """
