import java.lang
import java.math
import org.eclipse.emf.common.util
import org.eclipse.emf.ecore
import typing


class AllConfig(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.AllConfig'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """

class Filter(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.Filter'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getDefinition(self) -> 'FilterDetails': ...
    def getName(self) -> java.lang.String: ...
    def setDefinition(self, value: 'FilterDetails') -> None: ...
    def setName(self, value: java.lang.String) -> None: ...

class FilterDetails(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.FilterDetails'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """

class GroupConfig(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.GroupConfig'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getGroup(self) -> java.lang.String: ...
    def setGroup(self, value: java.lang.String) -> None: ...

class ItemConfig(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.ItemConfig'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getItem(self) -> java.lang.String: ...
    def setItem(self, value: java.lang.String) -> None: ...

class PersistenceConfiguration(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.PersistenceConfiguration'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getAlias(self) -> java.lang.String: ...
    def getFilters(self) -> org.eclipse.emf.common.util.EList[Filter]: ...
    def getItems(self) -> org.eclipse.emf.common.util.EList[org.eclipse.emf.ecore.EObject]: ...
    def getStrategies(self) -> org.eclipse.emf.common.util.EList['Strategy']: ...
    def setAlias(self, value: java.lang.String) -> None: ...

class PersistenceFactory(org.eclipse.emf.ecore.EFactory):
    """
    Java class 'org.openhab.core.model.persistence.persistence.PersistenceFactory'
    
        Interfaces:
            org.eclipse.emf.ecore.EFactory
    
      Attributes:
        eINSTANCE (org.openhab.core.model.persistence.persistence.PersistenceFactory): final static field
    
    """
    eINSTANCE: typing.ClassVar['PersistenceFactory'] = ...
    def createAllConfig(self) -> AllConfig: ...
    def createCronStrategy(self) -> 'CronStrategy': ...
    def createFilter(self) -> Filter: ...
    def createFilterDetails(self) -> FilterDetails: ...
    def createGroupConfig(self) -> GroupConfig: ...
    def createItemConfig(self) -> ItemConfig: ...
    def createPersistenceConfiguration(self) -> PersistenceConfiguration: ...
    def createPersistenceModel(self) -> 'PersistenceModel': ...
    def createStrategy(self) -> 'Strategy': ...
    def createThresholdFilter(self) -> 'ThresholdFilter': ...
    def createTimeFilter(self) -> 'TimeFilter': ...
    def getPersistencePackage(self) -> 'PersistencePackage': ...

class PersistenceModel(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.PersistenceModel'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getConfigs(self) -> org.eclipse.emf.common.util.EList[PersistenceConfiguration]: ...
    def getDefaults(self) -> org.eclipse.emf.common.util.EList['Strategy']: ...
    def getFilters(self) -> org.eclipse.emf.common.util.EList[Filter]: ...
    def getStrategies(self) -> org.eclipse.emf.common.util.EList['Strategy']: ...

class PersistencePackage(org.eclipse.emf.ecore.EPackage):
    """
    Java class 'org.openhab.core.model.persistence.persistence.PersistencePackage'
    
        Interfaces:
            org.eclipse.emf.ecore.EPackage
    
      Attributes:
        eNAME (java.lang.String): final static field
        eNS_URI (java.lang.String): final static field
        eNS_PREFIX (java.lang.String): final static field
        eINSTANCE (org.openhab.core.model.persistence.persistence.PersistencePackage): final static field
        PERSISTENCE_MODEL (int): final static field
        PERSISTENCE_MODEL__STRATEGIES (int): final static field
        PERSISTENCE_MODEL__DEFAULTS (int): final static field
        PERSISTENCE_MODEL__FILTERS (int): final static field
        PERSISTENCE_MODEL__CONFIGS (int): final static field
        PERSISTENCE_MODEL_FEATURE_COUNT (int): final static field
        STRATEGY (int): final static field
        STRATEGY__NAME (int): final static field
        STRATEGY_FEATURE_COUNT (int): final static field
        FILTER (int): final static field
        FILTER__NAME (int): final static field
        FILTER__DEFINITION (int): final static field
        FILTER_FEATURE_COUNT (int): final static field
        FILTER_DETAILS (int): final static field
        FILTER_DETAILS_FEATURE_COUNT (int): final static field
        THRESHOLD_FILTER (int): final static field
        THRESHOLD_FILTER__VALUE (int): final static field
        THRESHOLD_FILTER__PERCENT (int): final static field
        THRESHOLD_FILTER_FEATURE_COUNT (int): final static field
        TIME_FILTER (int): final static field
        TIME_FILTER__VALUE (int): final static field
        TIME_FILTER__UNIT (int): final static field
        TIME_FILTER_FEATURE_COUNT (int): final static field
        PERSISTENCE_CONFIGURATION (int): final static field
        PERSISTENCE_CONFIGURATION__ITEMS (int): final static field
        PERSISTENCE_CONFIGURATION__ALIAS (int): final static field
        PERSISTENCE_CONFIGURATION__STRATEGIES (int): final static field
        PERSISTENCE_CONFIGURATION__FILTERS (int): final static field
        PERSISTENCE_CONFIGURATION_FEATURE_COUNT (int): final static field
        ALL_CONFIG (int): final static field
        ALL_CONFIG_FEATURE_COUNT (int): final static field
        ITEM_CONFIG (int): final static field
        ITEM_CONFIG__ITEM (int): final static field
        ITEM_CONFIG_FEATURE_COUNT (int): final static field
        GROUP_CONFIG (int): final static field
        GROUP_CONFIG__GROUP (int): final static field
        GROUP_CONFIG_FEATURE_COUNT (int): final static field
        CRON_STRATEGY (int): final static field
        CRON_STRATEGY__NAME (int): final static field
        CRON_STRATEGY__CRON_EXPRESSION (int): final static field
        CRON_STRATEGY_FEATURE_COUNT (int): final static field
    
    """
    eNAME: typing.ClassVar[java.lang.String] = ...
    eNS_URI: typing.ClassVar[java.lang.String] = ...
    eNS_PREFIX: typing.ClassVar[java.lang.String] = ...
    eINSTANCE: typing.ClassVar['PersistencePackage'] = ...
    PERSISTENCE_MODEL: typing.ClassVar[int] = ...
    PERSISTENCE_MODEL__STRATEGIES: typing.ClassVar[int] = ...
    PERSISTENCE_MODEL__DEFAULTS: typing.ClassVar[int] = ...
    PERSISTENCE_MODEL__FILTERS: typing.ClassVar[int] = ...
    PERSISTENCE_MODEL__CONFIGS: typing.ClassVar[int] = ...
    PERSISTENCE_MODEL_FEATURE_COUNT: typing.ClassVar[int] = ...
    STRATEGY: typing.ClassVar[int] = ...
    STRATEGY__NAME: typing.ClassVar[int] = ...
    STRATEGY_FEATURE_COUNT: typing.ClassVar[int] = ...
    FILTER: typing.ClassVar[int] = ...
    FILTER__NAME: typing.ClassVar[int] = ...
    FILTER__DEFINITION: typing.ClassVar[int] = ...
    FILTER_FEATURE_COUNT: typing.ClassVar[int] = ...
    FILTER_DETAILS: typing.ClassVar[int] = ...
    FILTER_DETAILS_FEATURE_COUNT: typing.ClassVar[int] = ...
    THRESHOLD_FILTER: typing.ClassVar[int] = ...
    THRESHOLD_FILTER__VALUE: typing.ClassVar[int] = ...
    THRESHOLD_FILTER__PERCENT: typing.ClassVar[int] = ...
    THRESHOLD_FILTER_FEATURE_COUNT: typing.ClassVar[int] = ...
    TIME_FILTER: typing.ClassVar[int] = ...
    TIME_FILTER__VALUE: typing.ClassVar[int] = ...
    TIME_FILTER__UNIT: typing.ClassVar[int] = ...
    TIME_FILTER_FEATURE_COUNT: typing.ClassVar[int] = ...
    PERSISTENCE_CONFIGURATION: typing.ClassVar[int] = ...
    PERSISTENCE_CONFIGURATION__ITEMS: typing.ClassVar[int] = ...
    PERSISTENCE_CONFIGURATION__ALIAS: typing.ClassVar[int] = ...
    PERSISTENCE_CONFIGURATION__STRATEGIES: typing.ClassVar[int] = ...
    PERSISTENCE_CONFIGURATION__FILTERS: typing.ClassVar[int] = ...
    PERSISTENCE_CONFIGURATION_FEATURE_COUNT: typing.ClassVar[int] = ...
    ALL_CONFIG: typing.ClassVar[int] = ...
    ALL_CONFIG_FEATURE_COUNT: typing.ClassVar[int] = ...
    ITEM_CONFIG: typing.ClassVar[int] = ...
    ITEM_CONFIG__ITEM: typing.ClassVar[int] = ...
    ITEM_CONFIG_FEATURE_COUNT: typing.ClassVar[int] = ...
    GROUP_CONFIG: typing.ClassVar[int] = ...
    GROUP_CONFIG__GROUP: typing.ClassVar[int] = ...
    GROUP_CONFIG_FEATURE_COUNT: typing.ClassVar[int] = ...
    CRON_STRATEGY: typing.ClassVar[int] = ...
    CRON_STRATEGY__NAME: typing.ClassVar[int] = ...
    CRON_STRATEGY__CRON_EXPRESSION: typing.ClassVar[int] = ...
    CRON_STRATEGY_FEATURE_COUNT: typing.ClassVar[int] = ...
    def getAllConfig(self) -> org.eclipse.emf.ecore.EClass: ...
    def getCronStrategy(self) -> org.eclipse.emf.ecore.EClass: ...
    def getCronStrategy_CronExpression(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getFilter(self) -> org.eclipse.emf.ecore.EClass: ...
    def getFilterDetails(self) -> org.eclipse.emf.ecore.EClass: ...
    def getFilter_Definition(self) -> org.eclipse.emf.ecore.EReference: ...
    def getFilter_Name(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getGroupConfig(self) -> org.eclipse.emf.ecore.EClass: ...
    def getGroupConfig_Group(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getItemConfig(self) -> org.eclipse.emf.ecore.EClass: ...
    def getItemConfig_Item(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getPersistenceConfiguration(self) -> org.eclipse.emf.ecore.EClass: ...
    def getPersistenceConfiguration_Alias(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getPersistenceConfiguration_Filters(self) -> org.eclipse.emf.ecore.EReference: ...
    def getPersistenceConfiguration_Items(self) -> org.eclipse.emf.ecore.EReference: ...
    def getPersistenceConfiguration_Strategies(self) -> org.eclipse.emf.ecore.EReference: ...
    def getPersistenceFactory(self) -> PersistenceFactory: ...
    def getPersistenceModel(self) -> org.eclipse.emf.ecore.EClass: ...
    def getPersistenceModel_Configs(self) -> org.eclipse.emf.ecore.EReference: ...
    def getPersistenceModel_Defaults(self) -> org.eclipse.emf.ecore.EReference: ...
    def getPersistenceModel_Filters(self) -> org.eclipse.emf.ecore.EReference: ...
    def getPersistenceModel_Strategies(self) -> org.eclipse.emf.ecore.EReference: ...
    def getStrategy(self) -> org.eclipse.emf.ecore.EClass: ...
    def getStrategy_Name(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getThresholdFilter(self) -> org.eclipse.emf.ecore.EClass: ...
    def getThresholdFilter_Percent(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getThresholdFilter_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getTimeFilter(self) -> org.eclipse.emf.ecore.EClass: ...
    def getTimeFilter_Unit(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getTimeFilter_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    class Literals(java.lang.Object):
        """
        Java class 'org.openhab.core.model.persistence.persistence.PersistencePackage$Literals'
        
          Attributes:
            PERSISTENCE_MODEL (org.eclipse.emf.ecore.EClass): final static field
            PERSISTENCE_MODEL__STRATEGIES (org.eclipse.emf.ecore.EReference): final static field
            PERSISTENCE_MODEL__DEFAULTS (org.eclipse.emf.ecore.EReference): final static field
            PERSISTENCE_MODEL__FILTERS (org.eclipse.emf.ecore.EReference): final static field
            PERSISTENCE_MODEL__CONFIGS (org.eclipse.emf.ecore.EReference): final static field
            STRATEGY (org.eclipse.emf.ecore.EClass): final static field
            STRATEGY__NAME (org.eclipse.emf.ecore.EAttribute): final static field
            FILTER (org.eclipse.emf.ecore.EClass): final static field
            FILTER__NAME (org.eclipse.emf.ecore.EAttribute): final static field
            FILTER__DEFINITION (org.eclipse.emf.ecore.EReference): final static field
            FILTER_DETAILS (org.eclipse.emf.ecore.EClass): final static field
            THRESHOLD_FILTER (org.eclipse.emf.ecore.EClass): final static field
            THRESHOLD_FILTER__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            THRESHOLD_FILTER__PERCENT (org.eclipse.emf.ecore.EAttribute): final static field
            TIME_FILTER (org.eclipse.emf.ecore.EClass): final static field
            TIME_FILTER__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            TIME_FILTER__UNIT (org.eclipse.emf.ecore.EAttribute): final static field
            PERSISTENCE_CONFIGURATION (org.eclipse.emf.ecore.EClass): final static field
            PERSISTENCE_CONFIGURATION__ITEMS (org.eclipse.emf.ecore.EReference): final static field
            PERSISTENCE_CONFIGURATION__ALIAS (org.eclipse.emf.ecore.EAttribute): final static field
            PERSISTENCE_CONFIGURATION__STRATEGIES (org.eclipse.emf.ecore.EReference): final static field
            PERSISTENCE_CONFIGURATION__FILTERS (org.eclipse.emf.ecore.EReference): final static field
            ALL_CONFIG (org.eclipse.emf.ecore.EClass): final static field
            ITEM_CONFIG (org.eclipse.emf.ecore.EClass): final static field
            ITEM_CONFIG__ITEM (org.eclipse.emf.ecore.EAttribute): final static field
            GROUP_CONFIG (org.eclipse.emf.ecore.EClass): final static field
            GROUP_CONFIG__GROUP (org.eclipse.emf.ecore.EAttribute): final static field
            CRON_STRATEGY (org.eclipse.emf.ecore.EClass): final static field
            CRON_STRATEGY__CRON_EXPRESSION (org.eclipse.emf.ecore.EAttribute): final static field
        
        """
        PERSISTENCE_MODEL: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        PERSISTENCE_MODEL__STRATEGIES: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        PERSISTENCE_MODEL__DEFAULTS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        PERSISTENCE_MODEL__FILTERS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        PERSISTENCE_MODEL__CONFIGS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        STRATEGY: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        STRATEGY__NAME: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        FILTER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        FILTER__NAME: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        FILTER__DEFINITION: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        FILTER_DETAILS: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        THRESHOLD_FILTER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        THRESHOLD_FILTER__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        THRESHOLD_FILTER__PERCENT: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        TIME_FILTER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        TIME_FILTER__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        TIME_FILTER__UNIT: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        PERSISTENCE_CONFIGURATION: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        PERSISTENCE_CONFIGURATION__ITEMS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        PERSISTENCE_CONFIGURATION__ALIAS: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        PERSISTENCE_CONFIGURATION__STRATEGIES: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        PERSISTENCE_CONFIGURATION__FILTERS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        ALL_CONFIG: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        ITEM_CONFIG: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        ITEM_CONFIG__ITEM: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        GROUP_CONFIG: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        GROUP_CONFIG__GROUP: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        CRON_STRATEGY: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        CRON_STRATEGY__CRON_EXPRESSION: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...

class Strategy(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.persistence.persistence.Strategy'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getName(self) -> java.lang.String: ...
    def setName(self, value: java.lang.String) -> None: ...

class CronStrategy(Strategy):
    """
    Java class 'org.openhab.core.model.persistence.persistence.CronStrategy'
    
        Interfaces:
            org.openhab.core.model.persistence.persistence.Strategy
    
    """
    def getCronExpression(self) -> java.lang.String: ...
    def setCronExpression(self, value: java.lang.String) -> None: ...

class ThresholdFilter(FilterDetails):
    """
    Java class 'org.openhab.core.model.persistence.persistence.ThresholdFilter'
    
        Interfaces:
            org.openhab.core.model.persistence.persistence.FilterDetails
    
    """
    def getValue(self) -> java.math.BigDecimal: ...
    def isPercent(self) -> bool: ...
    def setPercent(self, value: bool) -> None: ...
    def setValue(self, value: java.math.BigDecimal) -> None: ...

class TimeFilter(FilterDetails):
    """
    Java class 'org.openhab.core.model.persistence.persistence.TimeFilter'
    
        Interfaces:
            org.openhab.core.model.persistence.persistence.FilterDetails
    
    """
    def getUnit(self) -> java.lang.String: ...
    def getValue(self) -> int: ...
    def setUnit(self, value: java.lang.String) -> None: ...
    def setValue(self, value: int) -> None: ...
