import java.lang
import java.net
import java.util
import org
import org.openhab.core.thing.type
import org.openhab.core.types


class StateChannelTypeBuilderImpl(org.openhab.core.thing.internal.type.AbstractChannelTypeBuilder[org.openhab.core.thing.type.StateChannelTypeBuilder], org.openhab.core.thing.type.StateChannelTypeBuilder):
    """
    Java class 'org.openhab.core.thing.internal.type.StateChannelTypeBuilderImpl'
    
        Extends:
            org.openhab.core.thing.internal.type.AbstractChannelTypeBuilder
    
        Interfaces:
            org.openhab.core.thing.type.StateChannelTypeBuilder
    
      Constructors:
        * StateChannelTypeBuilderImpl(org.openhab.core.thing.type.ChannelTypeUID, java.lang.String, java.lang.String)
    
    """
    def __init__(self, channelTypeUID: org.openhab.core.thing.type.ChannelTypeUID, label: java.lang.String, itemType: java.lang.String): ...
    def build(self) -> org.openhab.core.thing.type.ChannelType: ...
    def isAdvanced(self, boolean: bool) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withAutoUpdatePolicy(self, autoUpdatePolicy: org.openhab.core.thing.type.AutoUpdatePolicy) -> org.openhab.core.thing.type.StateChannelTypeBuilder: ...
    def withCategory(self, string: java.lang.String) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withCommandDescription(self, commandDescription: org.openhab.core.types.CommandDescription) -> org.openhab.core.thing.type.StateChannelTypeBuilder: ...
    def withConfigDescriptionURI(self, uRI: java.net.URI) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withDescription(self, string: java.lang.String) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withStateDescriptionFragment(self, stateDescriptionFragment: org.openhab.core.types.StateDescriptionFragment) -> org.openhab.core.thing.type.StateChannelTypeBuilder: ...
    def withTag(self, string: java.lang.String) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withTags(self, collection: java.util.Collection) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...

class TriggerChannelTypeBuilderImpl(org.openhab.core.thing.internal.type.AbstractChannelTypeBuilder[org.openhab.core.thing.type.TriggerChannelTypeBuilder], org.openhab.core.thing.type.TriggerChannelTypeBuilder):
    """
    Java class 'org.openhab.core.thing.internal.type.TriggerChannelTypeBuilderImpl'
    
        Extends:
            org.openhab.core.thing.internal.type.AbstractChannelTypeBuilder
    
        Interfaces:
            org.openhab.core.thing.type.TriggerChannelTypeBuilder
    
      Constructors:
        * TriggerChannelTypeBuilderImpl(org.openhab.core.thing.type.ChannelTypeUID, java.lang.String)
    
    """
    def __init__(self, channelTypeUID: org.openhab.core.thing.type.ChannelTypeUID, label: java.lang.String): ...
    def build(self) -> org.openhab.core.thing.type.ChannelType: ...
    def isAdvanced(self, boolean: bool) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withCategory(self, string: java.lang.String) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withConfigDescriptionURI(self, uRI: java.net.URI) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withDescription(self, string: java.lang.String) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withEventDescription(self, eventDescription: org.openhab.core.types.EventDescription) -> org.openhab.core.thing.type.TriggerChannelTypeBuilder: ...
    def withTag(self, string: java.lang.String) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...
    def withTags(self, collection: java.util.Collection) -> org.openhab.core.thing.type.ChannelTypeBuilder: ...

class AbstractChannelTypeBuilder: ...
