import java.lang
import java.net
import java.util
import org.apache.karaf.features
import org.openhab.core.addon
import org.osgi.service.cm
import typing


class FeatureInstaller(org.osgi.service.cm.ConfigurationListener):
    """
    Java class 'org.openhab.core.karaf.internal.FeatureInstaller'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            org.osgi.service.cm.ConfigurationListener
    
      Constructors:
        * FeatureInstaller(org.osgi.service.cm.ConfigurationAdmin, org.apache.karaf.features.FeaturesService)
    
      Attributes:
        EXTENSION_TYPE_AUTOMATION (java.lang.String): final static field
        EXTENSION_TYPE_BINDING (java.lang.String): final static field
        EXTENSION_TYPE_MISC (java.lang.String): final static field
        EXTENSION_TYPE_PERSISTENCE (java.lang.String): final static field
        EXTENSION_TYPE_TRANSFORMATION (java.lang.String): final static field
        EXTENSION_TYPE_UI (java.lang.String): final static field
        EXTENSION_TYPE_VOICE (java.lang.String): final static field
        SIMPLE_PACKAGE (java.lang.String): final static field
        MINIMAL_PACKAGE (java.lang.String): final static field
        STANDARD_PACKAGE (java.lang.String): final static field
        PREFIX (java.lang.String): final static field
        PREFIX_PACKAGE (java.lang.String): final static field
        EXTENSION_TYPES ([Ljava.lang.String;): final static field
    
    """
    EXTENSION_TYPE_AUTOMATION: typing.ClassVar[java.lang.String] = ...
    EXTENSION_TYPE_BINDING: typing.ClassVar[java.lang.String] = ...
    EXTENSION_TYPE_MISC: typing.ClassVar[java.lang.String] = ...
    EXTENSION_TYPE_PERSISTENCE: typing.ClassVar[java.lang.String] = ...
    EXTENSION_TYPE_TRANSFORMATION: typing.ClassVar[java.lang.String] = ...
    EXTENSION_TYPE_UI: typing.ClassVar[java.lang.String] = ...
    EXTENSION_TYPE_VOICE: typing.ClassVar[java.lang.String] = ...
    SIMPLE_PACKAGE: typing.ClassVar[java.lang.String] = ...
    MINIMAL_PACKAGE: typing.ClassVar[java.lang.String] = ...
    STANDARD_PACKAGE: typing.ClassVar[java.lang.String] = ...
    PREFIX: typing.ClassVar[java.lang.String] = ...
    PREFIX_PACKAGE: typing.ClassVar[java.lang.String] = ...
    EXTENSION_TYPES: typing.ClassVar[typing.List[java.lang.String]] = ...
    def __init__(self, configurationAdmin: org.osgi.service.cm.ConfigurationAdmin, featuresService: org.apache.karaf.features.FeaturesService): ...
    def addAddon(self, type: java.lang.String, id: java.lang.String) -> bool: ...
    def configurationEvent(self, event: org.osgi.service.cm.ConfigurationEvent) -> None: ...
    def removeAddon(self, type: java.lang.String, id: java.lang.String) -> bool: ...

class KarafAddonService(org.openhab.core.addon.AddonService):
    """
    Java class 'org.openhab.core.karaf.internal.KarafAddonService'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            org.openhab.core.addon.AddonService
    
      Constructors:
        * KarafAddonService(org.openhab.core.karaf.internal.FeatureInstaller, org.apache.karaf.features.FeaturesService)
    
    """
    def __init__(self, featureInstaller: FeatureInstaller, featuresService: org.apache.karaf.features.FeaturesService): ...
    def getAddon(self, id: java.lang.String, locale: java.util.Locale) -> org.openhab.core.addon.Addon: ...
    def getAddonId(self, addonURI: java.net.URI) -> java.lang.String: ...
    def getAddons(self, locale: java.util.Locale) -> java.util.List[org.openhab.core.addon.Addon]: ...
    def getTypes(self, locale: java.util.Locale) -> java.util.List[org.openhab.core.addon.AddonType]: ...
    def install(self, id: java.lang.String) -> None: ...
    def uninstall(self, id: java.lang.String) -> None: ...
