import java.lang
import java.math
import org.eclipse.emf.common.util
import org.eclipse.emf.ecore
import typing


class ColorArray(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.ColorArray'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getArg(self) -> java.lang.String: ...
    def getCondition(self) -> java.lang.String: ...
    def getItem(self) -> java.lang.String: ...
    def getSign(self) -> java.lang.String: ...
    def getState(self) -> java.lang.String: ...
    def setArg(self, value: java.lang.String) -> None: ...
    def setCondition(self, value: java.lang.String) -> None: ...
    def setItem(self, value: java.lang.String) -> None: ...
    def setSign(self, value: java.lang.String) -> None: ...
    def setState(self, value: java.lang.String) -> None: ...

class Mapping(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Mapping'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getCmd(self) -> java.lang.String: ...
    def getLabel(self) -> java.lang.String: ...
    def setCmd(self, value: java.lang.String) -> None: ...
    def setLabel(self, value: java.lang.String) -> None: ...

class SitemapFactory(org.eclipse.emf.ecore.EFactory):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.SitemapFactory'
    
        Interfaces:
            org.eclipse.emf.ecore.EFactory
    
      Attributes:
        eINSTANCE (org.openhab.core.model.sitemap.sitemap.SitemapFactory): final static field
    
    """
    eINSTANCE: typing.ClassVar['SitemapFactory'] = ...
    def createChart(self) -> 'Chart': ...
    def createColorArray(self) -> ColorArray: ...
    def createColorpicker(self) -> 'Colorpicker': ...
    def createDefault(self) -> 'Default': ...
    def createFrame(self) -> 'Frame': ...
    def createGroup(self) -> 'Group': ...
    def createImage(self) -> 'Image': ...
    def createLinkableWidget(self) -> 'LinkableWidget': ...
    def createList(self) -> 'List': ...
    def createMapping(self) -> Mapping: ...
    def createMapview(self) -> 'Mapview': ...
    def createNonLinkableWidget(self) -> 'NonLinkableWidget': ...
    def createSelection(self) -> 'Selection': ...
    def createSetpoint(self) -> 'Setpoint': ...
    def createSitemap(self) -> 'Sitemap': ...
    def createSitemapModel(self) -> 'SitemapModel': ...
    def createSlider(self) -> 'Slider': ...
    def createSwitch(self) -> 'Switch': ...
    def createText(self) -> 'Text': ...
    def createVideo(self) -> 'Video': ...
    def createVisibilityRule(self) -> 'VisibilityRule': ...
    def createWebview(self) -> 'Webview': ...
    def createWidget(self) -> 'Widget': ...
    def getSitemapPackage(self) -> 'SitemapPackage': ...

class SitemapModel(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.SitemapModel'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """

class SitemapPackage(org.eclipse.emf.ecore.EPackage):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.SitemapPackage'
    
        Interfaces:
            org.eclipse.emf.ecore.EPackage
    
      Attributes:
        eNAME (java.lang.String): final static field
        eNS_URI (java.lang.String): final static field
        eNS_PREFIX (java.lang.String): final static field
        eINSTANCE (org.openhab.core.model.sitemap.sitemap.SitemapPackage): final static field
        SITEMAP_MODEL (int): final static field
        SITEMAP_MODEL_FEATURE_COUNT (int): final static field
        SITEMAP (int): final static field
        SITEMAP__NAME (int): final static field
        SITEMAP__LABEL (int): final static field
        SITEMAP__ICON (int): final static field
        SITEMAP__CHILDREN (int): final static field
        SITEMAP_FEATURE_COUNT (int): final static field
        WIDGET (int): final static field
        WIDGET__ITEM (int): final static field
        WIDGET__LABEL (int): final static field
        WIDGET__ICON (int): final static field
        WIDGET__LABEL_COLOR (int): final static field
        WIDGET__VALUE_COLOR (int): final static field
        WIDGET__VISIBILITY (int): final static field
        WIDGET_FEATURE_COUNT (int): final static field
        NON_LINKABLE_WIDGET (int): final static field
        NON_LINKABLE_WIDGET__ITEM (int): final static field
        NON_LINKABLE_WIDGET__LABEL (int): final static field
        NON_LINKABLE_WIDGET__ICON (int): final static field
        NON_LINKABLE_WIDGET__LABEL_COLOR (int): final static field
        NON_LINKABLE_WIDGET__VALUE_COLOR (int): final static field
        NON_LINKABLE_WIDGET__VISIBILITY (int): final static field
        NON_LINKABLE_WIDGET_FEATURE_COUNT (int): final static field
        LINKABLE_WIDGET (int): final static field
        LINKABLE_WIDGET__ITEM (int): final static field
        LINKABLE_WIDGET__LABEL (int): final static field
        LINKABLE_WIDGET__ICON (int): final static field
        LINKABLE_WIDGET__LABEL_COLOR (int): final static field
        LINKABLE_WIDGET__VALUE_COLOR (int): final static field
        LINKABLE_WIDGET__VISIBILITY (int): final static field
        LINKABLE_WIDGET__CHILDREN (int): final static field
        LINKABLE_WIDGET_FEATURE_COUNT (int): final static field
        FRAME (int): final static field
        FRAME__ITEM (int): final static field
        FRAME__LABEL (int): final static field
        FRAME__ICON (int): final static field
        FRAME__LABEL_COLOR (int): final static field
        FRAME__VALUE_COLOR (int): final static field
        FRAME__VISIBILITY (int): final static field
        FRAME__CHILDREN (int): final static field
        FRAME_FEATURE_COUNT (int): final static field
        TEXT (int): final static field
        TEXT__ITEM (int): final static field
        TEXT__LABEL (int): final static field
        TEXT__ICON (int): final static field
        TEXT__LABEL_COLOR (int): final static field
        TEXT__VALUE_COLOR (int): final static field
        TEXT__VISIBILITY (int): final static field
        TEXT__CHILDREN (int): final static field
        TEXT_FEATURE_COUNT (int): final static field
        GROUP (int): final static field
        GROUP__ITEM (int): final static field
        GROUP__LABEL (int): final static field
        GROUP__ICON (int): final static field
        GROUP__LABEL_COLOR (int): final static field
        GROUP__VALUE_COLOR (int): final static field
        GROUP__VISIBILITY (int): final static field
        GROUP__CHILDREN (int): final static field
        GROUP_FEATURE_COUNT (int): final static field
        IMAGE (int): final static field
        IMAGE__ITEM (int): final static field
        IMAGE__LABEL (int): final static field
        IMAGE__ICON (int): final static field
        IMAGE__LABEL_COLOR (int): final static field
        IMAGE__VALUE_COLOR (int): final static field
        IMAGE__VISIBILITY (int): final static field
        IMAGE__CHILDREN (int): final static field
        IMAGE__URL (int): final static field
        IMAGE__REFRESH (int): final static field
        IMAGE__ICON_COLOR (int): final static field
        IMAGE_FEATURE_COUNT (int): final static field
        VIDEO (int): final static field
        VIDEO__ITEM (int): final static field
        VIDEO__LABEL (int): final static field
        VIDEO__ICON (int): final static field
        VIDEO__LABEL_COLOR (int): final static field
        VIDEO__VALUE_COLOR (int): final static field
        VIDEO__VISIBILITY (int): final static field
        VIDEO__URL (int): final static field
        VIDEO__ENCODING (int): final static field
        VIDEO_FEATURE_COUNT (int): final static field
        CHART (int): final static field
        CHART__ITEM (int): final static field
        CHART__LABEL (int): final static field
        CHART__ICON (int): final static field
        CHART__LABEL_COLOR (int): final static field
        CHART__VALUE_COLOR (int): final static field
        CHART__VISIBILITY (int): final static field
        CHART__SERVICE (int): final static field
        CHART__REFRESH (int): final static field
        CHART__PERIOD (int): final static field
        CHART__LEGEND (int): final static field
        CHART_FEATURE_COUNT (int): final static field
        WEBVIEW (int): final static field
        WEBVIEW__ITEM (int): final static field
        WEBVIEW__LABEL (int): final static field
        WEBVIEW__ICON (int): final static field
        WEBVIEW__LABEL_COLOR (int): final static field
        WEBVIEW__VALUE_COLOR (int): final static field
        WEBVIEW__VISIBILITY (int): final static field
        WEBVIEW__HEIGHT (int): final static field
        WEBVIEW__URL (int): final static field
        WEBVIEW_FEATURE_COUNT (int): final static field
        SWITCH (int): final static field
        SWITCH__ITEM (int): final static field
        SWITCH__LABEL (int): final static field
        SWITCH__ICON (int): final static field
        SWITCH__LABEL_COLOR (int): final static field
        SWITCH__VALUE_COLOR (int): final static field
        SWITCH__VISIBILITY (int): final static field
        SWITCH__MAPPINGS (int): final static field
        SWITCH_FEATURE_COUNT (int): final static field
        MAPVIEW (int): final static field
        MAPVIEW__ITEM (int): final static field
        MAPVIEW__LABEL (int): final static field
        MAPVIEW__ICON (int): final static field
        MAPVIEW__LABEL_COLOR (int): final static field
        MAPVIEW__VALUE_COLOR (int): final static field
        MAPVIEW__VISIBILITY (int): final static field
        MAPVIEW__HEIGHT (int): final static field
        MAPVIEW_FEATURE_COUNT (int): final static field
        SLIDER (int): final static field
        SLIDER__ITEM (int): final static field
        SLIDER__LABEL (int): final static field
        SLIDER__ICON (int): final static field
        SLIDER__LABEL_COLOR (int): final static field
        SLIDER__VALUE_COLOR (int): final static field
        SLIDER__VISIBILITY (int): final static field
        SLIDER__FREQUENCY (int): final static field
        SLIDER__SWITCH_ENABLED (int): final static field
        SLIDER__MIN_VALUE (int): final static field
        SLIDER__MAX_VALUE (int): final static field
        SLIDER__STEP (int): final static field
        SLIDER_FEATURE_COUNT (int): final static field
        SELECTION (int): final static field
        SELECTION__ITEM (int): final static field
        SELECTION__LABEL (int): final static field
        SELECTION__ICON (int): final static field
        SELECTION__LABEL_COLOR (int): final static field
        SELECTION__VALUE_COLOR (int): final static field
        SELECTION__VISIBILITY (int): final static field
        SELECTION__MAPPINGS (int): final static field
        SELECTION_FEATURE_COUNT (int): final static field
        LIST (int): final static field
        LIST__ITEM (int): final static field
        LIST__LABEL (int): final static field
        LIST__ICON (int): final static field
        LIST__LABEL_COLOR (int): final static field
        LIST__VALUE_COLOR (int): final static field
        LIST__VISIBILITY (int): final static field
        LIST__SEPARATOR (int): final static field
        LIST_FEATURE_COUNT (int): final static field
        SETPOINT (int): final static field
        SETPOINT__ITEM (int): final static field
        SETPOINT__LABEL (int): final static field
        SETPOINT__ICON (int): final static field
        SETPOINT__LABEL_COLOR (int): final static field
        SETPOINT__VALUE_COLOR (int): final static field
        SETPOINT__VISIBILITY (int): final static field
        SETPOINT__MIN_VALUE (int): final static field
        SETPOINT__MAX_VALUE (int): final static field
        SETPOINT__STEP (int): final static field
        SETPOINT_FEATURE_COUNT (int): final static field
        COLORPICKER (int): final static field
        COLORPICKER__ITEM (int): final static field
        COLORPICKER__LABEL (int): final static field
        COLORPICKER__ICON (int): final static field
        COLORPICKER__LABEL_COLOR (int): final static field
        COLORPICKER__VALUE_COLOR (int): final static field
        COLORPICKER__VISIBILITY (int): final static field
        COLORPICKER__FREQUENCY (int): final static field
        COLORPICKER_FEATURE_COUNT (int): final static field
        DEFAULT (int): final static field
        DEFAULT__ITEM (int): final static field
        DEFAULT__LABEL (int): final static field
        DEFAULT__ICON (int): final static field
        DEFAULT__LABEL_COLOR (int): final static field
        DEFAULT__VALUE_COLOR (int): final static field
        DEFAULT__VISIBILITY (int): final static field
        DEFAULT__HEIGHT (int): final static field
        DEFAULT_FEATURE_COUNT (int): final static field
        MAPPING (int): final static field
        MAPPING__CMD (int): final static field
        MAPPING__LABEL (int): final static field
        MAPPING_FEATURE_COUNT (int): final static field
        VISIBILITY_RULE (int): final static field
        VISIBILITY_RULE__ITEM (int): final static field
        VISIBILITY_RULE__CONDITION (int): final static field
        VISIBILITY_RULE__SIGN (int): final static field
        VISIBILITY_RULE__STATE (int): final static field
        VISIBILITY_RULE_FEATURE_COUNT (int): final static field
        COLOR_ARRAY (int): final static field
        COLOR_ARRAY__ITEM (int): final static field
        COLOR_ARRAY__CONDITION (int): final static field
        COLOR_ARRAY__SIGN (int): final static field
        COLOR_ARRAY__STATE (int): final static field
        COLOR_ARRAY__ARG (int): final static field
        COLOR_ARRAY_FEATURE_COUNT (int): final static field
    
    """
    eNAME: typing.ClassVar[java.lang.String] = ...
    eNS_URI: typing.ClassVar[java.lang.String] = ...
    eNS_PREFIX: typing.ClassVar[java.lang.String] = ...
    eINSTANCE: typing.ClassVar['SitemapPackage'] = ...
    SITEMAP_MODEL: typing.ClassVar[int] = ...
    SITEMAP_MODEL_FEATURE_COUNT: typing.ClassVar[int] = ...
    SITEMAP: typing.ClassVar[int] = ...
    SITEMAP__NAME: typing.ClassVar[int] = ...
    SITEMAP__LABEL: typing.ClassVar[int] = ...
    SITEMAP__ICON: typing.ClassVar[int] = ...
    SITEMAP__CHILDREN: typing.ClassVar[int] = ...
    SITEMAP_FEATURE_COUNT: typing.ClassVar[int] = ...
    WIDGET: typing.ClassVar[int] = ...
    WIDGET__ITEM: typing.ClassVar[int] = ...
    WIDGET__LABEL: typing.ClassVar[int] = ...
    WIDGET__ICON: typing.ClassVar[int] = ...
    WIDGET__LABEL_COLOR: typing.ClassVar[int] = ...
    WIDGET__VALUE_COLOR: typing.ClassVar[int] = ...
    WIDGET__VISIBILITY: typing.ClassVar[int] = ...
    WIDGET_FEATURE_COUNT: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET__ITEM: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET__LABEL: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET__ICON: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET__LABEL_COLOR: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET__VALUE_COLOR: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET__VISIBILITY: typing.ClassVar[int] = ...
    NON_LINKABLE_WIDGET_FEATURE_COUNT: typing.ClassVar[int] = ...
    LINKABLE_WIDGET: typing.ClassVar[int] = ...
    LINKABLE_WIDGET__ITEM: typing.ClassVar[int] = ...
    LINKABLE_WIDGET__LABEL: typing.ClassVar[int] = ...
    LINKABLE_WIDGET__ICON: typing.ClassVar[int] = ...
    LINKABLE_WIDGET__LABEL_COLOR: typing.ClassVar[int] = ...
    LINKABLE_WIDGET__VALUE_COLOR: typing.ClassVar[int] = ...
    LINKABLE_WIDGET__VISIBILITY: typing.ClassVar[int] = ...
    LINKABLE_WIDGET__CHILDREN: typing.ClassVar[int] = ...
    LINKABLE_WIDGET_FEATURE_COUNT: typing.ClassVar[int] = ...
    FRAME: typing.ClassVar[int] = ...
    FRAME__ITEM: typing.ClassVar[int] = ...
    FRAME__LABEL: typing.ClassVar[int] = ...
    FRAME__ICON: typing.ClassVar[int] = ...
    FRAME__LABEL_COLOR: typing.ClassVar[int] = ...
    FRAME__VALUE_COLOR: typing.ClassVar[int] = ...
    FRAME__VISIBILITY: typing.ClassVar[int] = ...
    FRAME__CHILDREN: typing.ClassVar[int] = ...
    FRAME_FEATURE_COUNT: typing.ClassVar[int] = ...
    TEXT: typing.ClassVar[int] = ...
    TEXT__ITEM: typing.ClassVar[int] = ...
    TEXT__LABEL: typing.ClassVar[int] = ...
    TEXT__ICON: typing.ClassVar[int] = ...
    TEXT__LABEL_COLOR: typing.ClassVar[int] = ...
    TEXT__VALUE_COLOR: typing.ClassVar[int] = ...
    TEXT__VISIBILITY: typing.ClassVar[int] = ...
    TEXT__CHILDREN: typing.ClassVar[int] = ...
    TEXT_FEATURE_COUNT: typing.ClassVar[int] = ...
    GROUP: typing.ClassVar[int] = ...
    GROUP__ITEM: typing.ClassVar[int] = ...
    GROUP__LABEL: typing.ClassVar[int] = ...
    GROUP__ICON: typing.ClassVar[int] = ...
    GROUP__LABEL_COLOR: typing.ClassVar[int] = ...
    GROUP__VALUE_COLOR: typing.ClassVar[int] = ...
    GROUP__VISIBILITY: typing.ClassVar[int] = ...
    GROUP__CHILDREN: typing.ClassVar[int] = ...
    GROUP_FEATURE_COUNT: typing.ClassVar[int] = ...
    IMAGE: typing.ClassVar[int] = ...
    IMAGE__ITEM: typing.ClassVar[int] = ...
    IMAGE__LABEL: typing.ClassVar[int] = ...
    IMAGE__ICON: typing.ClassVar[int] = ...
    IMAGE__LABEL_COLOR: typing.ClassVar[int] = ...
    IMAGE__VALUE_COLOR: typing.ClassVar[int] = ...
    IMAGE__VISIBILITY: typing.ClassVar[int] = ...
    IMAGE__CHILDREN: typing.ClassVar[int] = ...
    IMAGE__URL: typing.ClassVar[int] = ...
    IMAGE__REFRESH: typing.ClassVar[int] = ...
    IMAGE__ICON_COLOR: typing.ClassVar[int] = ...
    IMAGE_FEATURE_COUNT: typing.ClassVar[int] = ...
    VIDEO: typing.ClassVar[int] = ...
    VIDEO__ITEM: typing.ClassVar[int] = ...
    VIDEO__LABEL: typing.ClassVar[int] = ...
    VIDEO__ICON: typing.ClassVar[int] = ...
    VIDEO__LABEL_COLOR: typing.ClassVar[int] = ...
    VIDEO__VALUE_COLOR: typing.ClassVar[int] = ...
    VIDEO__VISIBILITY: typing.ClassVar[int] = ...
    VIDEO__URL: typing.ClassVar[int] = ...
    VIDEO__ENCODING: typing.ClassVar[int] = ...
    VIDEO_FEATURE_COUNT: typing.ClassVar[int] = ...
    CHART: typing.ClassVar[int] = ...
    CHART__ITEM: typing.ClassVar[int] = ...
    CHART__LABEL: typing.ClassVar[int] = ...
    CHART__ICON: typing.ClassVar[int] = ...
    CHART__LABEL_COLOR: typing.ClassVar[int] = ...
    CHART__VALUE_COLOR: typing.ClassVar[int] = ...
    CHART__VISIBILITY: typing.ClassVar[int] = ...
    CHART__SERVICE: typing.ClassVar[int] = ...
    CHART__REFRESH: typing.ClassVar[int] = ...
    CHART__PERIOD: typing.ClassVar[int] = ...
    CHART__LEGEND: typing.ClassVar[int] = ...
    CHART_FEATURE_COUNT: typing.ClassVar[int] = ...
    WEBVIEW: typing.ClassVar[int] = ...
    WEBVIEW__ITEM: typing.ClassVar[int] = ...
    WEBVIEW__LABEL: typing.ClassVar[int] = ...
    WEBVIEW__ICON: typing.ClassVar[int] = ...
    WEBVIEW__LABEL_COLOR: typing.ClassVar[int] = ...
    WEBVIEW__VALUE_COLOR: typing.ClassVar[int] = ...
    WEBVIEW__VISIBILITY: typing.ClassVar[int] = ...
    WEBVIEW__HEIGHT: typing.ClassVar[int] = ...
    WEBVIEW__URL: typing.ClassVar[int] = ...
    WEBVIEW_FEATURE_COUNT: typing.ClassVar[int] = ...
    SWITCH: typing.ClassVar[int] = ...
    SWITCH__ITEM: typing.ClassVar[int] = ...
    SWITCH__LABEL: typing.ClassVar[int] = ...
    SWITCH__ICON: typing.ClassVar[int] = ...
    SWITCH__LABEL_COLOR: typing.ClassVar[int] = ...
    SWITCH__VALUE_COLOR: typing.ClassVar[int] = ...
    SWITCH__VISIBILITY: typing.ClassVar[int] = ...
    SWITCH__MAPPINGS: typing.ClassVar[int] = ...
    SWITCH_FEATURE_COUNT: typing.ClassVar[int] = ...
    MAPVIEW: typing.ClassVar[int] = ...
    MAPVIEW__ITEM: typing.ClassVar[int] = ...
    MAPVIEW__LABEL: typing.ClassVar[int] = ...
    MAPVIEW__ICON: typing.ClassVar[int] = ...
    MAPVIEW__LABEL_COLOR: typing.ClassVar[int] = ...
    MAPVIEW__VALUE_COLOR: typing.ClassVar[int] = ...
    MAPVIEW__VISIBILITY: typing.ClassVar[int] = ...
    MAPVIEW__HEIGHT: typing.ClassVar[int] = ...
    MAPVIEW_FEATURE_COUNT: typing.ClassVar[int] = ...
    SLIDER: typing.ClassVar[int] = ...
    SLIDER__ITEM: typing.ClassVar[int] = ...
    SLIDER__LABEL: typing.ClassVar[int] = ...
    SLIDER__ICON: typing.ClassVar[int] = ...
    SLIDER__LABEL_COLOR: typing.ClassVar[int] = ...
    SLIDER__VALUE_COLOR: typing.ClassVar[int] = ...
    SLIDER__VISIBILITY: typing.ClassVar[int] = ...
    SLIDER__FREQUENCY: typing.ClassVar[int] = ...
    SLIDER__SWITCH_ENABLED: typing.ClassVar[int] = ...
    SLIDER__MIN_VALUE: typing.ClassVar[int] = ...
    SLIDER__MAX_VALUE: typing.ClassVar[int] = ...
    SLIDER__STEP: typing.ClassVar[int] = ...
    SLIDER_FEATURE_COUNT: typing.ClassVar[int] = ...
    SELECTION: typing.ClassVar[int] = ...
    SELECTION__ITEM: typing.ClassVar[int] = ...
    SELECTION__LABEL: typing.ClassVar[int] = ...
    SELECTION__ICON: typing.ClassVar[int] = ...
    SELECTION__LABEL_COLOR: typing.ClassVar[int] = ...
    SELECTION__VALUE_COLOR: typing.ClassVar[int] = ...
    SELECTION__VISIBILITY: typing.ClassVar[int] = ...
    SELECTION__MAPPINGS: typing.ClassVar[int] = ...
    SELECTION_FEATURE_COUNT: typing.ClassVar[int] = ...
    LIST: typing.ClassVar[int] = ...
    LIST__ITEM: typing.ClassVar[int] = ...
    LIST__LABEL: typing.ClassVar[int] = ...
    LIST__ICON: typing.ClassVar[int] = ...
    LIST__LABEL_COLOR: typing.ClassVar[int] = ...
    LIST__VALUE_COLOR: typing.ClassVar[int] = ...
    LIST__VISIBILITY: typing.ClassVar[int] = ...
    LIST__SEPARATOR: typing.ClassVar[int] = ...
    LIST_FEATURE_COUNT: typing.ClassVar[int] = ...
    SETPOINT: typing.ClassVar[int] = ...
    SETPOINT__ITEM: typing.ClassVar[int] = ...
    SETPOINT__LABEL: typing.ClassVar[int] = ...
    SETPOINT__ICON: typing.ClassVar[int] = ...
    SETPOINT__LABEL_COLOR: typing.ClassVar[int] = ...
    SETPOINT__VALUE_COLOR: typing.ClassVar[int] = ...
    SETPOINT__VISIBILITY: typing.ClassVar[int] = ...
    SETPOINT__MIN_VALUE: typing.ClassVar[int] = ...
    SETPOINT__MAX_VALUE: typing.ClassVar[int] = ...
    SETPOINT__STEP: typing.ClassVar[int] = ...
    SETPOINT_FEATURE_COUNT: typing.ClassVar[int] = ...
    COLORPICKER: typing.ClassVar[int] = ...
    COLORPICKER__ITEM: typing.ClassVar[int] = ...
    COLORPICKER__LABEL: typing.ClassVar[int] = ...
    COLORPICKER__ICON: typing.ClassVar[int] = ...
    COLORPICKER__LABEL_COLOR: typing.ClassVar[int] = ...
    COLORPICKER__VALUE_COLOR: typing.ClassVar[int] = ...
    COLORPICKER__VISIBILITY: typing.ClassVar[int] = ...
    COLORPICKER__FREQUENCY: typing.ClassVar[int] = ...
    COLORPICKER_FEATURE_COUNT: typing.ClassVar[int] = ...
    DEFAULT: typing.ClassVar[int] = ...
    DEFAULT__ITEM: typing.ClassVar[int] = ...
    DEFAULT__LABEL: typing.ClassVar[int] = ...
    DEFAULT__ICON: typing.ClassVar[int] = ...
    DEFAULT__LABEL_COLOR: typing.ClassVar[int] = ...
    DEFAULT__VALUE_COLOR: typing.ClassVar[int] = ...
    DEFAULT__VISIBILITY: typing.ClassVar[int] = ...
    DEFAULT__HEIGHT: typing.ClassVar[int] = ...
    DEFAULT_FEATURE_COUNT: typing.ClassVar[int] = ...
    MAPPING: typing.ClassVar[int] = ...
    MAPPING__CMD: typing.ClassVar[int] = ...
    MAPPING__LABEL: typing.ClassVar[int] = ...
    MAPPING_FEATURE_COUNT: typing.ClassVar[int] = ...
    VISIBILITY_RULE: typing.ClassVar[int] = ...
    VISIBILITY_RULE__ITEM: typing.ClassVar[int] = ...
    VISIBILITY_RULE__CONDITION: typing.ClassVar[int] = ...
    VISIBILITY_RULE__SIGN: typing.ClassVar[int] = ...
    VISIBILITY_RULE__STATE: typing.ClassVar[int] = ...
    VISIBILITY_RULE_FEATURE_COUNT: typing.ClassVar[int] = ...
    COLOR_ARRAY: typing.ClassVar[int] = ...
    COLOR_ARRAY__ITEM: typing.ClassVar[int] = ...
    COLOR_ARRAY__CONDITION: typing.ClassVar[int] = ...
    COLOR_ARRAY__SIGN: typing.ClassVar[int] = ...
    COLOR_ARRAY__STATE: typing.ClassVar[int] = ...
    COLOR_ARRAY__ARG: typing.ClassVar[int] = ...
    COLOR_ARRAY_FEATURE_COUNT: typing.ClassVar[int] = ...
    def getChart(self) -> org.eclipse.emf.ecore.EClass: ...
    def getChart_Legend(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getChart_Period(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getChart_Refresh(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getChart_Service(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getColorArray(self) -> org.eclipse.emf.ecore.EClass: ...
    def getColorArray_Arg(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getColorArray_Condition(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getColorArray_Item(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getColorArray_Sign(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getColorArray_State(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getColorpicker(self) -> org.eclipse.emf.ecore.EClass: ...
    def getColorpicker_Frequency(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getDefault(self) -> org.eclipse.emf.ecore.EClass: ...
    def getDefault_Height(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getFrame(self) -> org.eclipse.emf.ecore.EClass: ...
    def getGroup(self) -> org.eclipse.emf.ecore.EClass: ...
    def getImage(self) -> org.eclipse.emf.ecore.EClass: ...
    def getImage_IconColor(self) -> org.eclipse.emf.ecore.EReference: ...
    def getImage_Refresh(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getImage_Url(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getLinkableWidget(self) -> org.eclipse.emf.ecore.EClass: ...
    def getLinkableWidget_Children(self) -> org.eclipse.emf.ecore.EReference: ...
    def getList(self) -> org.eclipse.emf.ecore.EClass: ...
    def getList_Separator(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getMapping(self) -> org.eclipse.emf.ecore.EClass: ...
    def getMapping_Cmd(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getMapping_Label(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getMapview(self) -> org.eclipse.emf.ecore.EClass: ...
    def getMapview_Height(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getNonLinkableWidget(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSelection(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSelection_Mappings(self) -> org.eclipse.emf.ecore.EReference: ...
    def getSetpoint(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSetpoint_MaxValue(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSetpoint_MinValue(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSetpoint_Step(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSitemap(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSitemapFactory(self) -> SitemapFactory: ...
    def getSitemapModel(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSitemap_Children(self) -> org.eclipse.emf.ecore.EReference: ...
    def getSitemap_Icon(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSitemap_Label(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSitemap_Name(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSlider(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSlider_Frequency(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSlider_MaxValue(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSlider_MinValue(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSlider_Step(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSlider_SwitchEnabled(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getSwitch(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSwitch_Mappings(self) -> org.eclipse.emf.ecore.EReference: ...
    def getText(self) -> org.eclipse.emf.ecore.EClass: ...
    def getVideo(self) -> org.eclipse.emf.ecore.EClass: ...
    def getVideo_Encoding(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getVideo_Url(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getVisibilityRule(self) -> org.eclipse.emf.ecore.EClass: ...
    def getVisibilityRule_Condition(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getVisibilityRule_Item(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getVisibilityRule_Sign(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getVisibilityRule_State(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getWebview(self) -> org.eclipse.emf.ecore.EClass: ...
    def getWebview_Height(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getWebview_Url(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getWidget(self) -> org.eclipse.emf.ecore.EClass: ...
    def getWidget_Icon(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getWidget_Item(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getWidget_Label(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getWidget_LabelColor(self) -> org.eclipse.emf.ecore.EReference: ...
    def getWidget_ValueColor(self) -> org.eclipse.emf.ecore.EReference: ...
    def getWidget_Visibility(self) -> org.eclipse.emf.ecore.EReference: ...
    class Literals(java.lang.Object):
        """
        Java class 'org.openhab.core.model.sitemap.sitemap.SitemapPackage$Literals'
        
          Attributes:
            SITEMAP_MODEL (org.eclipse.emf.ecore.EClass): final static field
            SITEMAP (org.eclipse.emf.ecore.EClass): final static field
            SITEMAP__NAME (org.eclipse.emf.ecore.EAttribute): final static field
            SITEMAP__LABEL (org.eclipse.emf.ecore.EAttribute): final static field
            SITEMAP__ICON (org.eclipse.emf.ecore.EAttribute): final static field
            SITEMAP__CHILDREN (org.eclipse.emf.ecore.EReference): final static field
            WIDGET (org.eclipse.emf.ecore.EClass): final static field
            WIDGET__ITEM (org.eclipse.emf.ecore.EAttribute): final static field
            WIDGET__LABEL (org.eclipse.emf.ecore.EAttribute): final static field
            WIDGET__ICON (org.eclipse.emf.ecore.EAttribute): final static field
            WIDGET__LABEL_COLOR (org.eclipse.emf.ecore.EReference): final static field
            WIDGET__VALUE_COLOR (org.eclipse.emf.ecore.EReference): final static field
            WIDGET__VISIBILITY (org.eclipse.emf.ecore.EReference): final static field
            NON_LINKABLE_WIDGET (org.eclipse.emf.ecore.EClass): final static field
            LINKABLE_WIDGET (org.eclipse.emf.ecore.EClass): final static field
            LINKABLE_WIDGET__CHILDREN (org.eclipse.emf.ecore.EReference): final static field
            FRAME (org.eclipse.emf.ecore.EClass): final static field
            TEXT (org.eclipse.emf.ecore.EClass): final static field
            GROUP (org.eclipse.emf.ecore.EClass): final static field
            IMAGE (org.eclipse.emf.ecore.EClass): final static field
            IMAGE__URL (org.eclipse.emf.ecore.EAttribute): final static field
            IMAGE__REFRESH (org.eclipse.emf.ecore.EAttribute): final static field
            IMAGE__ICON_COLOR (org.eclipse.emf.ecore.EReference): final static field
            VIDEO (org.eclipse.emf.ecore.EClass): final static field
            VIDEO__URL (org.eclipse.emf.ecore.EAttribute): final static field
            VIDEO__ENCODING (org.eclipse.emf.ecore.EAttribute): final static field
            CHART (org.eclipse.emf.ecore.EClass): final static field
            CHART__SERVICE (org.eclipse.emf.ecore.EAttribute): final static field
            CHART__REFRESH (org.eclipse.emf.ecore.EAttribute): final static field
            CHART__PERIOD (org.eclipse.emf.ecore.EAttribute): final static field
            CHART__LEGEND (org.eclipse.emf.ecore.EAttribute): final static field
            WEBVIEW (org.eclipse.emf.ecore.EClass): final static field
            WEBVIEW__HEIGHT (org.eclipse.emf.ecore.EAttribute): final static field
            WEBVIEW__URL (org.eclipse.emf.ecore.EAttribute): final static field
            SWITCH (org.eclipse.emf.ecore.EClass): final static field
            SWITCH__MAPPINGS (org.eclipse.emf.ecore.EReference): final static field
            MAPVIEW (org.eclipse.emf.ecore.EClass): final static field
            MAPVIEW__HEIGHT (org.eclipse.emf.ecore.EAttribute): final static field
            SLIDER (org.eclipse.emf.ecore.EClass): final static field
            SLIDER__FREQUENCY (org.eclipse.emf.ecore.EAttribute): final static field
            SLIDER__SWITCH_ENABLED (org.eclipse.emf.ecore.EAttribute): final static field
            SLIDER__MIN_VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            SLIDER__MAX_VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            SLIDER__STEP (org.eclipse.emf.ecore.EAttribute): final static field
            SELECTION (org.eclipse.emf.ecore.EClass): final static field
            SELECTION__MAPPINGS (org.eclipse.emf.ecore.EReference): final static field
            LIST (org.eclipse.emf.ecore.EClass): final static field
            LIST__SEPARATOR (org.eclipse.emf.ecore.EAttribute): final static field
            SETPOINT (org.eclipse.emf.ecore.EClass): final static field
            SETPOINT__MIN_VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            SETPOINT__MAX_VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            SETPOINT__STEP (org.eclipse.emf.ecore.EAttribute): final static field
            COLORPICKER (org.eclipse.emf.ecore.EClass): final static field
            COLORPICKER__FREQUENCY (org.eclipse.emf.ecore.EAttribute): final static field
            DEFAULT (org.eclipse.emf.ecore.EClass): final static field
            DEFAULT__HEIGHT (org.eclipse.emf.ecore.EAttribute): final static field
            MAPPING (org.eclipse.emf.ecore.EClass): final static field
            MAPPING__CMD (org.eclipse.emf.ecore.EAttribute): final static field
            MAPPING__LABEL (org.eclipse.emf.ecore.EAttribute): final static field
            VISIBILITY_RULE (org.eclipse.emf.ecore.EClass): final static field
            VISIBILITY_RULE__ITEM (org.eclipse.emf.ecore.EAttribute): final static field
            VISIBILITY_RULE__CONDITION (org.eclipse.emf.ecore.EAttribute): final static field
            VISIBILITY_RULE__SIGN (org.eclipse.emf.ecore.EAttribute): final static field
            VISIBILITY_RULE__STATE (org.eclipse.emf.ecore.EAttribute): final static field
            COLOR_ARRAY (org.eclipse.emf.ecore.EClass): final static field
            COLOR_ARRAY__ITEM (org.eclipse.emf.ecore.EAttribute): final static field
            COLOR_ARRAY__CONDITION (org.eclipse.emf.ecore.EAttribute): final static field
            COLOR_ARRAY__SIGN (org.eclipse.emf.ecore.EAttribute): final static field
            COLOR_ARRAY__STATE (org.eclipse.emf.ecore.EAttribute): final static field
            COLOR_ARRAY__ARG (org.eclipse.emf.ecore.EAttribute): final static field
        
        """
        SITEMAP_MODEL: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SITEMAP: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SITEMAP__NAME: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SITEMAP__LABEL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SITEMAP__ICON: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SITEMAP__CHILDREN: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        WIDGET: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        WIDGET__ITEM: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        WIDGET__LABEL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        WIDGET__ICON: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        WIDGET__LABEL_COLOR: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        WIDGET__VALUE_COLOR: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        WIDGET__VISIBILITY: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        NON_LINKABLE_WIDGET: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        LINKABLE_WIDGET: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        LINKABLE_WIDGET__CHILDREN: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        FRAME: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        TEXT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        GROUP: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        IMAGE: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        IMAGE__URL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        IMAGE__REFRESH: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        IMAGE__ICON_COLOR: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        VIDEO: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VIDEO__URL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VIDEO__ENCODING: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        CHART: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        CHART__SERVICE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        CHART__REFRESH: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        CHART__PERIOD: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        CHART__LEGEND: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        WEBVIEW: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        WEBVIEW__HEIGHT: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        WEBVIEW__URL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SWITCH: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SWITCH__MAPPINGS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        MAPVIEW: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MAPVIEW__HEIGHT: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SLIDER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SLIDER__FREQUENCY: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SLIDER__SWITCH_ENABLED: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SLIDER__MIN_VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SLIDER__MAX_VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SLIDER__STEP: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SELECTION: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SELECTION__MAPPINGS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        LIST: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        LIST__SEPARATOR: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SETPOINT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SETPOINT__MIN_VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SETPOINT__MAX_VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SETPOINT__STEP: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        COLORPICKER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        COLORPICKER__FREQUENCY: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        DEFAULT: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        DEFAULT__HEIGHT: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MAPPING: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MAPPING__CMD: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MAPPING__LABEL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VISIBILITY_RULE: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VISIBILITY_RULE__ITEM: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VISIBILITY_RULE__CONDITION: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VISIBILITY_RULE__SIGN: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VISIBILITY_RULE__STATE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        COLOR_ARRAY: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        COLOR_ARRAY__ITEM: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        COLOR_ARRAY__CONDITION: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        COLOR_ARRAY__SIGN: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        COLOR_ARRAY__STATE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        COLOR_ARRAY__ARG: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...

class VisibilityRule(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.VisibilityRule'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getCondition(self) -> java.lang.String: ...
    def getItem(self) -> java.lang.String: ...
    def getSign(self) -> java.lang.String: ...
    def getState(self) -> java.lang.String: ...
    def setCondition(self, value: java.lang.String) -> None: ...
    def setItem(self, value: java.lang.String) -> None: ...
    def setSign(self, value: java.lang.String) -> None: ...
    def setState(self, value: java.lang.String) -> None: ...

class Widget(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Widget'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getIcon(self) -> java.lang.String: ...
    def getItem(self) -> java.lang.String: ...
    def getLabel(self) -> java.lang.String: ...
    def getLabelColor(self) -> org.eclipse.emf.common.util.EList[ColorArray]: ...
    def getValueColor(self) -> org.eclipse.emf.common.util.EList[ColorArray]: ...
    def getVisibility(self) -> org.eclipse.emf.common.util.EList[VisibilityRule]: ...
    def setIcon(self, value: java.lang.String) -> None: ...
    def setItem(self, value: java.lang.String) -> None: ...
    def setLabel(self, value: java.lang.String) -> None: ...

class LinkableWidget(Widget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.LinkableWidget'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.Widget
    
    """
    def getChildren(self) -> org.eclipse.emf.common.util.EList[Widget]: ...

class NonLinkableWidget(Widget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.NonLinkableWidget'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.Widget
    
    """

class Sitemap(SitemapModel):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Sitemap'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.SitemapModel
    
    """
    def getChildren(self) -> org.eclipse.emf.common.util.EList[Widget]: ...
    def getIcon(self) -> java.lang.String: ...
    def getLabel(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def setIcon(self, value: java.lang.String) -> None: ...
    def setLabel(self, value: java.lang.String) -> None: ...
    def setName(self, value: java.lang.String) -> None: ...

class Chart(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Chart'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getLegend(self) -> bool: ...
    def getPeriod(self) -> java.lang.String: ...
    def getRefresh(self) -> int: ...
    def getService(self) -> java.lang.String: ...
    def setLegend(self, value: bool) -> None: ...
    def setPeriod(self, value: java.lang.String) -> None: ...
    def setRefresh(self, value: int) -> None: ...
    def setService(self, value: java.lang.String) -> None: ...

class Colorpicker(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Colorpicker'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getFrequency(self) -> int: ...
    def setFrequency(self, value: int) -> None: ...

class Default(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Default'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getHeight(self) -> int: ...
    def setHeight(self, value: int) -> None: ...

class Frame(LinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Frame'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.LinkableWidget
    
    """

class Group(LinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Group'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.LinkableWidget
    
    """

class Image(LinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Image'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.LinkableWidget
    
    """
    def getIconColor(self) -> org.eclipse.emf.common.util.EList[ColorArray]: ...
    def getRefresh(self) -> int: ...
    def getUrl(self) -> java.lang.String: ...
    def setRefresh(self, value: int) -> None: ...
    def setUrl(self, value: java.lang.String) -> None: ...

class List(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.List'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getSeparator(self) -> java.lang.String: ...
    def setSeparator(self, value: java.lang.String) -> None: ...

class Mapview(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Mapview'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getHeight(self) -> int: ...
    def setHeight(self, value: int) -> None: ...

class Selection(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Selection'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getMappings(self) -> org.eclipse.emf.common.util.EList[Mapping]: ...

class Setpoint(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Setpoint'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getMaxValue(self) -> java.math.BigDecimal: ...
    def getMinValue(self) -> java.math.BigDecimal: ...
    def getStep(self) -> java.math.BigDecimal: ...
    def setMaxValue(self, value: java.math.BigDecimal) -> None: ...
    def setMinValue(self, value: java.math.BigDecimal) -> None: ...
    def setStep(self, value: java.math.BigDecimal) -> None: ...

class Slider(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Slider'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getFrequency(self) -> int: ...
    def getMaxValue(self) -> java.math.BigDecimal: ...
    def getMinValue(self) -> java.math.BigDecimal: ...
    def getStep(self) -> java.math.BigDecimal: ...
    def isSwitchEnabled(self) -> bool: ...
    def setFrequency(self, value: int) -> None: ...
    def setMaxValue(self, value: java.math.BigDecimal) -> None: ...
    def setMinValue(self, value: java.math.BigDecimal) -> None: ...
    def setStep(self, value: java.math.BigDecimal) -> None: ...
    def setSwitchEnabled(self, value: bool) -> None: ...

class Switch(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Switch'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getMappings(self) -> org.eclipse.emf.common.util.EList[Mapping]: ...

class Text(LinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Text'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.LinkableWidget
    
    """

class Video(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Video'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getEncoding(self) -> java.lang.String: ...
    def getUrl(self) -> java.lang.String: ...
    def setEncoding(self, value: java.lang.String) -> None: ...
    def setUrl(self, value: java.lang.String) -> None: ...

class Webview(NonLinkableWidget):
    """
    Java class 'org.openhab.core.model.sitemap.sitemap.Webview'
    
        Interfaces:
            org.openhab.core.model.sitemap.sitemap.NonLinkableWidget
    
    """
    def getHeight(self) -> int: ...
    def getUrl(self) -> java.lang.String: ...
    def setHeight(self, value: int) -> None: ...
    def setUrl(self, value: java.lang.String) -> None: ...
