import java
import java.io
import java.lang
import java.nio
import java.util
import typing


class CharacterCodingException(java.io.IOException):
    """
    Java class 'java.nio.charset.CharacterCodingException'
    
        Extends:
            java.io.IOException
    
      Constructors:
        * CharacterCodingException()
    
    """
    def __init__(self): ...

class Charset(java.lang.Comparable[java.nio.charset.Charset]):
    """
    Java class 'java.nio.charset.Charset'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            java.lang.Comparable
    
    """
    def aliases(self) -> java.util.Set[java.lang.String]: ...
    @classmethod
    def availableCharsets(cls) -> java.util.SortedMap[java.lang.String, 'Charset']: ...
    def canEncode(self) -> bool: ...
    @typing.overload
    def compareTo(self, charset: 'Charset') -> int: ...
    @typing.overload
    def compareTo(self, object: typing.Any) -> int: ...
    def contains(self, charset: 'Charset') -> bool: ...
    def decode(self, byteBuffer: java.nio.ByteBuffer) -> java.nio.CharBuffer: ...
    @classmethod
    def defaultCharset(cls) -> 'Charset': ...
    @typing.overload
    def displayName(self) -> java.lang.String: ...
    @typing.overload
    def displayName(self, locale: java.util.Locale) -> java.lang.String: ...
    @typing.overload
    def encode(self, string: java.lang.String) -> java.nio.ByteBuffer: ...
    @typing.overload
    def encode(self, charBuffer: java.nio.CharBuffer) -> java.nio.ByteBuffer: ...
    def equals(self, object: typing.Any) -> bool: ...
    @classmethod
    def forName(cls, string: java.lang.String) -> 'Charset': ...
    def hashCode(self) -> int: ...
    def isRegistered(self) -> bool: ...
    @classmethod
    def isSupported(cls, string: java.lang.String) -> bool: ...
    def name(self) -> java.lang.String: ...
    def newDecoder(self) -> 'CharsetDecoder': ...
    def newEncoder(self) -> 'CharsetEncoder': ...
    def toString(self) -> java.lang.String: ...

class CharsetDecoder(java.lang.Object):
    """
    Java class 'java.nio.charset.CharsetDecoder'
    
        Extends:
            java.lang.Object
    
    """
    def averageCharsPerByte(self) -> float: ...
    def charset(self) -> Charset: ...
    @typing.overload
    def decode(self, byteBuffer: java.nio.ByteBuffer) -> java.nio.CharBuffer: ...
    @typing.overload
    def decode(self, byteBuffer: java.nio.ByteBuffer, charBuffer: java.nio.CharBuffer, boolean: bool) -> 'CoderResult': ...
    def detectedCharset(self) -> Charset: ...
    def flush(self, charBuffer: java.nio.CharBuffer) -> 'CoderResult': ...
    def isAutoDetecting(self) -> bool: ...
    def isCharsetDetected(self) -> bool: ...
    def malformedInputAction(self) -> 'CodingErrorAction': ...
    def maxCharsPerByte(self) -> float: ...
    def onMalformedInput(self, codingErrorAction: 'CodingErrorAction') -> 'CharsetDecoder': ...
    def onUnmappableCharacter(self, codingErrorAction: 'CodingErrorAction') -> 'CharsetDecoder': ...
    def replaceWith(self, string: java.lang.String) -> 'CharsetDecoder': ...
    def replacement(self) -> java.lang.String: ...
    def reset(self) -> 'CharsetDecoder': ...
    def unmappableCharacterAction(self) -> 'CodingErrorAction': ...

class CharsetEncoder(java.lang.Object):
    """
    Java class 'java.nio.charset.CharsetEncoder'
    
        Extends:
            java.lang.Object
    
    """
    def averageBytesPerChar(self) -> float: ...
    @typing.overload
    def canEncode(self, char: str) -> bool: ...
    @typing.overload
    def canEncode(self, charSequence: java.lang.CharSequence) -> bool: ...
    def charset(self) -> Charset: ...
    @typing.overload
    def encode(self, charBuffer: java.nio.CharBuffer) -> java.nio.ByteBuffer: ...
    @typing.overload
    def encode(self, charBuffer: java.nio.CharBuffer, byteBuffer: java.nio.ByteBuffer, boolean: bool) -> 'CoderResult': ...
    def flush(self, byteBuffer: java.nio.ByteBuffer) -> 'CoderResult': ...
    def isLegalReplacement(self, byteArray: typing.List[int]) -> bool: ...
    def malformedInputAction(self) -> 'CodingErrorAction': ...
    def maxBytesPerChar(self) -> float: ...
    def onMalformedInput(self, codingErrorAction: 'CodingErrorAction') -> 'CharsetEncoder': ...
    def onUnmappableCharacter(self, codingErrorAction: 'CodingErrorAction') -> 'CharsetEncoder': ...
    def replaceWith(self, byteArray: typing.List[int]) -> 'CharsetEncoder': ...
    def replacement(self) -> typing.List[int]: ...
    def reset(self) -> 'CharsetEncoder': ...
    def unmappableCharacterAction(self) -> 'CodingErrorAction': ...

class CoderMalfunctionError(java.lang.Error):
    """
    Java class 'java.nio.charset.CoderMalfunctionError'
    
        Extends:
            java.lang.Error
    
      Constructors:
        * CoderMalfunctionError(java.lang.Exception)
    
    """
    def __init__(self, exception: java.lang.Exception): ...

class CoderResult(java.lang.Object):
    """
    Java class 'java.nio.charset.CoderResult'
    
        Extends:
            java.lang.Object
    
      Attributes:
        UNDERFLOW (java.nio.charset.CoderResult): final static field
        OVERFLOW (java.nio.charset.CoderResult): final static field
    
    """
    UNDERFLOW: typing.ClassVar['CoderResult'] = ...
    OVERFLOW: typing.ClassVar['CoderResult'] = ...
    def isError(self) -> bool: ...
    def isMalformed(self) -> bool: ...
    def isOverflow(self) -> bool: ...
    def isUnderflow(self) -> bool: ...
    def isUnmappable(self) -> bool: ...
    def length(self) -> int: ...
    @classmethod
    def malformedForLength(cls, int: int) -> 'CoderResult': ...
    def throwException(self) -> None: ...
    def toString(self) -> java.lang.String: ...
    @classmethod
    def unmappableForLength(cls, int: int) -> 'CoderResult': ...

class CodingErrorAction(java.lang.Object):
    """
    Java class 'java.nio.charset.CodingErrorAction'
    
        Extends:
            java.lang.Object
    
      Attributes:
        IGNORE (java.nio.charset.CodingErrorAction): final static field
        REPLACE (java.nio.charset.CodingErrorAction): final static field
        REPORT (java.nio.charset.CodingErrorAction): final static field
    
    """
    IGNORE: typing.ClassVar['CodingErrorAction'] = ...
    REPLACE: typing.ClassVar['CodingErrorAction'] = ...
    REPORT: typing.ClassVar['CodingErrorAction'] = ...
    def toString(self) -> java.lang.String: ...

class IllegalCharsetNameException(java.lang.IllegalArgumentException):
    """
    Java class 'java.nio.charset.IllegalCharsetNameException'
    
        Extends:
            java.lang.IllegalArgumentException
    
      Constructors:
        * IllegalCharsetNameException(java.lang.String)
    
    """
    def __init__(self, string: java.lang.String): ...
    def getCharsetName(self) -> java.lang.String: ...

class StandardCharsets(java.lang.Object):
    """
    Java class 'java.nio.charset.StandardCharsets'
    
        Extends:
            java.lang.Object
    
      Attributes:
        US_ASCII (java.nio.charset.Charset): final static field
        ISO_8859_1 (java.nio.charset.Charset): final static field
        UTF_8 (java.nio.charset.Charset): final static field
        UTF_16BE (java.nio.charset.Charset): final static field
        UTF_16LE (java.nio.charset.Charset): final static field
        UTF_16 (java.nio.charset.Charset): final static field
    
    """
    US_ASCII: typing.ClassVar[Charset] = ...
    ISO_8859_1: typing.ClassVar[Charset] = ...
    UTF_8: typing.ClassVar[Charset] = ...
    UTF_16BE: typing.ClassVar[Charset] = ...
    UTF_16LE: typing.ClassVar[Charset] = ...
    UTF_16: typing.ClassVar[Charset] = ...

class UnsupportedCharsetException(java.lang.IllegalArgumentException):
    """
    Java class 'java.nio.charset.UnsupportedCharsetException'
    
        Extends:
            java.lang.IllegalArgumentException
    
      Constructors:
        * UnsupportedCharsetException(java.lang.String)
    
    """
    def __init__(self, string: java.lang.String): ...
    def getCharsetName(self) -> java.lang.String: ...

class MalformedInputException(CharacterCodingException):
    """
    Java class 'java.nio.charset.MalformedInputException'
    
        Extends:
            java.nio.charset.CharacterCodingException
    
      Constructors:
        * MalformedInputException(int)
    
    """
    def __init__(self, int: int): ...
    def getInputLength(self) -> int: ...
    def getMessage(self) -> java.lang.String: ...

class UnmappableCharacterException(CharacterCodingException):
    """
    Java class 'java.nio.charset.UnmappableCharacterException'
    
        Extends:
            java.nio.charset.CharacterCodingException
    
      Constructors:
        * UnmappableCharacterException(int)
    
    """
    def __init__(self, int: int): ...
    def getInputLength(self) -> int: ...
    def getMessage(self) -> java.lang.String: ...
