import java.lang
import org.eclipse.emf.common.util
import org.eclipse.emf.ecore
import org.eclipse.xtext.common.types
import org.eclipse.xtext.xbase
import org.eclipse.xtext.xtype
import typing


class EventTrigger(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.rule.rules.EventTrigger'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """

class Rule(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.rule.rules.Rule'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getEventtrigger(self) -> org.eclipse.emf.common.util.EList[EventTrigger]: ...
    def getName(self) -> java.lang.String: ...
    def getScript(self) -> org.eclipse.xtext.xbase.XBlockExpression: ...
    def setName(self, value: java.lang.String) -> None: ...
    def setScript(self, value: org.eclipse.xtext.xbase.XBlockExpression) -> None: ...

class RuleModel(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.rule.rules.RuleModel'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getImportSection(self) -> org.eclipse.xtext.xtype.XImportSection: ...
    def getRules(self) -> org.eclipse.emf.common.util.EList[Rule]: ...
    def getVariables(self) -> org.eclipse.emf.common.util.EList['VariableDeclaration']: ...
    def setImportSection(self, value: org.eclipse.xtext.xtype.XImportSection) -> None: ...

class RulesFactory(org.eclipse.emf.ecore.EFactory):
    """
    Java class 'org.openhab.core.model.rule.rules.RulesFactory'
    
        Interfaces:
            org.eclipse.emf.ecore.EFactory
    
      Attributes:
        eINSTANCE (org.openhab.core.model.rule.rules.RulesFactory): final static field
    
    """
    eINSTANCE: typing.ClassVar['RulesFactory'] = ...
    def createChangedEventTrigger(self) -> 'ChangedEventTrigger': ...
    def createCommandEventTrigger(self) -> 'CommandEventTrigger': ...
    def createEventEmittedTrigger(self) -> 'EventEmittedTrigger': ...
    def createEventTrigger(self) -> EventTrigger: ...
    def createGroupMemberChangedEventTrigger(self) -> 'GroupMemberChangedEventTrigger': ...
    def createGroupMemberCommandEventTrigger(self) -> 'GroupMemberCommandEventTrigger': ...
    def createGroupMemberUpdateEventTrigger(self) -> 'GroupMemberUpdateEventTrigger': ...
    def createRule(self) -> Rule: ...
    def createRuleModel(self) -> RuleModel: ...
    def createSystemOnShutdownTrigger(self) -> 'SystemOnShutdownTrigger': ...
    def createSystemOnStartupTrigger(self) -> 'SystemOnStartupTrigger': ...
    def createSystemTrigger(self) -> 'SystemTrigger': ...
    def createThingStateChangedEventTrigger(self) -> 'ThingStateChangedEventTrigger': ...
    def createThingStateUpdateEventTrigger(self) -> 'ThingStateUpdateEventTrigger': ...
    def createTimerTrigger(self) -> 'TimerTrigger': ...
    def createUpdateEventTrigger(self) -> 'UpdateEventTrigger': ...
    def createValidCommand(self) -> 'ValidCommand': ...
    def createValidCommandId(self) -> 'ValidCommandId': ...
    def createValidCommandNumber(self) -> 'ValidCommandNumber': ...
    def createValidCommandString(self) -> 'ValidCommandString': ...
    def createValidState(self) -> 'ValidState': ...
    def createValidStateId(self) -> 'ValidStateId': ...
    def createValidStateNumber(self) -> 'ValidStateNumber': ...
    def createValidStateString(self) -> 'ValidStateString': ...
    def createValidTrigger(self) -> 'ValidTrigger': ...
    def createValidTriggerId(self) -> 'ValidTriggerId': ...
    def createValidTriggerNumber(self) -> 'ValidTriggerNumber': ...
    def createValidTriggerString(self) -> 'ValidTriggerString': ...
    def createVariableDeclaration(self) -> 'VariableDeclaration': ...
    def getRulesPackage(self) -> 'RulesPackage': ...

class RulesPackage(org.eclipse.emf.ecore.EPackage):
    """
    Java class 'org.openhab.core.model.rule.rules.RulesPackage'
    
        Interfaces:
            org.eclipse.emf.ecore.EPackage
    
      Attributes:
        eNAME (java.lang.String): final static field
        eNS_URI (java.lang.String): final static field
        eNS_PREFIX (java.lang.String): final static field
        eINSTANCE (org.openhab.core.model.rule.rules.RulesPackage): final static field
        RULE_MODEL (int): final static field
        RULE_MODEL__IMPORT_SECTION (int): final static field
        RULE_MODEL__VARIABLES (int): final static field
        RULE_MODEL__RULES (int): final static field
        RULE_MODEL_FEATURE_COUNT (int): final static field
        VARIABLE_DECLARATION (int): final static field
        VARIABLE_DECLARATION__WRITEABLE (int): final static field
        VARIABLE_DECLARATION__TYPE (int): final static field
        VARIABLE_DECLARATION__NAME (int): final static field
        VARIABLE_DECLARATION__RIGHT (int): final static field
        VARIABLE_DECLARATION_FEATURE_COUNT (int): final static field
        RULE (int): final static field
        RULE__NAME (int): final static field
        RULE__EVENTTRIGGER (int): final static field
        RULE__SCRIPT (int): final static field
        RULE_FEATURE_COUNT (int): final static field
        EVENT_TRIGGER (int): final static field
        EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        COMMAND_EVENT_TRIGGER (int): final static field
        COMMAND_EVENT_TRIGGER__ITEM (int): final static field
        COMMAND_EVENT_TRIGGER__COMMAND (int): final static field
        COMMAND_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        GROUP_MEMBER_COMMAND_EVENT_TRIGGER (int): final static field
        GROUP_MEMBER_COMMAND_EVENT_TRIGGER__GROUP (int): final static field
        GROUP_MEMBER_COMMAND_EVENT_TRIGGER__COMMAND (int): final static field
        GROUP_MEMBER_COMMAND_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        UPDATE_EVENT_TRIGGER (int): final static field
        UPDATE_EVENT_TRIGGER__ITEM (int): final static field
        UPDATE_EVENT_TRIGGER__STATE (int): final static field
        UPDATE_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        GROUP_MEMBER_UPDATE_EVENT_TRIGGER (int): final static field
        GROUP_MEMBER_UPDATE_EVENT_TRIGGER__GROUP (int): final static field
        GROUP_MEMBER_UPDATE_EVENT_TRIGGER__STATE (int): final static field
        GROUP_MEMBER_UPDATE_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        CHANGED_EVENT_TRIGGER (int): final static field
        CHANGED_EVENT_TRIGGER__ITEM (int): final static field
        CHANGED_EVENT_TRIGGER__OLD_STATE (int): final static field
        CHANGED_EVENT_TRIGGER__NEW_STATE (int): final static field
        CHANGED_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER (int): final static field
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER__GROUP (int): final static field
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER__OLD_STATE (int): final static field
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER__NEW_STATE (int): final static field
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        EVENT_EMITTED_TRIGGER (int): final static field
        EVENT_EMITTED_TRIGGER__CHANNEL (int): final static field
        EVENT_EMITTED_TRIGGER__TRIGGER (int): final static field
        EVENT_EMITTED_TRIGGER_FEATURE_COUNT (int): final static field
        TIMER_TRIGGER (int): final static field
        TIMER_TRIGGER__CRON (int): final static field
        TIMER_TRIGGER__TIME (int): final static field
        TIMER_TRIGGER_FEATURE_COUNT (int): final static field
        SYSTEM_TRIGGER (int): final static field
        SYSTEM_TRIGGER_FEATURE_COUNT (int): final static field
        SYSTEM_ON_STARTUP_TRIGGER (int): final static field
        SYSTEM_ON_STARTUP_TRIGGER_FEATURE_COUNT (int): final static field
        SYSTEM_ON_SHUTDOWN_TRIGGER (int): final static field
        SYSTEM_ON_SHUTDOWN_TRIGGER_FEATURE_COUNT (int): final static field
        THING_STATE_UPDATE_EVENT_TRIGGER (int): final static field
        THING_STATE_UPDATE_EVENT_TRIGGER__THING (int): final static field
        THING_STATE_UPDATE_EVENT_TRIGGER__STATE (int): final static field
        THING_STATE_UPDATE_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        THING_STATE_CHANGED_EVENT_TRIGGER (int): final static field
        THING_STATE_CHANGED_EVENT_TRIGGER__THING (int): final static field
        THING_STATE_CHANGED_EVENT_TRIGGER__OLD_STATE (int): final static field
        THING_STATE_CHANGED_EVENT_TRIGGER__NEW_STATE (int): final static field
        THING_STATE_CHANGED_EVENT_TRIGGER_FEATURE_COUNT (int): final static field
        VALID_STATE (int): final static field
        VALID_STATE__VALUE (int): final static field
        VALID_STATE_FEATURE_COUNT (int): final static field
        VALID_STATE_ID (int): final static field
        VALID_STATE_ID__VALUE (int): final static field
        VALID_STATE_ID_FEATURE_COUNT (int): final static field
        VALID_STATE_NUMBER (int): final static field
        VALID_STATE_NUMBER__VALUE (int): final static field
        VALID_STATE_NUMBER_FEATURE_COUNT (int): final static field
        VALID_STATE_STRING (int): final static field
        VALID_STATE_STRING__VALUE (int): final static field
        VALID_STATE_STRING_FEATURE_COUNT (int): final static field
        VALID_COMMAND (int): final static field
        VALID_COMMAND__VALUE (int): final static field
        VALID_COMMAND_FEATURE_COUNT (int): final static field
        VALID_COMMAND_ID (int): final static field
        VALID_COMMAND_ID__VALUE (int): final static field
        VALID_COMMAND_ID_FEATURE_COUNT (int): final static field
        VALID_COMMAND_NUMBER (int): final static field
        VALID_COMMAND_NUMBER__VALUE (int): final static field
        VALID_COMMAND_NUMBER_FEATURE_COUNT (int): final static field
        VALID_COMMAND_STRING (int): final static field
        VALID_COMMAND_STRING__VALUE (int): final static field
        VALID_COMMAND_STRING_FEATURE_COUNT (int): final static field
        VALID_TRIGGER (int): final static field
        VALID_TRIGGER__VALUE (int): final static field
        VALID_TRIGGER_FEATURE_COUNT (int): final static field
        VALID_TRIGGER_ID (int): final static field
        VALID_TRIGGER_ID__VALUE (int): final static field
        VALID_TRIGGER_ID_FEATURE_COUNT (int): final static field
        VALID_TRIGGER_NUMBER (int): final static field
        VALID_TRIGGER_NUMBER__VALUE (int): final static field
        VALID_TRIGGER_NUMBER_FEATURE_COUNT (int): final static field
        VALID_TRIGGER_STRING (int): final static field
        VALID_TRIGGER_STRING__VALUE (int): final static field
        VALID_TRIGGER_STRING_FEATURE_COUNT (int): final static field
    
    """
    eNAME: typing.ClassVar[java.lang.String] = ...
    eNS_URI: typing.ClassVar[java.lang.String] = ...
    eNS_PREFIX: typing.ClassVar[java.lang.String] = ...
    eINSTANCE: typing.ClassVar['RulesPackage'] = ...
    RULE_MODEL: typing.ClassVar[int] = ...
    RULE_MODEL__IMPORT_SECTION: typing.ClassVar[int] = ...
    RULE_MODEL__VARIABLES: typing.ClassVar[int] = ...
    RULE_MODEL__RULES: typing.ClassVar[int] = ...
    RULE_MODEL_FEATURE_COUNT: typing.ClassVar[int] = ...
    VARIABLE_DECLARATION: typing.ClassVar[int] = ...
    VARIABLE_DECLARATION__WRITEABLE: typing.ClassVar[int] = ...
    VARIABLE_DECLARATION__TYPE: typing.ClassVar[int] = ...
    VARIABLE_DECLARATION__NAME: typing.ClassVar[int] = ...
    VARIABLE_DECLARATION__RIGHT: typing.ClassVar[int] = ...
    VARIABLE_DECLARATION_FEATURE_COUNT: typing.ClassVar[int] = ...
    RULE: typing.ClassVar[int] = ...
    RULE__NAME: typing.ClassVar[int] = ...
    RULE__EVENTTRIGGER: typing.ClassVar[int] = ...
    RULE__SCRIPT: typing.ClassVar[int] = ...
    RULE_FEATURE_COUNT: typing.ClassVar[int] = ...
    EVENT_TRIGGER: typing.ClassVar[int] = ...
    EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    COMMAND_EVENT_TRIGGER: typing.ClassVar[int] = ...
    COMMAND_EVENT_TRIGGER__ITEM: typing.ClassVar[int] = ...
    COMMAND_EVENT_TRIGGER__COMMAND: typing.ClassVar[int] = ...
    COMMAND_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    GROUP_MEMBER_COMMAND_EVENT_TRIGGER: typing.ClassVar[int] = ...
    GROUP_MEMBER_COMMAND_EVENT_TRIGGER__GROUP: typing.ClassVar[int] = ...
    GROUP_MEMBER_COMMAND_EVENT_TRIGGER__COMMAND: typing.ClassVar[int] = ...
    GROUP_MEMBER_COMMAND_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    UPDATE_EVENT_TRIGGER: typing.ClassVar[int] = ...
    UPDATE_EVENT_TRIGGER__ITEM: typing.ClassVar[int] = ...
    UPDATE_EVENT_TRIGGER__STATE: typing.ClassVar[int] = ...
    UPDATE_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    GROUP_MEMBER_UPDATE_EVENT_TRIGGER: typing.ClassVar[int] = ...
    GROUP_MEMBER_UPDATE_EVENT_TRIGGER__GROUP: typing.ClassVar[int] = ...
    GROUP_MEMBER_UPDATE_EVENT_TRIGGER__STATE: typing.ClassVar[int] = ...
    GROUP_MEMBER_UPDATE_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    CHANGED_EVENT_TRIGGER: typing.ClassVar[int] = ...
    CHANGED_EVENT_TRIGGER__ITEM: typing.ClassVar[int] = ...
    CHANGED_EVENT_TRIGGER__OLD_STATE: typing.ClassVar[int] = ...
    CHANGED_EVENT_TRIGGER__NEW_STATE: typing.ClassVar[int] = ...
    CHANGED_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    GROUP_MEMBER_CHANGED_EVENT_TRIGGER: typing.ClassVar[int] = ...
    GROUP_MEMBER_CHANGED_EVENT_TRIGGER__GROUP: typing.ClassVar[int] = ...
    GROUP_MEMBER_CHANGED_EVENT_TRIGGER__OLD_STATE: typing.ClassVar[int] = ...
    GROUP_MEMBER_CHANGED_EVENT_TRIGGER__NEW_STATE: typing.ClassVar[int] = ...
    GROUP_MEMBER_CHANGED_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    EVENT_EMITTED_TRIGGER: typing.ClassVar[int] = ...
    EVENT_EMITTED_TRIGGER__CHANNEL: typing.ClassVar[int] = ...
    EVENT_EMITTED_TRIGGER__TRIGGER: typing.ClassVar[int] = ...
    EVENT_EMITTED_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    TIMER_TRIGGER: typing.ClassVar[int] = ...
    TIMER_TRIGGER__CRON: typing.ClassVar[int] = ...
    TIMER_TRIGGER__TIME: typing.ClassVar[int] = ...
    TIMER_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    SYSTEM_TRIGGER: typing.ClassVar[int] = ...
    SYSTEM_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    SYSTEM_ON_STARTUP_TRIGGER: typing.ClassVar[int] = ...
    SYSTEM_ON_STARTUP_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    SYSTEM_ON_SHUTDOWN_TRIGGER: typing.ClassVar[int] = ...
    SYSTEM_ON_SHUTDOWN_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    THING_STATE_UPDATE_EVENT_TRIGGER: typing.ClassVar[int] = ...
    THING_STATE_UPDATE_EVENT_TRIGGER__THING: typing.ClassVar[int] = ...
    THING_STATE_UPDATE_EVENT_TRIGGER__STATE: typing.ClassVar[int] = ...
    THING_STATE_UPDATE_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    THING_STATE_CHANGED_EVENT_TRIGGER: typing.ClassVar[int] = ...
    THING_STATE_CHANGED_EVENT_TRIGGER__THING: typing.ClassVar[int] = ...
    THING_STATE_CHANGED_EVENT_TRIGGER__OLD_STATE: typing.ClassVar[int] = ...
    THING_STATE_CHANGED_EVENT_TRIGGER__NEW_STATE: typing.ClassVar[int] = ...
    THING_STATE_CHANGED_EVENT_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_STATE: typing.ClassVar[int] = ...
    VALID_STATE__VALUE: typing.ClassVar[int] = ...
    VALID_STATE_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_STATE_ID: typing.ClassVar[int] = ...
    VALID_STATE_ID__VALUE: typing.ClassVar[int] = ...
    VALID_STATE_ID_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_STATE_NUMBER: typing.ClassVar[int] = ...
    VALID_STATE_NUMBER__VALUE: typing.ClassVar[int] = ...
    VALID_STATE_NUMBER_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_STATE_STRING: typing.ClassVar[int] = ...
    VALID_STATE_STRING__VALUE: typing.ClassVar[int] = ...
    VALID_STATE_STRING_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_COMMAND: typing.ClassVar[int] = ...
    VALID_COMMAND__VALUE: typing.ClassVar[int] = ...
    VALID_COMMAND_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_COMMAND_ID: typing.ClassVar[int] = ...
    VALID_COMMAND_ID__VALUE: typing.ClassVar[int] = ...
    VALID_COMMAND_ID_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_COMMAND_NUMBER: typing.ClassVar[int] = ...
    VALID_COMMAND_NUMBER__VALUE: typing.ClassVar[int] = ...
    VALID_COMMAND_NUMBER_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_COMMAND_STRING: typing.ClassVar[int] = ...
    VALID_COMMAND_STRING__VALUE: typing.ClassVar[int] = ...
    VALID_COMMAND_STRING_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_TRIGGER: typing.ClassVar[int] = ...
    VALID_TRIGGER__VALUE: typing.ClassVar[int] = ...
    VALID_TRIGGER_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_TRIGGER_ID: typing.ClassVar[int] = ...
    VALID_TRIGGER_ID__VALUE: typing.ClassVar[int] = ...
    VALID_TRIGGER_ID_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_TRIGGER_NUMBER: typing.ClassVar[int] = ...
    VALID_TRIGGER_NUMBER__VALUE: typing.ClassVar[int] = ...
    VALID_TRIGGER_NUMBER_FEATURE_COUNT: typing.ClassVar[int] = ...
    VALID_TRIGGER_STRING: typing.ClassVar[int] = ...
    VALID_TRIGGER_STRING__VALUE: typing.ClassVar[int] = ...
    VALID_TRIGGER_STRING_FEATURE_COUNT: typing.ClassVar[int] = ...
    def getChangedEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getChangedEventTrigger_Item(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getChangedEventTrigger_NewState(self) -> org.eclipse.emf.ecore.EReference: ...
    def getChangedEventTrigger_OldState(self) -> org.eclipse.emf.ecore.EReference: ...
    def getCommandEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getCommandEventTrigger_Command(self) -> org.eclipse.emf.ecore.EReference: ...
    def getCommandEventTrigger_Item(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getEventEmittedTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getEventEmittedTrigger_Channel(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getEventEmittedTrigger_Trigger(self) -> org.eclipse.emf.ecore.EReference: ...
    def getEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getGroupMemberChangedEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getGroupMemberChangedEventTrigger_Group(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getGroupMemberChangedEventTrigger_NewState(self) -> org.eclipse.emf.ecore.EReference: ...
    def getGroupMemberChangedEventTrigger_OldState(self) -> org.eclipse.emf.ecore.EReference: ...
    def getGroupMemberCommandEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getGroupMemberCommandEventTrigger_Command(self) -> org.eclipse.emf.ecore.EReference: ...
    def getGroupMemberCommandEventTrigger_Group(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getGroupMemberUpdateEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getGroupMemberUpdateEventTrigger_Group(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getGroupMemberUpdateEventTrigger_State(self) -> org.eclipse.emf.ecore.EReference: ...
    def getRule(self) -> org.eclipse.emf.ecore.EClass: ...
    def getRuleModel(self) -> org.eclipse.emf.ecore.EClass: ...
    def getRuleModel_ImportSection(self) -> org.eclipse.emf.ecore.EReference: ...
    def getRuleModel_Rules(self) -> org.eclipse.emf.ecore.EReference: ...
    def getRuleModel_Variables(self) -> org.eclipse.emf.ecore.EReference: ...
    def getRule_Eventtrigger(self) -> org.eclipse.emf.ecore.EReference: ...
    def getRule_Name(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getRule_Script(self) -> org.eclipse.emf.ecore.EReference: ...
    def getRulesFactory(self) -> RulesFactory: ...
    def getSystemOnShutdownTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSystemOnStartupTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getSystemTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getThingStateChangedEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getThingStateChangedEventTrigger_NewState(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getThingStateChangedEventTrigger_OldState(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getThingStateChangedEventTrigger_Thing(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getThingStateUpdateEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getThingStateUpdateEventTrigger_State(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getThingStateUpdateEventTrigger_Thing(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getTimerTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getTimerTrigger_Cron(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getTimerTrigger_Time(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getUpdateEventTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getUpdateEventTrigger_Item(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getUpdateEventTrigger_State(self) -> org.eclipse.emf.ecore.EReference: ...
    def getValidCommand(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidCommandId(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidCommandNumber(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidCommandString(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidCommand_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getValidState(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidStateId(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidStateNumber(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidStateString(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidState_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getValidTrigger(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidTriggerId(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidTriggerNumber(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidTriggerString(self) -> org.eclipse.emf.ecore.EClass: ...
    def getValidTrigger_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getVariableDeclaration(self) -> org.eclipse.emf.ecore.EClass: ...
    def getVariableDeclaration_Name(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getVariableDeclaration_Right(self) -> org.eclipse.emf.ecore.EReference: ...
    def getVariableDeclaration_Type(self) -> org.eclipse.emf.ecore.EReference: ...
    def getVariableDeclaration_Writeable(self) -> org.eclipse.emf.ecore.EAttribute: ...
    class Literals(java.lang.Object):
        """
        Java class 'org.openhab.core.model.rule.rules.RulesPackage$Literals'
        
          Attributes:
            RULE_MODEL (org.eclipse.emf.ecore.EClass): final static field
            RULE_MODEL__IMPORT_SECTION (org.eclipse.emf.ecore.EReference): final static field
            RULE_MODEL__VARIABLES (org.eclipse.emf.ecore.EReference): final static field
            RULE_MODEL__RULES (org.eclipse.emf.ecore.EReference): final static field
            VARIABLE_DECLARATION (org.eclipse.emf.ecore.EClass): final static field
            VARIABLE_DECLARATION__WRITEABLE (org.eclipse.emf.ecore.EAttribute): final static field
            VARIABLE_DECLARATION__TYPE (org.eclipse.emf.ecore.EReference): final static field
            VARIABLE_DECLARATION__NAME (org.eclipse.emf.ecore.EAttribute): final static field
            VARIABLE_DECLARATION__RIGHT (org.eclipse.emf.ecore.EReference): final static field
            RULE (org.eclipse.emf.ecore.EClass): final static field
            RULE__NAME (org.eclipse.emf.ecore.EAttribute): final static field
            RULE__EVENTTRIGGER (org.eclipse.emf.ecore.EReference): final static field
            RULE__SCRIPT (org.eclipse.emf.ecore.EReference): final static field
            EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            COMMAND_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            COMMAND_EVENT_TRIGGER__ITEM (org.eclipse.emf.ecore.EAttribute): final static field
            COMMAND_EVENT_TRIGGER__COMMAND (org.eclipse.emf.ecore.EReference): final static field
            GROUP_MEMBER_COMMAND_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            GROUP_MEMBER_COMMAND_EVENT_TRIGGER__GROUP (org.eclipse.emf.ecore.EAttribute): final static field
            GROUP_MEMBER_COMMAND_EVENT_TRIGGER__COMMAND (org.eclipse.emf.ecore.EReference): final static field
            UPDATE_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            UPDATE_EVENT_TRIGGER__ITEM (org.eclipse.emf.ecore.EAttribute): final static field
            UPDATE_EVENT_TRIGGER__STATE (org.eclipse.emf.ecore.EReference): final static field
            GROUP_MEMBER_UPDATE_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            GROUP_MEMBER_UPDATE_EVENT_TRIGGER__GROUP (org.eclipse.emf.ecore.EAttribute): final static field
            GROUP_MEMBER_UPDATE_EVENT_TRIGGER__STATE (org.eclipse.emf.ecore.EReference): final static field
            CHANGED_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            CHANGED_EVENT_TRIGGER__ITEM (org.eclipse.emf.ecore.EAttribute): final static field
            CHANGED_EVENT_TRIGGER__OLD_STATE (org.eclipse.emf.ecore.EReference): final static field
            CHANGED_EVENT_TRIGGER__NEW_STATE (org.eclipse.emf.ecore.EReference): final static field
            GROUP_MEMBER_CHANGED_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            GROUP_MEMBER_CHANGED_EVENT_TRIGGER__GROUP (org.eclipse.emf.ecore.EAttribute): final static field
            GROUP_MEMBER_CHANGED_EVENT_TRIGGER__OLD_STATE (org.eclipse.emf.ecore.EReference): final static field
            GROUP_MEMBER_CHANGED_EVENT_TRIGGER__NEW_STATE (org.eclipse.emf.ecore.EReference): final static field
            EVENT_EMITTED_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            EVENT_EMITTED_TRIGGER__CHANNEL (org.eclipse.emf.ecore.EAttribute): final static field
            EVENT_EMITTED_TRIGGER__TRIGGER (org.eclipse.emf.ecore.EReference): final static field
            TIMER_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            TIMER_TRIGGER__CRON (org.eclipse.emf.ecore.EAttribute): final static field
            TIMER_TRIGGER__TIME (org.eclipse.emf.ecore.EAttribute): final static field
            SYSTEM_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            SYSTEM_ON_STARTUP_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            SYSTEM_ON_SHUTDOWN_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            THING_STATE_UPDATE_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            THING_STATE_UPDATE_EVENT_TRIGGER__THING (org.eclipse.emf.ecore.EAttribute): final static field
            THING_STATE_UPDATE_EVENT_TRIGGER__STATE (org.eclipse.emf.ecore.EAttribute): final static field
            THING_STATE_CHANGED_EVENT_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            THING_STATE_CHANGED_EVENT_TRIGGER__THING (org.eclipse.emf.ecore.EAttribute): final static field
            THING_STATE_CHANGED_EVENT_TRIGGER__OLD_STATE (org.eclipse.emf.ecore.EAttribute): final static field
            THING_STATE_CHANGED_EVENT_TRIGGER__NEW_STATE (org.eclipse.emf.ecore.EAttribute): final static field
            VALID_STATE (org.eclipse.emf.ecore.EClass): final static field
            VALID_STATE__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            VALID_STATE_ID (org.eclipse.emf.ecore.EClass): final static field
            VALID_STATE_NUMBER (org.eclipse.emf.ecore.EClass): final static field
            VALID_STATE_STRING (org.eclipse.emf.ecore.EClass): final static field
            VALID_COMMAND (org.eclipse.emf.ecore.EClass): final static field
            VALID_COMMAND__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            VALID_COMMAND_ID (org.eclipse.emf.ecore.EClass): final static field
            VALID_COMMAND_NUMBER (org.eclipse.emf.ecore.EClass): final static field
            VALID_COMMAND_STRING (org.eclipse.emf.ecore.EClass): final static field
            VALID_TRIGGER (org.eclipse.emf.ecore.EClass): final static field
            VALID_TRIGGER__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            VALID_TRIGGER_ID (org.eclipse.emf.ecore.EClass): final static field
            VALID_TRIGGER_NUMBER (org.eclipse.emf.ecore.EClass): final static field
            VALID_TRIGGER_STRING (org.eclipse.emf.ecore.EClass): final static field
        
        """
        RULE_MODEL: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        RULE_MODEL__IMPORT_SECTION: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        RULE_MODEL__VARIABLES: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        RULE_MODEL__RULES: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        VARIABLE_DECLARATION: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VARIABLE_DECLARATION__WRITEABLE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VARIABLE_DECLARATION__TYPE: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        VARIABLE_DECLARATION__NAME: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VARIABLE_DECLARATION__RIGHT: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        RULE: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        RULE__NAME: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        RULE__EVENTTRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        RULE__SCRIPT: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        COMMAND_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        COMMAND_EVENT_TRIGGER__ITEM: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        COMMAND_EVENT_TRIGGER__COMMAND: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        GROUP_MEMBER_COMMAND_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        GROUP_MEMBER_COMMAND_EVENT_TRIGGER__GROUP: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        GROUP_MEMBER_COMMAND_EVENT_TRIGGER__COMMAND: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        UPDATE_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        UPDATE_EVENT_TRIGGER__ITEM: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        UPDATE_EVENT_TRIGGER__STATE: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        GROUP_MEMBER_UPDATE_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        GROUP_MEMBER_UPDATE_EVENT_TRIGGER__GROUP: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        GROUP_MEMBER_UPDATE_EVENT_TRIGGER__STATE: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        CHANGED_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        CHANGED_EVENT_TRIGGER__ITEM: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        CHANGED_EVENT_TRIGGER__OLD_STATE: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        CHANGED_EVENT_TRIGGER__NEW_STATE: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER__GROUP: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER__OLD_STATE: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        GROUP_MEMBER_CHANGED_EVENT_TRIGGER__NEW_STATE: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        EVENT_EMITTED_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        EVENT_EMITTED_TRIGGER__CHANNEL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        EVENT_EMITTED_TRIGGER__TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        TIMER_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        TIMER_TRIGGER__CRON: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        TIMER_TRIGGER__TIME: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        SYSTEM_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SYSTEM_ON_STARTUP_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        SYSTEM_ON_SHUTDOWN_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        THING_STATE_UPDATE_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        THING_STATE_UPDATE_EVENT_TRIGGER__THING: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        THING_STATE_UPDATE_EVENT_TRIGGER__STATE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        THING_STATE_CHANGED_EVENT_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        THING_STATE_CHANGED_EVENT_TRIGGER__THING: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        THING_STATE_CHANGED_EVENT_TRIGGER__OLD_STATE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        THING_STATE_CHANGED_EVENT_TRIGGER__NEW_STATE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VALID_STATE: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_STATE__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VALID_STATE_ID: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_STATE_NUMBER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_STATE_STRING: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_COMMAND: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_COMMAND__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VALID_COMMAND_ID: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_COMMAND_NUMBER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_COMMAND_STRING: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_TRIGGER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_TRIGGER__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        VALID_TRIGGER_ID: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_TRIGGER_NUMBER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        VALID_TRIGGER_STRING: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...

class ValidCommand(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidCommand'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getValue(self) -> java.lang.String: ...
    def setValue(self, value: java.lang.String) -> None: ...

class ValidState(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidState'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getValue(self) -> java.lang.String: ...
    def setValue(self, value: java.lang.String) -> None: ...

class ValidTrigger(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidTrigger'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getValue(self) -> java.lang.String: ...
    def setValue(self, value: java.lang.String) -> None: ...

class VariableDeclaration(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.rule.rules.VariableDeclaration'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getName(self) -> java.lang.String: ...
    def getRight(self) -> org.eclipse.xtext.xbase.XExpression: ...
    def getType(self) -> org.eclipse.xtext.common.types.JvmTypeReference: ...
    def isWriteable(self) -> bool: ...
    def setName(self, value: java.lang.String) -> None: ...
    def setRight(self, value: org.eclipse.xtext.xbase.XExpression) -> None: ...
    def setType(self, value: org.eclipse.xtext.common.types.JvmTypeReference) -> None: ...
    def setWriteable(self, value: bool) -> None: ...

class ChangedEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.ChangedEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getItem(self) -> java.lang.String: ...
    def getNewState(self) -> ValidState: ...
    def getOldState(self) -> ValidState: ...
    def setItem(self, value: java.lang.String) -> None: ...
    def setNewState(self, value: ValidState) -> None: ...
    def setOldState(self, value: ValidState) -> None: ...

class CommandEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.CommandEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getCommand(self) -> ValidCommand: ...
    def getItem(self) -> java.lang.String: ...
    def setCommand(self, value: ValidCommand) -> None: ...
    def setItem(self, value: java.lang.String) -> None: ...

class EventEmittedTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.EventEmittedTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getChannel(self) -> java.lang.String: ...
    def getTrigger(self) -> ValidTrigger: ...
    def setChannel(self, value: java.lang.String) -> None: ...
    def setTrigger(self, value: ValidTrigger) -> None: ...

class GroupMemberChangedEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.GroupMemberChangedEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getGroup(self) -> java.lang.String: ...
    def getNewState(self) -> ValidState: ...
    def getOldState(self) -> ValidState: ...
    def setGroup(self, value: java.lang.String) -> None: ...
    def setNewState(self, value: ValidState) -> None: ...
    def setOldState(self, value: ValidState) -> None: ...

class GroupMemberCommandEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.GroupMemberCommandEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getCommand(self) -> ValidCommand: ...
    def getGroup(self) -> java.lang.String: ...
    def setCommand(self, value: ValidCommand) -> None: ...
    def setGroup(self, value: java.lang.String) -> None: ...

class GroupMemberUpdateEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.GroupMemberUpdateEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getGroup(self) -> java.lang.String: ...
    def getState(self) -> ValidState: ...
    def setGroup(self, value: java.lang.String) -> None: ...
    def setState(self, value: ValidState) -> None: ...

class SystemTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.SystemTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """

class ThingStateChangedEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.ThingStateChangedEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getNewState(self) -> java.lang.String: ...
    def getOldState(self) -> java.lang.String: ...
    def getThing(self) -> java.lang.String: ...
    def setNewState(self, value: java.lang.String) -> None: ...
    def setOldState(self, value: java.lang.String) -> None: ...
    def setThing(self, value: java.lang.String) -> None: ...

class ThingStateUpdateEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.ThingStateUpdateEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getState(self) -> java.lang.String: ...
    def getThing(self) -> java.lang.String: ...
    def setState(self, value: java.lang.String) -> None: ...
    def setThing(self, value: java.lang.String) -> None: ...

class TimerTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.TimerTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getCron(self) -> java.lang.String: ...
    def getTime(self) -> java.lang.String: ...
    def setCron(self, value: java.lang.String) -> None: ...
    def setTime(self, value: java.lang.String) -> None: ...

class UpdateEventTrigger(EventTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.UpdateEventTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.EventTrigger
    
    """
    def getItem(self) -> java.lang.String: ...
    def getState(self) -> ValidState: ...
    def setItem(self, value: java.lang.String) -> None: ...
    def setState(self, value: ValidState) -> None: ...

class ValidCommandId(ValidCommand):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidCommandId'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidCommand
    
    """

class ValidCommandNumber(ValidCommand):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidCommandNumber'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidCommand
    
    """

class ValidCommandString(ValidCommand):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidCommandString'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidCommand
    
    """

class ValidStateId(ValidState):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidStateId'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidState
    
    """

class ValidStateNumber(ValidState):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidStateNumber'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidState
    
    """

class ValidStateString(ValidState):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidStateString'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidState
    
    """

class ValidTriggerId(ValidTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidTriggerId'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidTrigger
    
    """

class ValidTriggerNumber(ValidTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidTriggerNumber'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidTrigger
    
    """

class ValidTriggerString(ValidTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.ValidTriggerString'
    
        Interfaces:
            org.openhab.core.model.rule.rules.ValidTrigger
    
    """

class SystemOnShutdownTrigger(SystemTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.SystemOnShutdownTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.SystemTrigger
    
    """

class SystemOnStartupTrigger(SystemTrigger):
    """
    Java class 'org.openhab.core.model.rule.rules.SystemOnStartupTrigger'
    
        Interfaces:
            org.openhab.core.model.rule.rules.SystemTrigger
    
    """
