import java.io
import java.lang
import java.security
import java.security.cert
import java.util
import java.util.stream
import java.util.zip
import typing


class Attributes(java.util.Map[typing.Any, typing.Any], java.lang.Cloneable):
    """
    Java class 'java.util.jar.Attributes'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            java.util.Map, java.lang.Cloneable
    
      Constructors:
        * Attributes(java.util.jar.Attributes)
        * Attributes(int)
        * Attributes()
    
    """
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, attributes: 'Attributes'): ...
    def clear(self) -> None: ...
    def clone(self) -> typing.Any: ...
    def containsKey(self, object: typing.Any) -> bool: ...
    def containsValue(self, object: typing.Any) -> bool: ...
    def entrySet(self) -> java.util.Set[java.util.Map.Entry[typing.Any, typing.Any]]: ...
    def equals(self, object: typing.Any) -> bool: ...
    def get(self, object: typing.Any) -> typing.Any: ...
    @typing.overload
    def getValue(self, string: java.lang.String) -> java.lang.String: ...
    @typing.overload
    def getValue(self, name: 'Attributes.Name') -> java.lang.String: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def keySet(self) -> java.util.Set[typing.Any]: ...
    def put(self, object: typing.Any, object2: typing.Any) -> typing.Any: ...
    def putAll(self, map: typing.Union[java.util.Map[typing.Any, typing.Any], typing.Mapping[typing.Any, typing.Any]]) -> None: ...
    def putValue(self, string: java.lang.String, string2: java.lang.String) -> java.lang.String: ...
    @typing.overload
    def remove(self, object: typing.Any, object2: typing.Any) -> bool: ...
    @typing.overload
    def remove(self, object: typing.Any) -> typing.Any: ...
    def size(self) -> int: ...
    def values(self) -> java.util.Collection[typing.Any]: ...
    class Name(java.lang.Object):
        """
        Java class 'java.util.jar.Attributes$Name'
        
            Extends:
                java.lang.Object
        
          Constructors:
            * Name(java.lang.String)
        
          Attributes:
            MANIFEST_VERSION (java.util.jar.Attributes$Name): final static field
            SIGNATURE_VERSION (java.util.jar.Attributes$Name): final static field
            CONTENT_TYPE (java.util.jar.Attributes$Name): final static field
            CLASS_PATH (java.util.jar.Attributes$Name): final static field
            MAIN_CLASS (java.util.jar.Attributes$Name): final static field
            SEALED (java.util.jar.Attributes$Name): final static field
            EXTENSION_LIST (java.util.jar.Attributes$Name): final static field
            EXTENSION_NAME (java.util.jar.Attributes$Name): final static field
            EXTENSION_INSTALLATION (java.util.jar.Attributes$Name): final static field
            IMPLEMENTATION_TITLE (java.util.jar.Attributes$Name): final static field
            IMPLEMENTATION_VERSION (java.util.jar.Attributes$Name): final static field
            IMPLEMENTATION_VENDOR (java.util.jar.Attributes$Name): final static field
            IMPLEMENTATION_VENDOR_ID (java.util.jar.Attributes$Name): final static field
            IMPLEMENTATION_URL (java.util.jar.Attributes$Name): final static field
            SPECIFICATION_TITLE (java.util.jar.Attributes$Name): final static field
            SPECIFICATION_VERSION (java.util.jar.Attributes$Name): final static field
            SPECIFICATION_VENDOR (java.util.jar.Attributes$Name): final static field
            MULTI_RELEASE (java.util.jar.Attributes$Name): final static field
        
        """
        MANIFEST_VERSION: typing.ClassVar['Attributes.Name'] = ...
        SIGNATURE_VERSION: typing.ClassVar['Attributes.Name'] = ...
        CONTENT_TYPE: typing.ClassVar['Attributes.Name'] = ...
        CLASS_PATH: typing.ClassVar['Attributes.Name'] = ...
        MAIN_CLASS: typing.ClassVar['Attributes.Name'] = ...
        SEALED: typing.ClassVar['Attributes.Name'] = ...
        EXTENSION_LIST: typing.ClassVar['Attributes.Name'] = ...
        EXTENSION_NAME: typing.ClassVar['Attributes.Name'] = ...
        EXTENSION_INSTALLATION: typing.ClassVar['Attributes.Name'] = ...
        IMPLEMENTATION_TITLE: typing.ClassVar['Attributes.Name'] = ...
        IMPLEMENTATION_VERSION: typing.ClassVar['Attributes.Name'] = ...
        IMPLEMENTATION_VENDOR: typing.ClassVar['Attributes.Name'] = ...
        IMPLEMENTATION_VENDOR_ID: typing.ClassVar['Attributes.Name'] = ...
        IMPLEMENTATION_URL: typing.ClassVar['Attributes.Name'] = ...
        SPECIFICATION_TITLE: typing.ClassVar['Attributes.Name'] = ...
        SPECIFICATION_VERSION: typing.ClassVar['Attributes.Name'] = ...
        SPECIFICATION_VENDOR: typing.ClassVar['Attributes.Name'] = ...
        MULTI_RELEASE: typing.ClassVar['Attributes.Name'] = ...
        def __init__(self, string: java.lang.String): ...
        def equals(self, object: typing.Any) -> bool: ...
        def hashCode(self) -> int: ...
        def toString(self) -> java.lang.String: ...

class JarEntry(java.util.zip.ZipEntry):
    """
    Java class 'java.util.jar.JarEntry'
    
        Extends:
            java.util.zip.ZipEntry
    
      Constructors:
        * JarEntry(java.util.jar.JarEntry)
        * JarEntry(java.util.zip.ZipEntry)
        * JarEntry(java.lang.String)
    
    """
    @typing.overload
    def __init__(self, string: java.lang.String): ...
    @typing.overload
    def __init__(self, jarEntry: 'JarEntry'): ...
    @typing.overload
    def __init__(self, zipEntry: java.util.zip.ZipEntry): ...
    def getAttributes(self) -> Attributes: ...
    def getCertificates(self) -> typing.List[java.security.cert.Certificate]: ...
    def getCodeSigners(self) -> typing.List[java.security.CodeSigner]: ...
    def getRealName(self) -> java.lang.String: ...

class JarException(java.util.zip.ZipException):
    """
    Java class 'java.util.jar.JarException'
    
        Extends:
            java.util.zip.ZipException
    
      Constructors:
        * JarException()
        * JarException(java.lang.String)
    
    """
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: java.lang.String): ...

class JarFile(java.util.zip.ZipFile):
    """
    Java class 'java.util.jar.JarFile'
    
        Extends:
            java.util.zip.ZipFile
    
      Constructors:
        * JarFile(java.lang.String, boolean)
        * JarFile(java.io.File, boolean, int, java.lang.Runtime.Version)
        * JarFile(java.io.File, boolean)
        * JarFile(java.io.File, boolean, int)
        * JarFile(java.io.File)
        * JarFile(java.lang.String)
    
      Raises:
        java.io.IOException: from java
    
      Attributes:
        MANIFEST_NAME (java.lang.String): final static field
    
    """
    MANIFEST_NAME: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self, file: java.io.File): ...
    @typing.overload
    def __init__(self, file: java.io.File, boolean: bool): ...
    @typing.overload
    def __init__(self, file: java.io.File, boolean: bool, int: int): ...
    @typing.overload
    def __init__(self, file: java.io.File, boolean: bool, int: int, version: java.lang.Runtime.Version): ...
    @typing.overload
    def __init__(self, string: java.lang.String): ...
    @typing.overload
    def __init__(self, string: java.lang.String, boolean: bool): ...
    @classmethod
    def baseVersion(cls) -> java.lang.Runtime.Version: ...
    def entries(self) -> java.util.Enumeration[JarEntry]: ...
    def getEntry(self, string: java.lang.String) -> java.util.zip.ZipEntry: ...
    def getInputStream(self, zipEntry: java.util.zip.ZipEntry) -> java.io.InputStream: ...
    def getJarEntry(self, string: java.lang.String) -> JarEntry: ...
    def getManifest(self) -> 'Manifest': ...
    def getVersion(self) -> java.lang.Runtime.Version: ...
    def isMultiRelease(self) -> bool: ...
    @classmethod
    def runtimeVersion(cls) -> java.lang.Runtime.Version: ...
    def stream(self) -> java.util.stream.Stream[JarEntry]: ...
    def versionedStream(self) -> java.util.stream.Stream[JarEntry]: ...

class JarInputStream(java.util.zip.ZipInputStream):
    """
    Java class 'java.util.jar.JarInputStream'
    
        Extends:
            java.util.zip.ZipInputStream
    
      Constructors:
        * JarInputStream(java.io.InputStream)
        * JarInputStream(java.io.InputStream, boolean)
    
      Raises:
        java.io.IOException: from java
    
    """
    @typing.overload
    def __init__(self, inputStream: java.io.InputStream): ...
    @typing.overload
    def __init__(self, inputStream: java.io.InputStream, boolean: bool): ...
    def getManifest(self) -> 'Manifest': ...
    def getNextEntry(self) -> java.util.zip.ZipEntry: ...
    def getNextJarEntry(self) -> JarEntry: ...
    @typing.overload
    def read(self, byteArray: typing.List[int]) -> int: ...
    @typing.overload
    def read(self, byteArray: typing.List[int], int: int, int2: int) -> int: ...
    @typing.overload
    def read(self) -> int: ...

class JarOutputStream(java.util.zip.ZipOutputStream):
    """
    Java class 'java.util.jar.JarOutputStream'
    
        Extends:
            java.util.zip.ZipOutputStream
    
      Constructors:
        * JarOutputStream(java.io.OutputStream, java.util.jar.Manifest)
        * JarOutputStream(java.io.OutputStream)
    
      Raises:
        java.io.IOException: from java
    
    """
    @typing.overload
    def __init__(self, outputStream: java.io.OutputStream): ...
    @typing.overload
    def __init__(self, outputStream: java.io.OutputStream, manifest: 'Manifest'): ...
    def putNextEntry(self, zipEntry: java.util.zip.ZipEntry) -> None: ...

class Manifest(java.lang.Cloneable):
    """
    Java class 'java.util.jar.Manifest'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            java.lang.Cloneable
    
      Constructors:
        * Manifest(java.util.jar.Manifest)
        * Manifest(java.io.InputStream)
        * Manifest()
    
      Raises:
        java.io.IOException: from java
    
    """
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, inputStream: java.io.InputStream): ...
    @typing.overload
    def __init__(self, manifest: 'Manifest'): ...
    def clear(self) -> None: ...
    def clone(self) -> typing.Any: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getAttributes(self, string: java.lang.String) -> Attributes: ...
    def getEntries(self) -> java.util.Map[java.lang.String, Attributes]: ...
    def getMainAttributes(self) -> Attributes: ...
    def hashCode(self) -> int: ...
    def read(self, inputStream: java.io.InputStream) -> None: ...
    def write(self, outputStream: java.io.OutputStream) -> None: ...

class Pack200(java.lang.Object):
    """
    Java class 'java.util.jar.Pack200'
    
        Extends:
            java.lang.Object
    
    """
    @classmethod
    def newPacker(cls) -> 'Pack200.Packer': ...
    @classmethod
    def newUnpacker(cls) -> 'Pack200.Unpacker': ...
    class Packer(java.lang.Object):
        """
        Java class 'java.util.jar.Pack200$Packer'
        
          Attributes:
            SEGMENT_LIMIT (java.lang.String): final static field
            KEEP_FILE_ORDER (java.lang.String): final static field
            EFFORT (java.lang.String): final static field
            DEFLATE_HINT (java.lang.String): final static field
            MODIFICATION_TIME (java.lang.String): final static field
            PASS_FILE_PFX (java.lang.String): final static field
            UNKNOWN_ATTRIBUTE (java.lang.String): final static field
            CLASS_ATTRIBUTE_PFX (java.lang.String): final static field
            FIELD_ATTRIBUTE_PFX (java.lang.String): final static field
            METHOD_ATTRIBUTE_PFX (java.lang.String): final static field
            CODE_ATTRIBUTE_PFX (java.lang.String): final static field
            PROGRESS (java.lang.String): final static field
            KEEP (java.lang.String): final static field
            PASS (java.lang.String): final static field
            STRIP (java.lang.String): final static field
            ERROR (java.lang.String): final static field
            TRUE (java.lang.String): final static field
            FALSE (java.lang.String): final static field
            LATEST (java.lang.String): final static field
        
        """
        SEGMENT_LIMIT: typing.ClassVar[java.lang.String] = ...
        KEEP_FILE_ORDER: typing.ClassVar[java.lang.String] = ...
        EFFORT: typing.ClassVar[java.lang.String] = ...
        DEFLATE_HINT: typing.ClassVar[java.lang.String] = ...
        MODIFICATION_TIME: typing.ClassVar[java.lang.String] = ...
        PASS_FILE_PFX: typing.ClassVar[java.lang.String] = ...
        UNKNOWN_ATTRIBUTE: typing.ClassVar[java.lang.String] = ...
        CLASS_ATTRIBUTE_PFX: typing.ClassVar[java.lang.String] = ...
        FIELD_ATTRIBUTE_PFX: typing.ClassVar[java.lang.String] = ...
        METHOD_ATTRIBUTE_PFX: typing.ClassVar[java.lang.String] = ...
        CODE_ATTRIBUTE_PFX: typing.ClassVar[java.lang.String] = ...
        PROGRESS: typing.ClassVar[java.lang.String] = ...
        KEEP: typing.ClassVar[java.lang.String] = ...
        PASS: typing.ClassVar[java.lang.String] = ...
        STRIP: typing.ClassVar[java.lang.String] = ...
        ERROR: typing.ClassVar[java.lang.String] = ...
        TRUE: typing.ClassVar[java.lang.String] = ...
        FALSE: typing.ClassVar[java.lang.String] = ...
        LATEST: typing.ClassVar[java.lang.String] = ...
        @typing.overload
        def pack(self, jarFile: JarFile, outputStream: java.io.OutputStream) -> None: ...
        @typing.overload
        def pack(self, jarInputStream: JarInputStream, outputStream: java.io.OutputStream) -> None: ...
        def properties(self) -> java.util.SortedMap[java.lang.String, java.lang.String]: ...
    class Unpacker(java.lang.Object):
        """
        Java class 'java.util.jar.Pack200$Unpacker'
        
          Attributes:
            KEEP (java.lang.String): final static field
            TRUE (java.lang.String): final static field
            FALSE (java.lang.String): final static field
            DEFLATE_HINT (java.lang.String): final static field
            PROGRESS (java.lang.String): final static field
        
        """
        KEEP: typing.ClassVar[java.lang.String] = ...
        TRUE: typing.ClassVar[java.lang.String] = ...
        FALSE: typing.ClassVar[java.lang.String] = ...
        DEFLATE_HINT: typing.ClassVar[java.lang.String] = ...
        PROGRESS: typing.ClassVar[java.lang.String] = ...
        def properties(self) -> java.util.SortedMap[java.lang.String, java.lang.String]: ...
        @typing.overload
        def unpack(self, file: java.io.File, jarOutputStream: JarOutputStream) -> None: ...
        @typing.overload
        def unpack(self, inputStream: java.io.InputStream, jarOutputStream: JarOutputStream) -> None: ...
