import java.lang
import typing


class JaxrsWhiteboardConstants(java.lang.Object):
    """
    Java class 'org.osgi.service.jaxrs.whiteboard.JaxrsWhiteboardConstants'
    
        Extends:
            java.lang.Object
    
      Attributes:
        JAX_RS_NAME (java.lang.String): final static field
        JAX_RS_RESOURCE (java.lang.String): final static field
        JAX_RS_APPLICATION_BASE (java.lang.String): final static field
        JAX_RS_APPLICATION_SELECT (java.lang.String): final static field
        JAX_RS_APPLICATION_SERVICE_PROPERTIES (java.lang.String): final static field
        JAX_RS_DEFAULT_APPLICATION (java.lang.String): final static field
        JAX_RS_EXTENSION (java.lang.String): final static field
        JAX_RS_EXTENSION_SELECT (java.lang.String): final static field
        JAX_RS_MEDIA_TYPE (java.lang.String): final static field
        JAX_RS_WHITEBOARD_TARGET (java.lang.String): final static field
        JAX_RS_WHITEBOARD_IMPLEMENTATION (java.lang.String): final static field
        JAX_RS_WHITEBOARD_SPECIFICATION_VERSION (java.lang.String): final static field
    
    """
    JAX_RS_NAME: typing.ClassVar[java.lang.String] = ...
    JAX_RS_RESOURCE: typing.ClassVar[java.lang.String] = ...
    JAX_RS_APPLICATION_BASE: typing.ClassVar[java.lang.String] = ...
    JAX_RS_APPLICATION_SELECT: typing.ClassVar[java.lang.String] = ...
    JAX_RS_APPLICATION_SERVICE_PROPERTIES: typing.ClassVar[java.lang.String] = ...
    JAX_RS_DEFAULT_APPLICATION: typing.ClassVar[java.lang.String] = ...
    JAX_RS_EXTENSION: typing.ClassVar[java.lang.String] = ...
    JAX_RS_EXTENSION_SELECT: typing.ClassVar[java.lang.String] = ...
    JAX_RS_MEDIA_TYPE: typing.ClassVar[java.lang.String] = ...
    JAX_RS_WHITEBOARD_TARGET: typing.ClassVar[java.lang.String] = ...
    JAX_RS_WHITEBOARD_IMPLEMENTATION: typing.ClassVar[java.lang.String] = ...
    JAX_RS_WHITEBOARD_SPECIFICATION_VERSION: typing.ClassVar[java.lang.String] = ...
