import org.eclipse.xtext
import org.eclipse.xtext.service
import typing


class ItemsGrammarAccess(org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder):
    """
    Java class 'org.openhab.core.model.services.ItemsGrammarAccess'
    
        Extends:
            org.eclipse.xtext.service.AbstractElementFinder$AbstractGrammarElementFinder
    
      Constructors:
        * ItemsGrammarAccess(org.eclipse.xtext.service.GrammarProvider)
    
    """
    def __init__(self, grammarProvider: org.eclipse.xtext.service.GrammarProvider): ...
    def getANY_OTHERRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getBOOLEANAccess(self) -> 'ItemsGrammarAccess.BOOLEANElements': ...
    def getBOOLEANRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getBaseModelItemTypeAccess(self) -> 'ItemsGrammarAccess.BaseModelItemTypeElements': ...
    def getBaseModelItemTypeRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getGrammar(self) -> org.eclipse.xtext.Grammar: ...
    def getIDRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getItemModelAccess(self) -> 'ItemsGrammarAccess.ItemModelElements': ...
    def getItemModelRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getML_COMMENTRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getModelBindingAccess(self) -> 'ItemsGrammarAccess.ModelBindingElements': ...
    def getModelBindingRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getModelGroupFunctionAccess(self) -> 'ItemsGrammarAccess.ModelGroupFunctionElements': ...
    def getModelGroupFunctionRule(self) -> org.eclipse.xtext.EnumRule: ...
    def getModelGroupItemAccess(self) -> 'ItemsGrammarAccess.ModelGroupItemElements': ...
    def getModelGroupItemRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getModelItemAccess(self) -> 'ItemsGrammarAccess.ModelItemElements': ...
    def getModelItemRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getModelItemTypeAccess(self) -> 'ItemsGrammarAccess.ModelItemTypeElements': ...
    def getModelItemTypeRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getModelNormalItemAccess(self) -> 'ItemsGrammarAccess.ModelNormalItemElements': ...
    def getModelNormalItemRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getModelPropertyAccess(self) -> 'ItemsGrammarAccess.ModelPropertyElements': ...
    def getModelPropertyRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getNUMBERAccess(self) -> 'ItemsGrammarAccess.NUMBERElements': ...
    def getNUMBERRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getSL_COMMENTRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getSTRINGRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getValueTypeAccess(self) -> 'ItemsGrammarAccess.ValueTypeElements': ...
    def getValueTypeRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getWSRule(self) -> org.eclipse.xtext.TerminalRule: ...
    class BOOLEANElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$BOOLEANElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * BOOLEANElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getFalseKeyword_1(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getTrueKeyword_0(self) -> org.eclipse.xtext.Keyword: ...
    class BaseModelItemTypeElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$BaseModelItemTypeElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * BaseModelItemTypeElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getCallKeyword_9(self) -> org.eclipse.xtext.Keyword: ...
        def getColorKeyword_6(self) -> org.eclipse.xtext.Keyword: ...
        def getContactKeyword_4(self) -> org.eclipse.xtext.Keyword: ...
        def getDateTimeKeyword_5(self) -> org.eclipse.xtext.Keyword: ...
        def getDimmerKeyword_3(self) -> org.eclipse.xtext.Keyword: ...
        def getImageKeyword_10(self) -> org.eclipse.xtext.Keyword: ...
        def getLocationKeyword_8(self) -> org.eclipse.xtext.Keyword: ...
        def getPlayerKeyword_7(self) -> org.eclipse.xtext.Keyword: ...
        def getRollershutterKeyword_1(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getStringKeyword_2(self) -> org.eclipse.xtext.Keyword: ...
        def getSwitchKeyword_0(self) -> org.eclipse.xtext.Keyword: ...
    class ItemModelElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ItemModelElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ItemModelElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getItemModelAction_0(self) -> org.eclipse.xtext.Action: ...
        def getItemsAssignment_1(self) -> org.eclipse.xtext.Assignment: ...
        def getItemsModelItemParserRuleCall_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
    class ModelBindingElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ModelBindingElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ModelBindingElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getCommaKeyword_3_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getConfigurationAssignment_2(self) -> org.eclipse.xtext.Assignment: ...
        def getConfigurationSTRINGTerminalRuleCall_2_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getEqualsSignKeyword_1(self) -> org.eclipse.xtext.Keyword: ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getGroup_3(self) -> org.eclipse.xtext.Group: ...
        def getGroup_3_2(self) -> org.eclipse.xtext.Group: ...
        def getLeftSquareBracketKeyword_3_0(self) -> org.eclipse.xtext.Keyword: ...
        def getPropertiesAssignment_3_1(self) -> org.eclipse.xtext.Assignment: ...
        def getPropertiesAssignment_3_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getPropertiesModelPropertyParserRuleCall_3_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getPropertiesModelPropertyParserRuleCall_3_2_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getRightSquareBracketKeyword_3_3(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getTypeAssignment_0(self) -> org.eclipse.xtext.Assignment: ...
        def getTypeIDTerminalRuleCall_0_0(self) -> org.eclipse.xtext.RuleCall: ...
    class ModelGroupFunctionElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ModelGroupFunctionElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractEnumRuleElementFinder
        
          Constructors:
            * ModelGroupFunctionElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getANDANDKeyword_1_0(self) -> org.eclipse.xtext.Keyword: ...
        def getANDEnumLiteralDeclaration_1(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getAVGAVGKeyword_5_0(self) -> org.eclipse.xtext.Keyword: ...
        def getAVGEnumLiteralDeclaration_5(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getCOUNTCOUNTKeyword_9_0(self) -> org.eclipse.xtext.Keyword: ...
        def getCOUNTEnumLiteralDeclaration_9(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getEARLIESTEARLIESTKeyword_11_0(self) -> org.eclipse.xtext.Keyword: ...
        def getEARLIESTEnumLiteralDeclaration_11(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getEQUALITYEQUALITYKeyword_0_0(self) -> org.eclipse.xtext.Keyword: ...
        def getEQUALITYEnumLiteralDeclaration_0(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getLATESTEnumLiteralDeclaration_10(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getLATESTLATESTKeyword_10_0(self) -> org.eclipse.xtext.Keyword: ...
        def getMAXEnumLiteralDeclaration_7(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getMAXMAXKeyword_7_0(self) -> org.eclipse.xtext.Keyword: ...
        def getMINEnumLiteralDeclaration_8(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getMINMINKeyword_8_0(self) -> org.eclipse.xtext.Keyword: ...
        def getNANDEnumLiteralDeclaration_3(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getNANDNANDKeyword_3_0(self) -> org.eclipse.xtext.Keyword: ...
        def getNOREnumLiteralDeclaration_4(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getNORNORKeyword_4_0(self) -> org.eclipse.xtext.Keyword: ...
        def getOREnumLiteralDeclaration_2(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getORORKeyword_2_0(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.EnumRule: ...
        def getSUMEnumLiteralDeclaration_6(self) -> org.eclipse.xtext.EnumLiteralDeclaration: ...
        def getSUMSUMKeyword_6_0(self) -> org.eclipse.xtext.Keyword: ...
    class ModelGroupItemElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ModelGroupItemElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ModelGroupItemElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getArgsAlternatives_2_2_2_1_0(self) -> org.eclipse.xtext.Alternatives: ...
        def getArgsAlternatives_2_2_2_2_1_0(self) -> org.eclipse.xtext.Alternatives: ...
        def getArgsAssignment_2_2_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getArgsAssignment_2_2_2_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getArgsIDTerminalRuleCall_2_2_2_1_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getArgsIDTerminalRuleCall_2_2_2_2_1_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getArgsSTRINGTerminalRuleCall_2_2_2_1_0_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getArgsSTRINGTerminalRuleCall_2_2_2_2_1_0_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getColonKeyword_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getColonKeyword_2_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getCommaKeyword_2_2_2_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getFunctionAssignment_2_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getFunctionModelGroupFunctionEnumRuleCall_2_2_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getGroupKeyword_1(self) -> org.eclipse.xtext.Keyword: ...
        def getGroup_2(self) -> org.eclipse.xtext.Group: ...
        def getGroup_2_2(self) -> org.eclipse.xtext.Group: ...
        def getGroup_2_2_2(self) -> org.eclipse.xtext.Group: ...
        def getGroup_2_2_2_2(self) -> org.eclipse.xtext.Group: ...
        def getLeftParenthesisKeyword_2_2_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getModelGroupItemAction_0(self) -> org.eclipse.xtext.Action: ...
        def getRightParenthesisKeyword_2_2_2_3(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getTypeAssignment_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getTypeModelItemTypeParserRuleCall_2_1_0(self) -> org.eclipse.xtext.RuleCall: ...
    class ModelItemElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ModelItemElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ModelItemElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives_0(self) -> org.eclipse.xtext.Alternatives: ...
        def getBindingsAssignment_6_1(self) -> org.eclipse.xtext.Assignment: ...
        def getBindingsAssignment_6_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getBindingsModelBindingParserRuleCall_6_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getBindingsModelBindingParserRuleCall_6_2_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getCommaKeyword_4_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getCommaKeyword_5_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getCommaKeyword_6_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getGreaterThanSignKeyword_3_2(self) -> org.eclipse.xtext.Keyword: ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getGroup_3(self) -> org.eclipse.xtext.Group: ...
        def getGroup_4(self) -> org.eclipse.xtext.Group: ...
        def getGroup_4_2(self) -> org.eclipse.xtext.Group: ...
        def getGroup_5(self) -> org.eclipse.xtext.Group: ...
        def getGroup_5_2(self) -> org.eclipse.xtext.Group: ...
        def getGroup_6(self) -> org.eclipse.xtext.Group: ...
        def getGroup_6_2(self) -> org.eclipse.xtext.Group: ...
        def getGroupsAssignment_4_1(self) -> org.eclipse.xtext.Assignment: ...
        def getGroupsAssignment_4_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getGroupsIDTerminalRuleCall_4_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getGroupsIDTerminalRuleCall_4_2_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getIconAlternatives_3_1_0(self) -> org.eclipse.xtext.Alternatives: ...
        def getIconAssignment_3_1(self) -> org.eclipse.xtext.Assignment: ...
        def getIconIDTerminalRuleCall_3_1_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getIconSTRINGTerminalRuleCall_3_1_0_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getLabelAssignment_2(self) -> org.eclipse.xtext.Assignment: ...
        def getLabelSTRINGTerminalRuleCall_2_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getLeftCurlyBracketKeyword_6_0(self) -> org.eclipse.xtext.Keyword: ...
        def getLeftParenthesisKeyword_4_0(self) -> org.eclipse.xtext.Keyword: ...
        def getLeftSquareBracketKeyword_5_0(self) -> org.eclipse.xtext.Keyword: ...
        def getLessThanSignKeyword_3_0(self) -> org.eclipse.xtext.Keyword: ...
        def getModelGroupItemParserRuleCall_0_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getModelNormalItemParserRuleCall_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getNameAssignment_1(self) -> org.eclipse.xtext.Assignment: ...
        def getNameIDTerminalRuleCall_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getRightCurlyBracketKeyword_6_3(self) -> org.eclipse.xtext.Keyword: ...
        def getRightParenthesisKeyword_4_3(self) -> org.eclipse.xtext.Keyword: ...
        def getRightSquareBracketKeyword_5_3(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getTagsAlternatives_5_1_0(self) -> org.eclipse.xtext.Alternatives: ...
        def getTagsAlternatives_5_2_1_0(self) -> org.eclipse.xtext.Alternatives: ...
        def getTagsAssignment_5_1(self) -> org.eclipse.xtext.Assignment: ...
        def getTagsAssignment_5_2_1(self) -> org.eclipse.xtext.Assignment: ...
        def getTagsIDTerminalRuleCall_5_1_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getTagsIDTerminalRuleCall_5_2_1_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getTagsSTRINGTerminalRuleCall_5_1_0_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getTagsSTRINGTerminalRuleCall_5_2_1_0_1(self) -> org.eclipse.xtext.RuleCall: ...
    class ModelItemTypeElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ModelItemTypeElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ModelItemTypeElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getBaseModelItemTypeParserRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getColonKeyword_1_1_0(self) -> org.eclipse.xtext.Keyword: ...
        def getGroup_1(self) -> org.eclipse.xtext.Group: ...
        def getGroup_1_1(self) -> org.eclipse.xtext.Group: ...
        def getIDTerminalRuleCall_1_1_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getNumberKeyword_1_0(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
    class ModelNormalItemElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ModelNormalItemElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ModelNormalItemElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getTypeAssignment(self) -> org.eclipse.xtext.Assignment: ...
        def getTypeModelItemTypeParserRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
    class ModelPropertyElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ModelPropertyElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ModelPropertyElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getEqualsSignKeyword_1(self) -> org.eclipse.xtext.Keyword: ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getKeyAssignment_0(self) -> org.eclipse.xtext.Assignment: ...
        def getKeyIDTerminalRuleCall_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getValueAssignment_2(self) -> org.eclipse.xtext.Assignment: ...
        def getValueValueTypeParserRuleCall_2_0(self) -> org.eclipse.xtext.RuleCall: ...
    class NUMBERElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$NUMBERElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * NUMBERElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getFullStopKeyword_2_0(self) -> org.eclipse.xtext.Keyword: ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getGroup_2(self) -> org.eclipse.xtext.Group: ...
        def getHyphenMinusKeyword_0(self) -> org.eclipse.xtext.Keyword: ...
        def getIDTerminalRuleCall_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getIDTerminalRuleCall_2_1(self) -> org.eclipse.xtext.RuleCall: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
    class ValueTypeElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.services.ItemsGrammarAccess$ValueTypeElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ValueTypeElements(org.openhab.core.model.services.ItemsGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getBOOLEANParserRuleCall_2(self) -> org.eclipse.xtext.RuleCall: ...
        def getNUMBERParserRuleCall_1(self) -> org.eclipse.xtext.RuleCall: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getSTRINGTerminalRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
