import org.eclipse.xtext
import org.eclipse.xtext.service
import org.eclipse.xtext.xbase.services
import typing


class ScriptGrammarAccess(org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder):
    """
    Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess'
    
        Extends:
            org.eclipse.xtext.service.AbstractElementFinder$AbstractGrammarElementFinder
    
      Constructors:
        * ScriptGrammarAccess(org.eclipse.xtext.service.GrammarProvider, org.eclipse.xtext.xbase.services.XbaseGrammarAccess, org.eclipse.xtext.xbase.services.XtypeGrammarAccess)
    
    """
    def __init__(self, grammarProvider: org.eclipse.xtext.service.GrammarProvider, gaXbase: org.eclipse.xtext.xbase.services.XbaseGrammarAccess, gaXtype: org.eclipse.xtext.xbase.services.XtypeGrammarAccess): ...
    def getANY_OTHERRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getAbstractUnitAccess(self) -> 'ScriptGrammarAccess.AbstractUnitElements': ...
    def getAbstractUnitRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getArrayBracketsAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.ArrayBracketsElements: ...
    def getArrayBracketsRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getCOMMON_UNIT_SYMBOLSAccess(self) -> 'ScriptGrammarAccess.COMMON_UNIT_SYMBOLSElements': ...
    def getCOMMON_UNIT_SYMBOLSRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getDECIMALRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getFeatureCallIDAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.FeatureCallIDElements: ...
    def getFeatureCallIDRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getFullJvmFormalParameterAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.FullJvmFormalParameterElements: ...
    def getFullJvmFormalParameterRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getGrammar(self) -> org.eclipse.xtext.Grammar: ...
    def getHEXRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getIDRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getIDUnitAccess(self) -> 'ScriptGrammarAccess.IDUnitElements': ...
    def getIDUnitRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getINTRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getIdOrSuperAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.IdOrSuperElements: ...
    def getIdOrSuperRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmArgumentTypeReferenceAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmArgumentTypeReferenceElements: ...
    def getJvmArgumentTypeReferenceRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmFormalParameterAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.JvmFormalParameterElements: ...
    def getJvmFormalParameterRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmLowerBoundAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmLowerBoundElements: ...
    def getJvmLowerBoundAndedAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmLowerBoundAndedElements: ...
    def getJvmLowerBoundAndedRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmLowerBoundRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmParameterizedTypeReferenceAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmParameterizedTypeReferenceElements: ...
    def getJvmParameterizedTypeReferenceRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmTypeParameterAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmTypeParameterElements: ...
    def getJvmTypeParameterRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmTypeReferenceAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmTypeReferenceElements: ...
    def getJvmTypeReferenceRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmUpperBoundAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmUpperBoundElements: ...
    def getJvmUpperBoundAndedAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmUpperBoundAndedElements: ...
    def getJvmUpperBoundAndedRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmUpperBoundRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getJvmWildcardTypeReferenceAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.JvmWildcardTypeReferenceElements: ...
    def getJvmWildcardTypeReferenceRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getML_COMMENTRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getNumberAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.NumberElements: ...
    def getNumberRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpAddAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpAddElements: ...
    def getOpAddRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpAndAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpAndElements: ...
    def getOpAndRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpCompareAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpCompareElements: ...
    def getOpCompareRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpEqualityAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpEqualityElements: ...
    def getOpEqualityRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpMultiAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpMultiElements: ...
    def getOpMultiAssignAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpMultiAssignElements: ...
    def getOpMultiAssignRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpMultiRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpOrAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpOrElements: ...
    def getOpOrRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpOtherAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpOtherElements: ...
    def getOpOtherRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpPostfixAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpPostfixElements: ...
    def getOpPostfixRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpSingleAssignAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpSingleAssignElements: ...
    def getOpSingleAssignRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getOpUnaryAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.OpUnaryElements: ...
    def getOpUnaryRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getQualifiedNameAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.QualifiedNameElements: ...
    def getQualifiedNameInStaticImportAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.QualifiedNameInStaticImportElements: ...
    def getQualifiedNameInStaticImportRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getQualifiedNameRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getQualifiedNameWithWildcardAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.QualifiedNameWithWildcardElements: ...
    def getQualifiedNameWithWildcardRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getQuantityLiteralAccess(self) -> 'ScriptGrammarAccess.QuantityLiteralElements': ...
    def getQuantityLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getSL_COMMENTRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getSTRINGRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getScriptAccess(self) -> 'ScriptGrammarAccess.ScriptElements': ...
    def getScriptRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getSpecificUnitAccess(self) -> 'ScriptGrammarAccess.SpecificUnitElements': ...
    def getSpecificUnitRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getStaticQualifierAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.StaticQualifierElements: ...
    def getStaticQualifierRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getStringUnitAccess(self) -> 'ScriptGrammarAccess.StringUnitElements': ...
    def getStringUnitRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getValidIDAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.ValidIDElements: ...
    def getValidIDRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getWSRule(self) -> org.eclipse.xtext.TerminalRule: ...
    def getXAdditiveExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XAdditiveExpressionElements: ...
    def getXAdditiveExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXAndExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XAndExpressionElements: ...
    def getXAndExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXAssignmentAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XAssignmentElements: ...
    def getXAssignmentRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXBasicForLoopExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XBasicForLoopExpressionElements: ...
    def getXBasicForLoopExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXBlockExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XBlockExpressionElements: ...
    def getXBlockExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXBooleanLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XBooleanLiteralElements: ...
    def getXBooleanLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXCasePartAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XCasePartElements: ...
    def getXCasePartRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXCastedExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XCastedExpressionElements: ...
    def getXCastedExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXCatchClauseAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XCatchClauseElements: ...
    def getXCatchClauseRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXClosureAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XClosureElements: ...
    def getXClosureRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXCollectionLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XCollectionLiteralElements: ...
    def getXCollectionLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXConstructorCallAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XConstructorCallElements: ...
    def getXConstructorCallRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXDoWhileExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XDoWhileExpressionElements: ...
    def getXDoWhileExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXEqualityExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XEqualityExpressionElements: ...
    def getXEqualityExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XExpressionElements: ...
    def getXExpressionInClosureAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XExpressionInClosureElements: ...
    def getXExpressionInClosureRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXExpressionOrVarDeclarationAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XExpressionOrVarDeclarationElements: ...
    def getXExpressionOrVarDeclarationRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXFeatureCallAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XFeatureCallElements: ...
    def getXFeatureCallRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXForLoopExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XForLoopExpressionElements: ...
    def getXForLoopExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXFunctionTypeRefAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.XFunctionTypeRefElements: ...
    def getXFunctionTypeRefRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXIfExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XIfExpressionElements: ...
    def getXIfExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXImportDeclarationAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.XImportDeclarationElements: ...
    def getXImportDeclarationRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXImportSectionAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess.XImportSectionElements: ...
    def getXImportSectionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXListLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XListLiteralElements: ...
    def getXListLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXLiteralAccess(self) -> 'ScriptGrammarAccess.XLiteralElements': ...
    def getXLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXMemberFeatureCallAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XMemberFeatureCallElements: ...
    def getXMemberFeatureCallRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXMultiplicativeExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XMultiplicativeExpressionElements: ...
    def getXMultiplicativeExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXNullLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XNullLiteralElements: ...
    def getXNullLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXNumberLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XNumberLiteralElements: ...
    def getXNumberLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXOrExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XOrExpressionElements: ...
    def getXOrExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXOtherOperatorExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XOtherOperatorExpressionElements: ...
    def getXOtherOperatorExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXParenthesizedExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XParenthesizedExpressionElements: ...
    def getXParenthesizedExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXPostfixOperationAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XPostfixOperationElements: ...
    def getXPostfixOperationRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXPrimaryExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XPrimaryExpressionElements: ...
    def getXPrimaryExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXRelationalExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XRelationalExpressionElements: ...
    def getXRelationalExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXReturnExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XReturnExpressionElements: ...
    def getXReturnExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXSetLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XSetLiteralElements: ...
    def getXSetLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXShortClosureAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XShortClosureElements: ...
    def getXShortClosureRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXStringLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XStringLiteralElements: ...
    def getXStringLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXSwitchExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XSwitchExpressionElements: ...
    def getXSwitchExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXSynchronizedExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XSynchronizedExpressionElements: ...
    def getXSynchronizedExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXThrowExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XThrowExpressionElements: ...
    def getXThrowExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXTryCatchFinallyExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XTryCatchFinallyExpressionElements: ...
    def getXTryCatchFinallyExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXTypeLiteralAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XTypeLiteralElements: ...
    def getXTypeLiteralRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXUnaryOperationAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XUnaryOperationElements: ...
    def getXUnaryOperationRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXVariableDeclarationAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XVariableDeclarationElements: ...
    def getXVariableDeclarationRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXWhileExpressionAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess.XWhileExpressionElements: ...
    def getXWhileExpressionRule(self) -> org.eclipse.xtext.ParserRule: ...
    def getXbaseGrammarAccess(self) -> org.eclipse.xtext.xbase.services.XbaseGrammarAccess: ...
    def getXtypeGrammarAccess(self) -> org.eclipse.xtext.xbase.services.XtypeGrammarAccess: ...
    class AbstractUnitElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$AbstractUnitElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * AbstractUnitElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getIDUnitParserRuleCall_1(self) -> org.eclipse.xtext.RuleCall: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getSpecificUnitParserRuleCall_2(self) -> org.eclipse.xtext.RuleCall: ...
        def getStringUnitParserRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
    class COMMON_UNIT_SYMBOLSElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$COMMON_UNIT_SYMBOLSElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * COMMON_UNIT_SYMBOLSElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getCKeyword_0(self) -> org.eclipse.xtext.Keyword: ...
        def getDegreeCelsiusKeyword_3(self) -> org.eclipse.xtext.Keyword: ...
        def getDegreeSignKeyword_4(self) -> org.eclipse.xtext.Keyword: ...
        def getFKeyword_1(self) -> org.eclipse.xtext.Keyword: ...
        def getGreekCapitalLetterOmegaKeyword_2(self) -> org.eclipse.xtext.Keyword: ...
        def getMKeyword_6(self) -> org.eclipse.xtext.Keyword: ...
        def getMKeyword_7(self) -> org.eclipse.xtext.Keyword: ...
        def getPercentSignKeyword_5(self) -> org.eclipse.xtext.Keyword: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
    class IDUnitElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$IDUnitElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * IDUnitElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getValueAssignment(self) -> org.eclipse.xtext.Assignment: ...
        def getValueIDTerminalRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
    class QuantityLiteralElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$QuantityLiteralElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * QuantityLiteralElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getQuantityLiteralAction_0(self) -> org.eclipse.xtext.Action: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getUnitAbstractUnitParserRuleCall_3_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getUnitAssignment_3(self) -> org.eclipse.xtext.Assignment: ...
        def getValueAssignment_1(self) -> org.eclipse.xtext.Assignment: ...
        def getValueNumberParserRuleCall_1_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getVerticalLineKeyword_2(self) -> org.eclipse.xtext.Keyword: ...
    class ScriptElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$ScriptElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * ScriptElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        def getExpressionsAssignment_1_0(self) -> org.eclipse.xtext.Assignment: ...
        def getExpressionsXExpressionOrVarDeclarationParserRuleCall_1_0_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getGroup(self) -> org.eclipse.xtext.Group: ...
        def getGroup_1(self) -> org.eclipse.xtext.Group: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getScriptAction_0(self) -> org.eclipse.xtext.Action: ...
        def getSemicolonKeyword_1_1(self) -> org.eclipse.xtext.Keyword: ...
    class SpecificUnitElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$SpecificUnitElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * SpecificUnitElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getValueAssignment(self) -> org.eclipse.xtext.Assignment: ...
        def getValueCOMMON_UNIT_SYMBOLSParserRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
    class StringUnitElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$StringUnitElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * StringUnitElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getValueAssignment(self) -> org.eclipse.xtext.Assignment: ...
        def getValueSTRINGTerminalRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
    class XLiteralElements(org.eclipse.xtext.service.AbstractElementFinder.AbstractParserRuleElementFinder):
        """
        Java class 'org.openhab.core.model.script.services.ScriptGrammarAccess$XLiteralElements'
        
            Extends:
                org.eclipse.xtext.service.AbstractElementFinder$AbstractParserRuleElementFinder
        
          Constructors:
            * XLiteralElements(org.openhab.core.model.script.services.ScriptGrammarAccess)
        
        """
        def __init__(self): ...
        def getAlternatives(self) -> org.eclipse.xtext.Alternatives: ...
        def getQuantityLiteralParserRuleCall_6(self) -> org.eclipse.xtext.RuleCall: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.AbstractRule: ...
        @typing.overload
        def getRule(self) -> org.eclipse.xtext.ParserRule: ...
        def getXBooleanLiteralParserRuleCall_1(self) -> org.eclipse.xtext.RuleCall: ...
        def getXClosureParserRuleCall_0(self) -> org.eclipse.xtext.RuleCall: ...
        def getXNullLiteralParserRuleCall_2(self) -> org.eclipse.xtext.RuleCall: ...
        def getXNumberLiteralParserRuleCall_4(self) -> org.eclipse.xtext.RuleCall: ...
        def getXStringLiteralParserRuleCall_3(self) -> org.eclipse.xtext.RuleCall: ...
        def getXTypeLiteralParserRuleCall_5(self) -> org.eclipse.xtext.RuleCall: ...
