import java.lang
import org.antlr.runtime
import org.eclipse.emf.ecore
import org.eclipse.xtext.parser.antlr
import org.openhab.core.model.script.services
import typing


class InternalScriptLexer(org.eclipse.xtext.parser.antlr.Lexer):
    """
    Java class 'org.openhab.core.model.script.parser.antlr.internal.InternalScriptLexer'
    
        Extends:
            org.eclipse.xtext.parser.antlr.Lexer
    
      Constructors:
        * InternalScriptLexer(org.antlr.runtime.CharStream)
        * InternalScriptLexer()
        * InternalScriptLexer(org.antlr.runtime.CharStream, org.antlr.runtime.RecognizerSharedState)
    
      Attributes:
        RULE_HEX (int): final static field
        T__50 (int): final static field
        T__59 (int): final static field
        T__55 (int): final static field
        T__56 (int): final static field
        T__57 (int): final static field
        T__58 (int): final static field
        T__51 (int): final static field
        T__52 (int): final static field
        T__53 (int): final static field
        T__54 (int): final static field
        T__60 (int): final static field
        T__61 (int): final static field
        RULE_ID (int): final static field
        RULE_INT (int): final static field
        T__66 (int): final static field
        RULE_ML_COMMENT (int): final static field
        T__67 (int): final static field
        T__68 (int): final static field
        T__69 (int): final static field
        T__62 (int): final static field
        T__63 (int): final static field
        T__64 (int): final static field
        T__65 (int): final static field
        T__37 (int): final static field
        T__38 (int): final static field
        T__39 (int): final static field
        T__33 (int): final static field
        T__34 (int): final static field
        T__35 (int): final static field
        T__36 (int): final static field
        T__30 (int): final static field
        T__31 (int): final static field
        T__32 (int): final static field
        T__48 (int): final static field
        T__49 (int): final static field
        T__44 (int): final static field
        T__45 (int): final static field
        T__46 (int): final static field
        T__47 (int): final static field
        T__40 (int): final static field
        T__41 (int): final static field
        T__42 (int): final static field
        T__43 (int): final static field
        T__91 (int): final static field
        T__92 (int): final static field
        T__93 (int): final static field
        T__90 (int): final static field
        T__19 (int): final static field
        T__15 (int): final static field
        T__16 (int): final static field
        T__17 (int): final static field
        T__18 (int): final static field
        T__13 (int): final static field
        T__14 (int): final static field
        RULE_DECIMAL (int): final static field
        T__26 (int): final static field
        T__27 (int): final static field
        T__28 (int): final static field
        T__29 (int): final static field
        T__22 (int): final static field
        T__23 (int): final static field
        T__24 (int): final static field
        T__25 (int): final static field
        T__20 (int): final static field
        T__21 (int): final static field
        T__70 (int): final static field
        T__71 (int): final static field
        T__72 (int): final static field
        RULE_STRING (int): final static field
        RULE_SL_COMMENT (int): final static field
        T__77 (int): final static field
        T__78 (int): final static field
        T__79 (int): final static field
        T__73 (int): final static field
        EOF (int): final static field
        T__74 (int): final static field
        T__75 (int): final static field
        T__76 (int): final static field
        T__80 (int): final static field
        T__81 (int): final static field
        T__82 (int): final static field
        T__83 (int): final static field
        RULE_WS (int): final static field
        RULE_ANY_OTHER (int): final static field
        T__88 (int): final static field
        T__89 (int): final static field
        T__84 (int): final static field
        T__85 (int): final static field
        T__86 (int): final static field
        T__87 (int): final static field
    
    """
    RULE_HEX: typing.ClassVar[int] = ...
    T__50: typing.ClassVar[int] = ...
    T__59: typing.ClassVar[int] = ...
    T__55: typing.ClassVar[int] = ...
    T__56: typing.ClassVar[int] = ...
    T__57: typing.ClassVar[int] = ...
    T__58: typing.ClassVar[int] = ...
    T__51: typing.ClassVar[int] = ...
    T__52: typing.ClassVar[int] = ...
    T__53: typing.ClassVar[int] = ...
    T__54: typing.ClassVar[int] = ...
    T__60: typing.ClassVar[int] = ...
    T__61: typing.ClassVar[int] = ...
    RULE_ID: typing.ClassVar[int] = ...
    RULE_INT: typing.ClassVar[int] = ...
    T__66: typing.ClassVar[int] = ...
    RULE_ML_COMMENT: typing.ClassVar[int] = ...
    T__67: typing.ClassVar[int] = ...
    T__68: typing.ClassVar[int] = ...
    T__69: typing.ClassVar[int] = ...
    T__62: typing.ClassVar[int] = ...
    T__63: typing.ClassVar[int] = ...
    T__64: typing.ClassVar[int] = ...
    T__65: typing.ClassVar[int] = ...
    T__37: typing.ClassVar[int] = ...
    T__38: typing.ClassVar[int] = ...
    T__39: typing.ClassVar[int] = ...
    T__33: typing.ClassVar[int] = ...
    T__34: typing.ClassVar[int] = ...
    T__35: typing.ClassVar[int] = ...
    T__36: typing.ClassVar[int] = ...
    T__30: typing.ClassVar[int] = ...
    T__31: typing.ClassVar[int] = ...
    T__32: typing.ClassVar[int] = ...
    T__48: typing.ClassVar[int] = ...
    T__49: typing.ClassVar[int] = ...
    T__44: typing.ClassVar[int] = ...
    T__45: typing.ClassVar[int] = ...
    T__46: typing.ClassVar[int] = ...
    T__47: typing.ClassVar[int] = ...
    T__40: typing.ClassVar[int] = ...
    T__41: typing.ClassVar[int] = ...
    T__42: typing.ClassVar[int] = ...
    T__43: typing.ClassVar[int] = ...
    T__91: typing.ClassVar[int] = ...
    T__92: typing.ClassVar[int] = ...
    T__93: typing.ClassVar[int] = ...
    T__90: typing.ClassVar[int] = ...
    T__19: typing.ClassVar[int] = ...
    T__15: typing.ClassVar[int] = ...
    T__16: typing.ClassVar[int] = ...
    T__17: typing.ClassVar[int] = ...
    T__18: typing.ClassVar[int] = ...
    T__13: typing.ClassVar[int] = ...
    T__14: typing.ClassVar[int] = ...
    RULE_DECIMAL: typing.ClassVar[int] = ...
    T__26: typing.ClassVar[int] = ...
    T__27: typing.ClassVar[int] = ...
    T__28: typing.ClassVar[int] = ...
    T__29: typing.ClassVar[int] = ...
    T__22: typing.ClassVar[int] = ...
    T__23: typing.ClassVar[int] = ...
    T__24: typing.ClassVar[int] = ...
    T__25: typing.ClassVar[int] = ...
    T__20: typing.ClassVar[int] = ...
    T__21: typing.ClassVar[int] = ...
    T__70: typing.ClassVar[int] = ...
    T__71: typing.ClassVar[int] = ...
    T__72: typing.ClassVar[int] = ...
    RULE_STRING: typing.ClassVar[int] = ...
    RULE_SL_COMMENT: typing.ClassVar[int] = ...
    T__77: typing.ClassVar[int] = ...
    T__78: typing.ClassVar[int] = ...
    T__79: typing.ClassVar[int] = ...
    T__73: typing.ClassVar[int] = ...
    EOF: typing.ClassVar[int] = ...
    T__74: typing.ClassVar[int] = ...
    T__75: typing.ClassVar[int] = ...
    T__76: typing.ClassVar[int] = ...
    T__80: typing.ClassVar[int] = ...
    T__81: typing.ClassVar[int] = ...
    T__82: typing.ClassVar[int] = ...
    T__83: typing.ClassVar[int] = ...
    RULE_WS: typing.ClassVar[int] = ...
    RULE_ANY_OTHER: typing.ClassVar[int] = ...
    T__88: typing.ClassVar[int] = ...
    T__89: typing.ClassVar[int] = ...
    T__84: typing.ClassVar[int] = ...
    T__85: typing.ClassVar[int] = ...
    T__86: typing.ClassVar[int] = ...
    T__87: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.CharStream): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.CharStream, state: org.antlr.runtime.RecognizerSharedState): ...
    def getGrammarFileName(self) -> java.lang.String: ...
    def mRULE_ANY_OTHER(self) -> None: ...
    def mRULE_DECIMAL(self) -> None: ...
    def mRULE_HEX(self) -> None: ...
    def mRULE_ID(self) -> None: ...
    def mRULE_INT(self) -> None: ...
    def mRULE_ML_COMMENT(self) -> None: ...
    def mRULE_SL_COMMENT(self) -> None: ...
    def mRULE_STRING(self) -> None: ...
    def mRULE_WS(self) -> None: ...
    def mT__13(self) -> None: ...
    def mT__14(self) -> None: ...
    def mT__15(self) -> None: ...
    def mT__16(self) -> None: ...
    def mT__17(self) -> None: ...
    def mT__18(self) -> None: ...
    def mT__19(self) -> None: ...
    def mT__20(self) -> None: ...
    def mT__21(self) -> None: ...
    def mT__22(self) -> None: ...
    def mT__23(self) -> None: ...
    def mT__24(self) -> None: ...
    def mT__25(self) -> None: ...
    def mT__26(self) -> None: ...
    def mT__27(self) -> None: ...
    def mT__28(self) -> None: ...
    def mT__29(self) -> None: ...
    def mT__30(self) -> None: ...
    def mT__31(self) -> None: ...
    def mT__32(self) -> None: ...
    def mT__33(self) -> None: ...
    def mT__34(self) -> None: ...
    def mT__35(self) -> None: ...
    def mT__36(self) -> None: ...
    def mT__37(self) -> None: ...
    def mT__38(self) -> None: ...
    def mT__39(self) -> None: ...
    def mT__40(self) -> None: ...
    def mT__41(self) -> None: ...
    def mT__42(self) -> None: ...
    def mT__43(self) -> None: ...
    def mT__44(self) -> None: ...
    def mT__45(self) -> None: ...
    def mT__46(self) -> None: ...
    def mT__47(self) -> None: ...
    def mT__48(self) -> None: ...
    def mT__49(self) -> None: ...
    def mT__50(self) -> None: ...
    def mT__51(self) -> None: ...
    def mT__52(self) -> None: ...
    def mT__53(self) -> None: ...
    def mT__54(self) -> None: ...
    def mT__55(self) -> None: ...
    def mT__56(self) -> None: ...
    def mT__57(self) -> None: ...
    def mT__58(self) -> None: ...
    def mT__59(self) -> None: ...
    def mT__60(self) -> None: ...
    def mT__61(self) -> None: ...
    def mT__62(self) -> None: ...
    def mT__63(self) -> None: ...
    def mT__64(self) -> None: ...
    def mT__65(self) -> None: ...
    def mT__66(self) -> None: ...
    def mT__67(self) -> None: ...
    def mT__68(self) -> None: ...
    def mT__69(self) -> None: ...
    def mT__70(self) -> None: ...
    def mT__71(self) -> None: ...
    def mT__72(self) -> None: ...
    def mT__73(self) -> None: ...
    def mT__74(self) -> None: ...
    def mT__75(self) -> None: ...
    def mT__76(self) -> None: ...
    def mT__77(self) -> None: ...
    def mT__78(self) -> None: ...
    def mT__79(self) -> None: ...
    def mT__80(self) -> None: ...
    def mT__81(self) -> None: ...
    def mT__82(self) -> None: ...
    def mT__83(self) -> None: ...
    def mT__84(self) -> None: ...
    def mT__85(self) -> None: ...
    def mT__86(self) -> None: ...
    def mT__87(self) -> None: ...
    def mT__88(self) -> None: ...
    def mT__89(self) -> None: ...
    def mT__90(self) -> None: ...
    def mT__91(self) -> None: ...
    def mT__92(self) -> None: ...
    def mT__93(self) -> None: ...
    def mTokens(self) -> None: ...

class InternalScriptParser(org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser):
    """
    Java class 'org.openhab.core.model.script.parser.antlr.internal.InternalScriptParser'
    
        Extends:
            org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser
    
      Constructors:
        * InternalScriptParser(org.antlr.runtime.TokenStream, org.openhab.core.model.script.services.ScriptGrammarAccess)
        * InternalScriptParser(org.antlr.runtime.TokenStream)
        * InternalScriptParser(org.antlr.runtime.TokenStream, org.antlr.runtime.RecognizerSharedState)
    
      Attributes:
        tokenNames ([Ljava.lang.String;): final static field
        RULE_HEX (int): final static field
        T__50 (int): final static field
        T__59 (int): final static field
        T__55 (int): final static field
        T__56 (int): final static field
        T__57 (int): final static field
        T__58 (int): final static field
        T__51 (int): final static field
        T__52 (int): final static field
        T__53 (int): final static field
        T__54 (int): final static field
        T__60 (int): final static field
        T__61 (int): final static field
        RULE_ID (int): final static field
        RULE_INT (int): final static field
        T__66 (int): final static field
        RULE_ML_COMMENT (int): final static field
        T__67 (int): final static field
        T__68 (int): final static field
        T__69 (int): final static field
        T__62 (int): final static field
        T__63 (int): final static field
        T__64 (int): final static field
        T__65 (int): final static field
        T__37 (int): final static field
        T__38 (int): final static field
        T__39 (int): final static field
        T__33 (int): final static field
        T__34 (int): final static field
        T__35 (int): final static field
        T__36 (int): final static field
        T__30 (int): final static field
        T__31 (int): final static field
        T__32 (int): final static field
        T__48 (int): final static field
        T__49 (int): final static field
        T__44 (int): final static field
        T__45 (int): final static field
        T__46 (int): final static field
        T__47 (int): final static field
        T__40 (int): final static field
        T__41 (int): final static field
        T__42 (int): final static field
        T__43 (int): final static field
        T__91 (int): final static field
        T__92 (int): final static field
        T__93 (int): final static field
        T__90 (int): final static field
        T__19 (int): final static field
        T__15 (int): final static field
        T__16 (int): final static field
        T__17 (int): final static field
        T__18 (int): final static field
        T__13 (int): final static field
        T__14 (int): final static field
        RULE_DECIMAL (int): final static field
        T__26 (int): final static field
        T__27 (int): final static field
        T__28 (int): final static field
        T__29 (int): final static field
        T__22 (int): final static field
        T__23 (int): final static field
        T__24 (int): final static field
        T__25 (int): final static field
        T__20 (int): final static field
        T__21 (int): final static field
        T__70 (int): final static field
        T__71 (int): final static field
        T__72 (int): final static field
        RULE_STRING (int): final static field
        RULE_SL_COMMENT (int): final static field
        T__77 (int): final static field
        T__78 (int): final static field
        T__79 (int): final static field
        T__73 (int): final static field
        EOF (int): final static field
        T__74 (int): final static field
        T__75 (int): final static field
        T__76 (int): final static field
        T__80 (int): final static field
        T__81 (int): final static field
        T__82 (int): final static field
        T__83 (int): final static field
        RULE_WS (int): final static field
        RULE_ANY_OTHER (int): final static field
        T__88 (int): final static field
        T__89 (int): final static field
        T__84 (int): final static field
        T__85 (int): final static field
        T__86 (int): final static field
        T__87 (int): final static field
        FOLLOW_1 (org.antlr.runtime.BitSet): final static field
        FOLLOW_2 (org.antlr.runtime.BitSet): final static field
        FOLLOW_3 (org.antlr.runtime.BitSet): final static field
        FOLLOW_4 (org.antlr.runtime.BitSet): final static field
        FOLLOW_5 (org.antlr.runtime.BitSet): final static field
        FOLLOW_6 (org.antlr.runtime.BitSet): final static field
        FOLLOW_7 (org.antlr.runtime.BitSet): final static field
        FOLLOW_8 (org.antlr.runtime.BitSet): final static field
        FOLLOW_9 (org.antlr.runtime.BitSet): final static field
        FOLLOW_10 (org.antlr.runtime.BitSet): final static field
        FOLLOW_11 (org.antlr.runtime.BitSet): final static field
        FOLLOW_12 (org.antlr.runtime.BitSet): final static field
        FOLLOW_13 (org.antlr.runtime.BitSet): final static field
        FOLLOW_14 (org.antlr.runtime.BitSet): final static field
        FOLLOW_15 (org.antlr.runtime.BitSet): final static field
        FOLLOW_16 (org.antlr.runtime.BitSet): final static field
        FOLLOW_17 (org.antlr.runtime.BitSet): final static field
        FOLLOW_18 (org.antlr.runtime.BitSet): final static field
        FOLLOW_19 (org.antlr.runtime.BitSet): final static field
        FOLLOW_20 (org.antlr.runtime.BitSet): final static field
        FOLLOW_21 (org.antlr.runtime.BitSet): final static field
        FOLLOW_22 (org.antlr.runtime.BitSet): final static field
        FOLLOW_23 (org.antlr.runtime.BitSet): final static field
        FOLLOW_24 (org.antlr.runtime.BitSet): final static field
        FOLLOW_25 (org.antlr.runtime.BitSet): final static field
        FOLLOW_26 (org.antlr.runtime.BitSet): final static field
        FOLLOW_27 (org.antlr.runtime.BitSet): final static field
        FOLLOW_28 (org.antlr.runtime.BitSet): final static field
        FOLLOW_29 (org.antlr.runtime.BitSet): final static field
        FOLLOW_30 (org.antlr.runtime.BitSet): final static field
        FOLLOW_31 (org.antlr.runtime.BitSet): final static field
        FOLLOW_32 (org.antlr.runtime.BitSet): final static field
        FOLLOW_33 (org.antlr.runtime.BitSet): final static field
        FOLLOW_34 (org.antlr.runtime.BitSet): final static field
        FOLLOW_35 (org.antlr.runtime.BitSet): final static field
        FOLLOW_36 (org.antlr.runtime.BitSet): final static field
        FOLLOW_37 (org.antlr.runtime.BitSet): final static field
        FOLLOW_38 (org.antlr.runtime.BitSet): final static field
        FOLLOW_39 (org.antlr.runtime.BitSet): final static field
        FOLLOW_40 (org.antlr.runtime.BitSet): final static field
        FOLLOW_41 (org.antlr.runtime.BitSet): final static field
        FOLLOW_42 (org.antlr.runtime.BitSet): final static field
        FOLLOW_43 (org.antlr.runtime.BitSet): final static field
        FOLLOW_44 (org.antlr.runtime.BitSet): final static field
        FOLLOW_45 (org.antlr.runtime.BitSet): final static field
        FOLLOW_46 (org.antlr.runtime.BitSet): final static field
        FOLLOW_47 (org.antlr.runtime.BitSet): final static field
        FOLLOW_48 (org.antlr.runtime.BitSet): final static field
        FOLLOW_49 (org.antlr.runtime.BitSet): final static field
        FOLLOW_50 (org.antlr.runtime.BitSet): final static field
        FOLLOW_51 (org.antlr.runtime.BitSet): final static field
        FOLLOW_52 (org.antlr.runtime.BitSet): final static field
        FOLLOW_53 (org.antlr.runtime.BitSet): final static field
        FOLLOW_54 (org.antlr.runtime.BitSet): final static field
        FOLLOW_55 (org.antlr.runtime.BitSet): final static field
        FOLLOW_56 (org.antlr.runtime.BitSet): final static field
        FOLLOW_57 (org.antlr.runtime.BitSet): final static field
        FOLLOW_58 (org.antlr.runtime.BitSet): final static field
        FOLLOW_59 (org.antlr.runtime.BitSet): final static field
        FOLLOW_60 (org.antlr.runtime.BitSet): final static field
        FOLLOW_61 (org.antlr.runtime.BitSet): final static field
        FOLLOW_62 (org.antlr.runtime.BitSet): final static field
        FOLLOW_63 (org.antlr.runtime.BitSet): final static field
        FOLLOW_64 (org.antlr.runtime.BitSet): final static field
        FOLLOW_65 (org.antlr.runtime.BitSet): final static field
        FOLLOW_66 (org.antlr.runtime.BitSet): final static field
        FOLLOW_67 (org.antlr.runtime.BitSet): final static field
        FOLLOW_68 (org.antlr.runtime.BitSet): final static field
        FOLLOW_69 (org.antlr.runtime.BitSet): final static field
        FOLLOW_70 (org.antlr.runtime.BitSet): final static field
        FOLLOW_71 (org.antlr.runtime.BitSet): final static field
        FOLLOW_72 (org.antlr.runtime.BitSet): final static field
        FOLLOW_73 (org.antlr.runtime.BitSet): final static field
        FOLLOW_74 (org.antlr.runtime.BitSet): final static field
        FOLLOW_75 (org.antlr.runtime.BitSet): final static field
        FOLLOW_76 (org.antlr.runtime.BitSet): final static field
        FOLLOW_77 (org.antlr.runtime.BitSet): final static field
        FOLLOW_78 (org.antlr.runtime.BitSet): final static field
        FOLLOW_79 (org.antlr.runtime.BitSet): final static field
        FOLLOW_80 (org.antlr.runtime.BitSet): final static field
        FOLLOW_81 (org.antlr.runtime.BitSet): final static field
        FOLLOW_82 (org.antlr.runtime.BitSet): final static field
        FOLLOW_83 (org.antlr.runtime.BitSet): final static field
        FOLLOW_84 (org.antlr.runtime.BitSet): final static field
        FOLLOW_85 (org.antlr.runtime.BitSet): final static field
        FOLLOW_86 (org.antlr.runtime.BitSet): final static field
        FOLLOW_87 (org.antlr.runtime.BitSet): final static field
        FOLLOW_88 (org.antlr.runtime.BitSet): final static field
        FOLLOW_89 (org.antlr.runtime.BitSet): final static field
        FOLLOW_90 (org.antlr.runtime.BitSet): final static field
        FOLLOW_91 (org.antlr.runtime.BitSet): final static field
    
    """
    tokenNames: typing.ClassVar[typing.List[java.lang.String]] = ...
    RULE_HEX: typing.ClassVar[int] = ...
    T__50: typing.ClassVar[int] = ...
    T__59: typing.ClassVar[int] = ...
    T__55: typing.ClassVar[int] = ...
    T__56: typing.ClassVar[int] = ...
    T__57: typing.ClassVar[int] = ...
    T__58: typing.ClassVar[int] = ...
    T__51: typing.ClassVar[int] = ...
    T__52: typing.ClassVar[int] = ...
    T__53: typing.ClassVar[int] = ...
    T__54: typing.ClassVar[int] = ...
    T__60: typing.ClassVar[int] = ...
    T__61: typing.ClassVar[int] = ...
    RULE_ID: typing.ClassVar[int] = ...
    RULE_INT: typing.ClassVar[int] = ...
    T__66: typing.ClassVar[int] = ...
    RULE_ML_COMMENT: typing.ClassVar[int] = ...
    T__67: typing.ClassVar[int] = ...
    T__68: typing.ClassVar[int] = ...
    T__69: typing.ClassVar[int] = ...
    T__62: typing.ClassVar[int] = ...
    T__63: typing.ClassVar[int] = ...
    T__64: typing.ClassVar[int] = ...
    T__65: typing.ClassVar[int] = ...
    T__37: typing.ClassVar[int] = ...
    T__38: typing.ClassVar[int] = ...
    T__39: typing.ClassVar[int] = ...
    T__33: typing.ClassVar[int] = ...
    T__34: typing.ClassVar[int] = ...
    T__35: typing.ClassVar[int] = ...
    T__36: typing.ClassVar[int] = ...
    T__30: typing.ClassVar[int] = ...
    T__31: typing.ClassVar[int] = ...
    T__32: typing.ClassVar[int] = ...
    T__48: typing.ClassVar[int] = ...
    T__49: typing.ClassVar[int] = ...
    T__44: typing.ClassVar[int] = ...
    T__45: typing.ClassVar[int] = ...
    T__46: typing.ClassVar[int] = ...
    T__47: typing.ClassVar[int] = ...
    T__40: typing.ClassVar[int] = ...
    T__41: typing.ClassVar[int] = ...
    T__42: typing.ClassVar[int] = ...
    T__43: typing.ClassVar[int] = ...
    T__91: typing.ClassVar[int] = ...
    T__92: typing.ClassVar[int] = ...
    T__93: typing.ClassVar[int] = ...
    T__90: typing.ClassVar[int] = ...
    T__19: typing.ClassVar[int] = ...
    T__15: typing.ClassVar[int] = ...
    T__16: typing.ClassVar[int] = ...
    T__17: typing.ClassVar[int] = ...
    T__18: typing.ClassVar[int] = ...
    T__13: typing.ClassVar[int] = ...
    T__14: typing.ClassVar[int] = ...
    RULE_DECIMAL: typing.ClassVar[int] = ...
    T__26: typing.ClassVar[int] = ...
    T__27: typing.ClassVar[int] = ...
    T__28: typing.ClassVar[int] = ...
    T__29: typing.ClassVar[int] = ...
    T__22: typing.ClassVar[int] = ...
    T__23: typing.ClassVar[int] = ...
    T__24: typing.ClassVar[int] = ...
    T__25: typing.ClassVar[int] = ...
    T__20: typing.ClassVar[int] = ...
    T__21: typing.ClassVar[int] = ...
    T__70: typing.ClassVar[int] = ...
    T__71: typing.ClassVar[int] = ...
    T__72: typing.ClassVar[int] = ...
    RULE_STRING: typing.ClassVar[int] = ...
    RULE_SL_COMMENT: typing.ClassVar[int] = ...
    T__77: typing.ClassVar[int] = ...
    T__78: typing.ClassVar[int] = ...
    T__79: typing.ClassVar[int] = ...
    T__73: typing.ClassVar[int] = ...
    EOF: typing.ClassVar[int] = ...
    T__74: typing.ClassVar[int] = ...
    T__75: typing.ClassVar[int] = ...
    T__76: typing.ClassVar[int] = ...
    T__80: typing.ClassVar[int] = ...
    T__81: typing.ClassVar[int] = ...
    T__82: typing.ClassVar[int] = ...
    T__83: typing.ClassVar[int] = ...
    RULE_WS: typing.ClassVar[int] = ...
    RULE_ANY_OTHER: typing.ClassVar[int] = ...
    T__88: typing.ClassVar[int] = ...
    T__89: typing.ClassVar[int] = ...
    T__84: typing.ClassVar[int] = ...
    T__85: typing.ClassVar[int] = ...
    T__86: typing.ClassVar[int] = ...
    T__87: typing.ClassVar[int] = ...
    FOLLOW_1: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_2: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_3: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_4: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_5: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_6: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_7: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_8: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_9: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_10: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_11: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_12: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_13: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_14: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_15: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_16: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_17: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_18: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_19: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_20: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_21: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_22: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_23: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_24: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_25: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_26: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_27: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_28: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_29: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_30: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_31: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_32: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_33: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_34: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_35: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_36: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_37: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_38: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_39: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_40: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_41: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_42: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_43: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_44: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_45: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_46: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_47: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_48: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_49: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_50: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_51: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_52: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_53: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_54: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_55: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_56: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_57: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_58: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_59: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_60: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_61: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_62: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_63: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_64: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_65: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_66: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_67: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_68: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_69: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_70: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_71: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_72: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_73: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_74: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_75: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_76: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_77: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_78: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_79: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_80: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_81: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_82: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_83: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_84: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_85: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_86: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_87: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_88: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_89: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_90: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_91: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.TokenStream): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.TokenStream, state: org.antlr.runtime.RecognizerSharedState): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.TokenStream, grammarAccess: org.openhab.core.model.script.services.ScriptGrammarAccess): ...
    def entryRuleAbstractUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleArrayBrackets(self) -> java.lang.String: ...
    def entryRuleCOMMON_UNIT_SYMBOLS(self) -> java.lang.String: ...
    def entryRuleFeatureCallID(self) -> java.lang.String: ...
    def entryRuleFullJvmFormalParameter(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleIDUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleIdOrSuper(self) -> java.lang.String: ...
    def entryRuleJvmArgumentTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmFormalParameter(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmLowerBound(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmLowerBoundAnded(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmParameterizedTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmUpperBound(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmUpperBoundAnded(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleJvmWildcardTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleNumber(self) -> java.lang.String: ...
    def entryRuleOpAdd(self) -> java.lang.String: ...
    def entryRuleOpAnd(self) -> java.lang.String: ...
    def entryRuleOpCompare(self) -> java.lang.String: ...
    def entryRuleOpEquality(self) -> java.lang.String: ...
    def entryRuleOpMulti(self) -> java.lang.String: ...
    def entryRuleOpMultiAssign(self) -> java.lang.String: ...
    def entryRuleOpOr(self) -> java.lang.String: ...
    def entryRuleOpOther(self) -> java.lang.String: ...
    def entryRuleOpPostfix(self) -> java.lang.String: ...
    def entryRuleOpSingleAssign(self) -> java.lang.String: ...
    def entryRuleOpUnary(self) -> java.lang.String: ...
    def entryRuleQualifiedName(self) -> java.lang.String: ...
    def entryRuleQualifiedNameInStaticImport(self) -> java.lang.String: ...
    def entryRuleQualifiedNameWithWildcard(self) -> java.lang.String: ...
    def entryRuleQuantityLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleScript(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleSpecificUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleStringUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleValidID(self) -> java.lang.String: ...
    def entryRuleXAdditiveExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXAndExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXAssignment(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXBasicForLoopExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXBlockExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXBooleanLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXCasePart(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXCastedExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXCatchClause(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXClosure(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXConstructorCall(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXDoWhileExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXEqualityExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXExpressionInClosure(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXExpressionOrVarDeclaration(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXFeatureCall(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXForLoopExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXFunctionTypeRef(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXIfExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXImportDeclaration(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXListLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXMemberFeatureCall(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXMultiplicativeExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXNullLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXNumberLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXOrExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXOtherOperatorExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXParenthesizedExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXPostfixOperation(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXPrimaryExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXRelationalExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXReturnExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXSetLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXShortClosure(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXStringLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXSwitchExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXSynchronizedExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXThrowExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXTryCatchFinallyExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXTypeLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXUnaryOperation(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXVariableDeclaration(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXWhileExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def getGrammarFileName(self) -> java.lang.String: ...
    def getTokenNames(self) -> typing.List[java.lang.String]: ...
    def ruleAbstractUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleArrayBrackets(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleCOMMON_UNIT_SYMBOLS(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleFeatureCallID(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleFullJvmFormalParameter(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleIDUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleIdOrSuper(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleJvmArgumentTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmFormalParameter(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmLowerBound(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmLowerBoundAnded(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmParameterizedTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmUpperBound(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmUpperBoundAnded(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleJvmWildcardTypeReference(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleNumber(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpAdd(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpAnd(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpCompare(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpEquality(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpMulti(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpMultiAssign(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpOr(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpOther(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpPostfix(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpSingleAssign(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleOpUnary(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleQualifiedName(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleQualifiedNameInStaticImport(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleQualifiedNameWithWildcard(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleQuantityLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleScript(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleSpecificUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleStringUnit(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleValidID(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleXAdditiveExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXAndExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXAssignment(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXBasicForLoopExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXBlockExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXBooleanLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXCasePart(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXCastedExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXCatchClause(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXClosure(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXConstructorCall(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXDoWhileExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXEqualityExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXExpressionInClosure(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXExpressionOrVarDeclaration(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXFeatureCall(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXForLoopExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXFunctionTypeRef(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXIfExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXImportDeclaration(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXListLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXMemberFeatureCall(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXMultiplicativeExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXNullLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXNumberLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXOrExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXOtherOperatorExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXParenthesizedExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXPostfixOperation(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXPrimaryExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXRelationalExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXReturnExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXSetLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXShortClosure(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXStringLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXSwitchExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXSynchronizedExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXThrowExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXTryCatchFinallyExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXTypeLiteral(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXUnaryOperation(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXVariableDeclaration(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXWhileExpression(self) -> org.eclipse.emf.ecore.EObject: ...
    def synpred10_InternalScript(self) -> bool: ...
    def synpred10_InternalScript_fragment(self) -> None: ...
    def synpred11_InternalScript(self) -> bool: ...
    def synpred11_InternalScript_fragment(self) -> None: ...
    def synpred12_InternalScript(self) -> bool: ...
    def synpred12_InternalScript_fragment(self) -> None: ...
    def synpred13_InternalScript(self) -> bool: ...
    def synpred13_InternalScript_fragment(self) -> None: ...
    def synpred14_InternalScript(self) -> bool: ...
    def synpred14_InternalScript_fragment(self) -> None: ...
    def synpred15_InternalScript(self) -> bool: ...
    def synpred15_InternalScript_fragment(self) -> None: ...
    def synpred16_InternalScript(self) -> bool: ...
    def synpred16_InternalScript_fragment(self) -> None: ...
    def synpred17_InternalScript(self) -> bool: ...
    def synpred17_InternalScript_fragment(self) -> None: ...
    def synpred18_InternalScript(self) -> bool: ...
    def synpred18_InternalScript_fragment(self) -> None: ...
    def synpred19_InternalScript(self) -> bool: ...
    def synpred19_InternalScript_fragment(self) -> None: ...
    def synpred1_InternalScript(self) -> bool: ...
    def synpred1_InternalScript_fragment(self) -> None: ...
    def synpred20_InternalScript(self) -> bool: ...
    def synpred20_InternalScript_fragment(self) -> None: ...
    def synpred21_InternalScript(self) -> bool: ...
    def synpred21_InternalScript_fragment(self) -> None: ...
    def synpred23_InternalScript(self) -> bool: ...
    def synpred23_InternalScript_fragment(self) -> None: ...
    def synpred25_InternalScript(self) -> bool: ...
    def synpred25_InternalScript_fragment(self) -> None: ...
    def synpred26_InternalScript(self) -> bool: ...
    def synpred26_InternalScript_fragment(self) -> None: ...
    def synpred27_InternalScript(self) -> bool: ...
    def synpred27_InternalScript_fragment(self) -> None: ...
    def synpred29_InternalScript(self) -> bool: ...
    def synpred29_InternalScript_fragment(self) -> None: ...
    def synpred2_InternalScript(self) -> bool: ...
    def synpred2_InternalScript_fragment(self) -> None: ...
    def synpred30_InternalScript(self) -> bool: ...
    def synpred30_InternalScript_fragment(self) -> None: ...
    def synpred31_InternalScript(self) -> bool: ...
    def synpred31_InternalScript_fragment(self) -> None: ...
    def synpred32_InternalScript(self) -> bool: ...
    def synpred32_InternalScript_fragment(self) -> None: ...
    def synpred33_InternalScript(self) -> bool: ...
    def synpred33_InternalScript_fragment(self) -> None: ...
    def synpred34_InternalScript(self) -> bool: ...
    def synpred34_InternalScript_fragment(self) -> None: ...
    def synpred35_InternalScript(self) -> bool: ...
    def synpred35_InternalScript_fragment(self) -> None: ...
    def synpred36_InternalScript(self) -> bool: ...
    def synpred36_InternalScript_fragment(self) -> None: ...
    def synpred37_InternalScript(self) -> bool: ...
    def synpred37_InternalScript_fragment(self) -> None: ...
    def synpred38_InternalScript(self) -> bool: ...
    def synpred38_InternalScript_fragment(self) -> None: ...
    def synpred39_InternalScript(self) -> bool: ...
    def synpred39_InternalScript_fragment(self) -> None: ...
    def synpred3_InternalScript(self) -> bool: ...
    def synpred3_InternalScript_fragment(self) -> None: ...
    def synpred42_InternalScript(self) -> bool: ...
    def synpred42_InternalScript_fragment(self) -> None: ...
    def synpred43_InternalScript(self) -> bool: ...
    def synpred43_InternalScript_fragment(self) -> None: ...
    def synpred44_InternalScript(self) -> bool: ...
    def synpred44_InternalScript_fragment(self) -> None: ...
    def synpred45_InternalScript(self) -> bool: ...
    def synpred45_InternalScript_fragment(self) -> None: ...
    def synpred46_InternalScript(self) -> bool: ...
    def synpred46_InternalScript_fragment(self) -> None: ...
    def synpred4_InternalScript(self) -> bool: ...
    def synpred4_InternalScript_fragment(self) -> None: ...
    def synpred5_InternalScript(self) -> bool: ...
    def synpred5_InternalScript_fragment(self) -> None: ...
    def synpred6_InternalScript(self) -> bool: ...
    def synpred6_InternalScript_fragment(self) -> None: ...
    def synpred7_InternalScript(self) -> bool: ...
    def synpred7_InternalScript_fragment(self) -> None: ...
    def synpred8_InternalScript(self) -> bool: ...
    def synpred8_InternalScript_fragment(self) -> None: ...
    def synpred9_InternalScript(self) -> bool: ...
    def synpred9_InternalScript_fragment(self) -> None: ...
