import java
import java.lang
import java.text
import java.time
import java.time.chrono
import java.time.temporal
import java.util
import typing


class DateTimeFormatter(java.lang.Object):
    """
    Java class 'java.time.format.DateTimeFormatter'
    
        Extends:
            java.lang.Object
    
      Attributes:
        ISO_LOCAL_DATE (java.time.format.DateTimeFormatter): final static field
        ISO_OFFSET_DATE (java.time.format.DateTimeFormatter): final static field
        ISO_DATE (java.time.format.DateTimeFormatter): final static field
        ISO_LOCAL_TIME (java.time.format.DateTimeFormatter): final static field
        ISO_OFFSET_TIME (java.time.format.DateTimeFormatter): final static field
        ISO_TIME (java.time.format.DateTimeFormatter): final static field
        ISO_LOCAL_DATE_TIME (java.time.format.DateTimeFormatter): final static field
        ISO_OFFSET_DATE_TIME (java.time.format.DateTimeFormatter): final static field
        ISO_ZONED_DATE_TIME (java.time.format.DateTimeFormatter): final static field
        ISO_DATE_TIME (java.time.format.DateTimeFormatter): final static field
        ISO_ORDINAL_DATE (java.time.format.DateTimeFormatter): final static field
        ISO_WEEK_DATE (java.time.format.DateTimeFormatter): final static field
        ISO_INSTANT (java.time.format.DateTimeFormatter): final static field
        BASIC_ISO_DATE (java.time.format.DateTimeFormatter): final static field
        RFC_1123_DATE_TIME (java.time.format.DateTimeFormatter): final static field
    
    """
    ISO_LOCAL_DATE: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_OFFSET_DATE: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_DATE: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_LOCAL_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_OFFSET_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_LOCAL_DATE_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_OFFSET_DATE_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_ZONED_DATE_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_DATE_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_ORDINAL_DATE: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_WEEK_DATE: typing.ClassVar['DateTimeFormatter'] = ...
    ISO_INSTANT: typing.ClassVar['DateTimeFormatter'] = ...
    BASIC_ISO_DATE: typing.ClassVar['DateTimeFormatter'] = ...
    RFC_1123_DATE_TIME: typing.ClassVar['DateTimeFormatter'] = ...
    def format(self, temporalAccessor: java.time.temporal.TemporalAccessor) -> java.lang.String: ...
    def formatTo(self, temporalAccessor: java.time.temporal.TemporalAccessor, appendable: java.lang.Appendable) -> None: ...
    def getChronology(self) -> java.time.chrono.Chronology: ...
    def getDecimalStyle(self) -> 'DecimalStyle': ...
    def getLocale(self) -> java.util.Locale: ...
    def getResolverFields(self) -> java.util.Set[java.time.temporal.TemporalField]: ...
    def getResolverStyle(self) -> 'ResolverStyle': ...
    def getZone(self) -> java.time.ZoneId: ...
    def localizedBy(self, locale: java.util.Locale) -> 'DateTimeFormatter': ...
    @classmethod
    def ofLocalizedDate(cls, formatStyle: 'FormatStyle') -> 'DateTimeFormatter': ...
    @classmethod
    @typing.overload
    def ofLocalizedDateTime(cls, formatStyle: 'FormatStyle') -> 'DateTimeFormatter': ...
    @classmethod
    @typing.overload
    def ofLocalizedDateTime(cls, formatStyle: 'FormatStyle', formatStyle2: 'FormatStyle') -> 'DateTimeFormatter': ...
    @classmethod
    def ofLocalizedTime(cls, formatStyle: 'FormatStyle') -> 'DateTimeFormatter': ...
    @classmethod
    @typing.overload
    def ofPattern(cls, string: java.lang.String) -> 'DateTimeFormatter': ...
    @classmethod
    @typing.overload
    def ofPattern(cls, string: java.lang.String, locale: java.util.Locale) -> 'DateTimeFormatter': ...
    _parse_0__T = typing.TypeVar('_parse_0__T')  # <T>
    @typing.overload
    def parse(self, charSequence: java.lang.CharSequence, temporalQuery: typing.Union[java.time.temporal.TemporalQuery[_parse_0__T], typing.Callable[[], _parse_0__T]]) -> _parse_0__T: ...
    @typing.overload
    def parse(self, charSequence: java.lang.CharSequence) -> java.time.temporal.TemporalAccessor: ...
    @typing.overload
    def parse(self, charSequence: java.lang.CharSequence, parsePosition: java.text.ParsePosition) -> java.time.temporal.TemporalAccessor: ...
    def parseBest(self, charSequence: java.lang.CharSequence, temporalQueryArray: typing.List[java.time.temporal.TemporalQuery[typing.Any]]) -> java.time.temporal.TemporalAccessor: ...
    def parseUnresolved(self, charSequence: java.lang.CharSequence, parsePosition: java.text.ParsePosition) -> java.time.temporal.TemporalAccessor: ...
    @classmethod
    def parsedExcessDays(cls) -> java.time.temporal.TemporalQuery[java.time.Period]: ...
    @classmethod
    def parsedLeapSecond(cls) -> java.time.temporal.TemporalQuery[bool]: ...
    @typing.overload
    def toFormat(self) -> java.text.Format: ...
    @typing.overload
    def toFormat(self, temporalQuery: typing.Union[java.time.temporal.TemporalQuery[typing.Any], typing.Callable[[], typing.Any]]) -> java.text.Format: ...
    def toString(self) -> java.lang.String: ...
    def withChronology(self, chronology: java.time.chrono.Chronology) -> 'DateTimeFormatter': ...
    def withDecimalStyle(self, decimalStyle: 'DecimalStyle') -> 'DateTimeFormatter': ...
    def withLocale(self, locale: java.util.Locale) -> 'DateTimeFormatter': ...
    @typing.overload
    def withResolverFields(self, temporalFieldArray: typing.List[java.time.temporal.TemporalField]) -> 'DateTimeFormatter': ...
    @typing.overload
    def withResolverFields(self, set: java.util.Set[java.time.temporal.TemporalField]) -> 'DateTimeFormatter': ...
    def withResolverStyle(self, resolverStyle: 'ResolverStyle') -> 'DateTimeFormatter': ...
    def withZone(self, zoneId: java.time.ZoneId) -> 'DateTimeFormatter': ...

class DateTimeFormatterBuilder(java.lang.Object):
    """
    Java class 'java.time.format.DateTimeFormatterBuilder'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * DateTimeFormatterBuilder()
    
    """
    def __init__(self): ...
    def append(self, dateTimeFormatter: DateTimeFormatter) -> 'DateTimeFormatterBuilder': ...
    def appendChronologyId(self) -> 'DateTimeFormatterBuilder': ...
    def appendChronologyText(self, textStyle: 'TextStyle') -> 'DateTimeFormatterBuilder': ...
    def appendFraction(self, temporalField: java.time.temporal.TemporalField, int: int, int2: int, boolean: bool) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendGenericZoneText(self, textStyle: 'TextStyle') -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendGenericZoneText(self, textStyle: 'TextStyle', set: java.util.Set[java.time.ZoneId]) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendInstant(self) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendInstant(self, int: int) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendLiteral(self, char: str) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendLiteral(self, string: java.lang.String) -> 'DateTimeFormatterBuilder': ...
    def appendLocalized(self, formatStyle: 'FormatStyle', formatStyle2: 'FormatStyle') -> 'DateTimeFormatterBuilder': ...
    def appendLocalizedOffset(self, textStyle: 'TextStyle') -> 'DateTimeFormatterBuilder': ...
    def appendOffset(self, string: java.lang.String, string2: java.lang.String) -> 'DateTimeFormatterBuilder': ...
    def appendOffsetId(self) -> 'DateTimeFormatterBuilder': ...
    def appendOptional(self, dateTimeFormatter: DateTimeFormatter) -> 'DateTimeFormatterBuilder': ...
    def appendPattern(self, string: java.lang.String) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendText(self, temporalField: java.time.temporal.TemporalField) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendText(self, temporalField: java.time.temporal.TemporalField, textStyle: 'TextStyle') -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendText(self, temporalField: java.time.temporal.TemporalField, map: typing.Union[java.util.Map[int, java.lang.String], typing.Mapping[int, java.lang.String]]) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendValue(self, temporalField: java.time.temporal.TemporalField) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendValue(self, temporalField: java.time.temporal.TemporalField, int: int) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendValue(self, temporalField: java.time.temporal.TemporalField, int: int, int2: int, signStyle: 'SignStyle') -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendValueReduced(self, temporalField: java.time.temporal.TemporalField, int: int, int2: int, int3: int) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendValueReduced(self, temporalField: java.time.temporal.TemporalField, int: int, int2: int, chronoLocalDate: java.time.chrono.ChronoLocalDate) -> 'DateTimeFormatterBuilder': ...
    def appendZoneId(self) -> 'DateTimeFormatterBuilder': ...
    def appendZoneOrOffsetId(self) -> 'DateTimeFormatterBuilder': ...
    def appendZoneRegionId(self) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendZoneText(self, textStyle: 'TextStyle') -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def appendZoneText(self, textStyle: 'TextStyle', set: java.util.Set[java.time.ZoneId]) -> 'DateTimeFormatterBuilder': ...
    @classmethod
    def getLocalizedDateTimePattern(cls, formatStyle: 'FormatStyle', formatStyle2: 'FormatStyle', chronology: java.time.chrono.Chronology, locale: java.util.Locale) -> java.lang.String: ...
    def optionalEnd(self) -> 'DateTimeFormatterBuilder': ...
    def optionalStart(self) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def padNext(self, int: int) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def padNext(self, int: int, char: str) -> 'DateTimeFormatterBuilder': ...
    def parseCaseInsensitive(self) -> 'DateTimeFormatterBuilder': ...
    def parseCaseSensitive(self) -> 'DateTimeFormatterBuilder': ...
    def parseDefaulting(self, temporalField: java.time.temporal.TemporalField, long: int) -> 'DateTimeFormatterBuilder': ...
    def parseLenient(self) -> 'DateTimeFormatterBuilder': ...
    def parseStrict(self) -> 'DateTimeFormatterBuilder': ...
    @typing.overload
    def toFormatter(self) -> DateTimeFormatter: ...
    @typing.overload
    def toFormatter(self, locale: java.util.Locale) -> DateTimeFormatter: ...

class DateTimeParseException(java.time.DateTimeException):
    """
    Java class 'java.time.format.DateTimeParseException'
    
        Extends:
            java.time.DateTimeException
    
      Constructors:
        * DateTimeParseException(java.lang.String, java.lang.CharSequence, int)
        * DateTimeParseException(java.lang.String, java.lang.CharSequence, int, java.lang.Throwable)
    
    """
    @typing.overload
    def __init__(self, string: java.lang.String, charSequence: java.lang.CharSequence, int: int): ...
    @typing.overload
    def __init__(self, string: java.lang.String, charSequence: java.lang.CharSequence, int: int, throwable: java.lang.Throwable): ...
    def getErrorIndex(self) -> int: ...
    def getParsedString(self) -> java.lang.String: ...

class DecimalStyle(java.lang.Object):
    """
    Java class 'java.time.format.DecimalStyle'
    
        Extends:
            java.lang.Object
    
      Attributes:
        STANDARD (java.time.format.DecimalStyle): final static field
    
    """
    STANDARD: typing.ClassVar['DecimalStyle'] = ...
    def equals(self, object: typing.Any) -> bool: ...
    @classmethod
    def getAvailableLocales(cls) -> java.util.Set[java.util.Locale]: ...
    def getDecimalSeparator(self) -> str: ...
    def getNegativeSign(self) -> str: ...
    def getPositiveSign(self) -> str: ...
    def getZeroDigit(self) -> str: ...
    def hashCode(self) -> int: ...
    @classmethod
    def of(cls, locale: java.util.Locale) -> 'DecimalStyle': ...
    @classmethod
    def ofDefaultLocale(cls) -> 'DecimalStyle': ...
    def toString(self) -> java.lang.String: ...
    def withDecimalSeparator(self, char: str) -> 'DecimalStyle': ...
    def withNegativeSign(self, char: str) -> 'DecimalStyle': ...
    def withPositiveSign(self, char: str) -> 'DecimalStyle': ...
    def withZeroDigit(self, char: str) -> 'DecimalStyle': ...

class FormatStyle(java.lang.Enum[java.time.format.FormatStyle]):
    """
    Java class 'java.time.format.FormatStyle'
    
        Extends:
            java.lang.Enum
    
      Attributes:
        FULL (java.time.format.FormatStyle): final static enum constant
        LONG (java.time.format.FormatStyle): final static enum constant
        MEDIUM (java.time.format.FormatStyle): final static enum constant
        SHORT (java.time.format.FormatStyle): final static enum constant
    
    """
    FULL: typing.ClassVar['FormatStyle'] = ...
    LONG: typing.ClassVar['FormatStyle'] = ...
    MEDIUM: typing.ClassVar['FormatStyle'] = ...
    SHORT: typing.ClassVar['FormatStyle'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @classmethod
    @typing.overload
    def valueOf(cls, class_: typing.Type[_valueOf_0__T], string: java.lang.String) -> _valueOf_0__T: ...
    @classmethod
    @typing.overload
    def valueOf(cls, string: java.lang.String) -> 'FormatStyle': ...
    @classmethod
    def values(cls) -> typing.List['FormatStyle']: ...

class ResolverStyle(java.lang.Enum[java.time.format.ResolverStyle]):
    """
    Java class 'java.time.format.ResolverStyle'
    
        Extends:
            java.lang.Enum
    
      Attributes:
        STRICT (java.time.format.ResolverStyle): final static enum constant
        SMART (java.time.format.ResolverStyle): final static enum constant
        LENIENT (java.time.format.ResolverStyle): final static enum constant
    
    """
    STRICT: typing.ClassVar['ResolverStyle'] = ...
    SMART: typing.ClassVar['ResolverStyle'] = ...
    LENIENT: typing.ClassVar['ResolverStyle'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @classmethod
    @typing.overload
    def valueOf(cls, class_: typing.Type[_valueOf_0__T], string: java.lang.String) -> _valueOf_0__T: ...
    @classmethod
    @typing.overload
    def valueOf(cls, string: java.lang.String) -> 'ResolverStyle': ...
    @classmethod
    def values(cls) -> typing.List['ResolverStyle']: ...

class SignStyle(java.lang.Enum[java.time.format.SignStyle]):
    """
    Java class 'java.time.format.SignStyle'
    
        Extends:
            java.lang.Enum
    
      Attributes:
        NORMAL (java.time.format.SignStyle): final static enum constant
        ALWAYS (java.time.format.SignStyle): final static enum constant
        NEVER (java.time.format.SignStyle): final static enum constant
        NOT_NEGATIVE (java.time.format.SignStyle): final static enum constant
        EXCEEDS_PAD (java.time.format.SignStyle): final static enum constant
    
    """
    NORMAL: typing.ClassVar['SignStyle'] = ...
    ALWAYS: typing.ClassVar['SignStyle'] = ...
    NEVER: typing.ClassVar['SignStyle'] = ...
    NOT_NEGATIVE: typing.ClassVar['SignStyle'] = ...
    EXCEEDS_PAD: typing.ClassVar['SignStyle'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @classmethod
    @typing.overload
    def valueOf(cls, class_: typing.Type[_valueOf_0__T], string: java.lang.String) -> _valueOf_0__T: ...
    @classmethod
    @typing.overload
    def valueOf(cls, string: java.lang.String) -> 'SignStyle': ...
    @classmethod
    def values(cls) -> typing.List['SignStyle']: ...

class TextStyle(java.lang.Enum[java.time.format.TextStyle]):
    """
    Java class 'java.time.format.TextStyle'
    
        Extends:
            java.lang.Enum
    
      Attributes:
        FULL (java.time.format.TextStyle): final static enum constant
        FULL_STANDALONE (java.time.format.TextStyle): final static enum constant
        SHORT (java.time.format.TextStyle): final static enum constant
        SHORT_STANDALONE (java.time.format.TextStyle): final static enum constant
        NARROW (java.time.format.TextStyle): final static enum constant
        NARROW_STANDALONE (java.time.format.TextStyle): final static enum constant
    
    """
    FULL: typing.ClassVar['TextStyle'] = ...
    FULL_STANDALONE: typing.ClassVar['TextStyle'] = ...
    SHORT: typing.ClassVar['TextStyle'] = ...
    SHORT_STANDALONE: typing.ClassVar['TextStyle'] = ...
    NARROW: typing.ClassVar['TextStyle'] = ...
    NARROW_STANDALONE: typing.ClassVar['TextStyle'] = ...
    def asNormal(self) -> 'TextStyle': ...
    def asStandalone(self) -> 'TextStyle': ...
    def isStandalone(self) -> bool: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @classmethod
    @typing.overload
    def valueOf(cls, class_: typing.Type[_valueOf_0__T], string: java.lang.String) -> _valueOf_0__T: ...
    @classmethod
    @typing.overload
    def valueOf(cls, string: java.lang.String) -> 'TextStyle': ...
    @classmethod
    def values(cls) -> typing.List['TextStyle']: ...
