import java.lang
import org.osgi.framework


class StartLevel(java.lang.Object):
    """
    Java class 'org.osgi.service.startlevel.StartLevel'
    
    """
    def getBundleStartLevel(self, bundle: org.osgi.framework.Bundle) -> int: ...
    def getInitialBundleStartLevel(self) -> int: ...
    def getStartLevel(self) -> int: ...
    def isBundleActivationPolicyUsed(self, bundle: org.osgi.framework.Bundle) -> bool: ...
    def isBundlePersistentlyStarted(self, bundle: org.osgi.framework.Bundle) -> bool: ...
    def setBundleStartLevel(self, bundle: org.osgi.framework.Bundle, int: int) -> None: ...
    def setInitialBundleStartLevel(self, int: int) -> None: ...
    def setStartLevel(self, int: int) -> None: ...
