import java.lang
import org.eclipse.emf.common.util
import org.eclipse.emf.ecore
import typing


class ModelProperty(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.thing.thing.ModelProperty'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getKey(self) -> java.lang.String: ...
    def getValue(self) -> org.eclipse.emf.common.util.EList[typing.Any]: ...
    def setKey(self, string: java.lang.String) -> None: ...

class ModelPropertyContainer(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.thing.thing.ModelPropertyContainer'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getId(self) -> java.lang.String: ...
    def getLabel(self) -> java.lang.String: ...
    def getProperties(self) -> org.eclipse.emf.common.util.EList[ModelProperty]: ...
    def setId(self, string: java.lang.String) -> None: ...
    def setLabel(self, string: java.lang.String) -> None: ...

class ThingFactory(org.eclipse.emf.ecore.EFactory):
    """
    Java class 'org.openhab.core.model.thing.thing.ThingFactory'
    
        Interfaces:
            org.eclipse.emf.ecore.EFactory
    
      Attributes:
        eINSTANCE (org.openhab.core.model.thing.thing.ThingFactory): final static field
    
    """
    eINSTANCE: typing.ClassVar['ThingFactory'] = ...
    def createModelBridge(self) -> 'ModelBridge': ...
    def createModelChannel(self) -> 'ModelChannel': ...
    def createModelProperty(self) -> ModelProperty: ...
    def createModelPropertyContainer(self) -> ModelPropertyContainer: ...
    def createModelThing(self) -> 'ModelThing': ...
    def createThingModel(self) -> 'ThingModel': ...
    def getThingPackage(self) -> 'ThingPackage': ...

class ThingModel(org.eclipse.emf.ecore.EObject):
    """
    Java class 'org.openhab.core.model.thing.thing.ThingModel'
    
        Interfaces:
            org.eclipse.emf.ecore.EObject
    
    """
    def getThings(self) -> org.eclipse.emf.common.util.EList['ModelThing']: ...

class ThingPackage(org.eclipse.emf.ecore.EPackage):
    """
    Java class 'org.openhab.core.model.thing.thing.ThingPackage'
    
        Interfaces:
            org.eclipse.emf.ecore.EPackage
    
      Attributes:
        eNAME (java.lang.String): final static field
        eNS_URI (java.lang.String): final static field
        eNS_PREFIX (java.lang.String): final static field
        eINSTANCE (org.openhab.core.model.thing.thing.ThingPackage): final static field
        THING_MODEL (int): final static field
        THING_MODEL__THINGS (int): final static field
        THING_MODEL_FEATURE_COUNT (int): final static field
        MODEL_PROPERTY_CONTAINER (int): final static field
        MODEL_PROPERTY_CONTAINER__ID (int): final static field
        MODEL_PROPERTY_CONTAINER__LABEL (int): final static field
        MODEL_PROPERTY_CONTAINER__PROPERTIES (int): final static field
        MODEL_PROPERTY_CONTAINER_FEATURE_COUNT (int): final static field
        MODEL_THING (int): final static field
        MODEL_THING__ID (int): final static field
        MODEL_THING__LABEL (int): final static field
        MODEL_THING__PROPERTIES (int): final static field
        MODEL_THING__THING_TYPE_ID (int): final static field
        MODEL_THING__THING_ID (int): final static field
        MODEL_THING__BRIDGE_UID (int): final static field
        MODEL_THING__LOCATION (int): final static field
        MODEL_THING__CHANNELS (int): final static field
        MODEL_THING_FEATURE_COUNT (int): final static field
        MODEL_CHANNEL (int): final static field
        MODEL_CHANNEL__ID (int): final static field
        MODEL_CHANNEL__LABEL (int): final static field
        MODEL_CHANNEL__PROPERTIES (int): final static field
        MODEL_CHANNEL__CHANNEL_KIND (int): final static field
        MODEL_CHANNEL__TYPE (int): final static field
        MODEL_CHANNEL__CHANNEL_TYPE (int): final static field
        MODEL_CHANNEL_FEATURE_COUNT (int): final static field
        MODEL_PROPERTY (int): final static field
        MODEL_PROPERTY__KEY (int): final static field
        MODEL_PROPERTY__VALUE (int): final static field
        MODEL_PROPERTY_FEATURE_COUNT (int): final static field
        MODEL_BRIDGE (int): final static field
        MODEL_BRIDGE__ID (int): final static field
        MODEL_BRIDGE__LABEL (int): final static field
        MODEL_BRIDGE__PROPERTIES (int): final static field
        MODEL_BRIDGE__THING_TYPE_ID (int): final static field
        MODEL_BRIDGE__THING_ID (int): final static field
        MODEL_BRIDGE__BRIDGE_UID (int): final static field
        MODEL_BRIDGE__LOCATION (int): final static field
        MODEL_BRIDGE__CHANNELS (int): final static field
        MODEL_BRIDGE__BRIDGE (int): final static field
        MODEL_BRIDGE__THINGS (int): final static field
        MODEL_BRIDGE_FEATURE_COUNT (int): final static field
    
    """
    eNAME: typing.ClassVar[java.lang.String] = ...
    eNS_URI: typing.ClassVar[java.lang.String] = ...
    eNS_PREFIX: typing.ClassVar[java.lang.String] = ...
    eINSTANCE: typing.ClassVar['ThingPackage'] = ...
    THING_MODEL: typing.ClassVar[int] = ...
    THING_MODEL__THINGS: typing.ClassVar[int] = ...
    THING_MODEL_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_PROPERTY_CONTAINER: typing.ClassVar[int] = ...
    MODEL_PROPERTY_CONTAINER__ID: typing.ClassVar[int] = ...
    MODEL_PROPERTY_CONTAINER__LABEL: typing.ClassVar[int] = ...
    MODEL_PROPERTY_CONTAINER__PROPERTIES: typing.ClassVar[int] = ...
    MODEL_PROPERTY_CONTAINER_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_THING: typing.ClassVar[int] = ...
    MODEL_THING__ID: typing.ClassVar[int] = ...
    MODEL_THING__LABEL: typing.ClassVar[int] = ...
    MODEL_THING__PROPERTIES: typing.ClassVar[int] = ...
    MODEL_THING__THING_TYPE_ID: typing.ClassVar[int] = ...
    MODEL_THING__THING_ID: typing.ClassVar[int] = ...
    MODEL_THING__BRIDGE_UID: typing.ClassVar[int] = ...
    MODEL_THING__LOCATION: typing.ClassVar[int] = ...
    MODEL_THING__CHANNELS: typing.ClassVar[int] = ...
    MODEL_THING_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_CHANNEL: typing.ClassVar[int] = ...
    MODEL_CHANNEL__ID: typing.ClassVar[int] = ...
    MODEL_CHANNEL__LABEL: typing.ClassVar[int] = ...
    MODEL_CHANNEL__PROPERTIES: typing.ClassVar[int] = ...
    MODEL_CHANNEL__CHANNEL_KIND: typing.ClassVar[int] = ...
    MODEL_CHANNEL__TYPE: typing.ClassVar[int] = ...
    MODEL_CHANNEL__CHANNEL_TYPE: typing.ClassVar[int] = ...
    MODEL_CHANNEL_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_PROPERTY: typing.ClassVar[int] = ...
    MODEL_PROPERTY__KEY: typing.ClassVar[int] = ...
    MODEL_PROPERTY__VALUE: typing.ClassVar[int] = ...
    MODEL_PROPERTY_FEATURE_COUNT: typing.ClassVar[int] = ...
    MODEL_BRIDGE: typing.ClassVar[int] = ...
    MODEL_BRIDGE__ID: typing.ClassVar[int] = ...
    MODEL_BRIDGE__LABEL: typing.ClassVar[int] = ...
    MODEL_BRIDGE__PROPERTIES: typing.ClassVar[int] = ...
    MODEL_BRIDGE__THING_TYPE_ID: typing.ClassVar[int] = ...
    MODEL_BRIDGE__THING_ID: typing.ClassVar[int] = ...
    MODEL_BRIDGE__BRIDGE_UID: typing.ClassVar[int] = ...
    MODEL_BRIDGE__LOCATION: typing.ClassVar[int] = ...
    MODEL_BRIDGE__CHANNELS: typing.ClassVar[int] = ...
    MODEL_BRIDGE__BRIDGE: typing.ClassVar[int] = ...
    MODEL_BRIDGE__THINGS: typing.ClassVar[int] = ...
    MODEL_BRIDGE_FEATURE_COUNT: typing.ClassVar[int] = ...
    def getModelBridge(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelBridge_Bridge(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelBridge_Things(self) -> org.eclipse.emf.ecore.EReference: ...
    def getModelChannel(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelChannel_ChannelKind(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelChannel_ChannelType(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelChannel_Type(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelProperty(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelPropertyContainer(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelPropertyContainer_Id(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelPropertyContainer_Label(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelPropertyContainer_Properties(self) -> org.eclipse.emf.ecore.EReference: ...
    def getModelProperty_Key(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelProperty_Value(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelThing(self) -> org.eclipse.emf.ecore.EClass: ...
    def getModelThing_BridgeUID(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelThing_Channels(self) -> org.eclipse.emf.ecore.EReference: ...
    def getModelThing_Location(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelThing_ThingId(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getModelThing_ThingTypeId(self) -> org.eclipse.emf.ecore.EAttribute: ...
    def getThingFactory(self) -> ThingFactory: ...
    def getThingModel(self) -> org.eclipse.emf.ecore.EClass: ...
    def getThingModel_Things(self) -> org.eclipse.emf.ecore.EReference: ...
    class Literals(java.lang.Object):
        """
        Java class 'org.openhab.core.model.thing.thing.ThingPackage$Literals'
        
          Attributes:
            THING_MODEL (org.eclipse.emf.ecore.EClass): final static field
            THING_MODEL__THINGS (org.eclipse.emf.ecore.EReference): final static field
            MODEL_PROPERTY_CONTAINER (org.eclipse.emf.ecore.EClass): final static field
            MODEL_PROPERTY_CONTAINER__ID (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_PROPERTY_CONTAINER__LABEL (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_PROPERTY_CONTAINER__PROPERTIES (org.eclipse.emf.ecore.EReference): final static field
            MODEL_THING (org.eclipse.emf.ecore.EClass): final static field
            MODEL_THING__THING_TYPE_ID (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_THING__THING_ID (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_THING__BRIDGE_UID (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_THING__LOCATION (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_THING__CHANNELS (org.eclipse.emf.ecore.EReference): final static field
            MODEL_CHANNEL (org.eclipse.emf.ecore.EClass): final static field
            MODEL_CHANNEL__CHANNEL_KIND (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_CHANNEL__TYPE (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_CHANNEL__CHANNEL_TYPE (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_PROPERTY (org.eclipse.emf.ecore.EClass): final static field
            MODEL_PROPERTY__KEY (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_PROPERTY__VALUE (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_BRIDGE (org.eclipse.emf.ecore.EClass): final static field
            MODEL_BRIDGE__BRIDGE (org.eclipse.emf.ecore.EAttribute): final static field
            MODEL_BRIDGE__THINGS (org.eclipse.emf.ecore.EReference): final static field
        
        """
        THING_MODEL: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        THING_MODEL__THINGS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        MODEL_PROPERTY_CONTAINER: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_PROPERTY_CONTAINER__ID: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_PROPERTY_CONTAINER__LABEL: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_PROPERTY_CONTAINER__PROPERTIES: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        MODEL_THING: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_THING__THING_TYPE_ID: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_THING__THING_ID: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_THING__BRIDGE_UID: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_THING__LOCATION: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_THING__CHANNELS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...
        MODEL_CHANNEL: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_CHANNEL__CHANNEL_KIND: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_CHANNEL__TYPE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_CHANNEL__CHANNEL_TYPE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_PROPERTY: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_PROPERTY__KEY: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_PROPERTY__VALUE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_BRIDGE: typing.ClassVar[org.eclipse.emf.ecore.EClass] = ...
        MODEL_BRIDGE__BRIDGE: typing.ClassVar[org.eclipse.emf.ecore.EAttribute] = ...
        MODEL_BRIDGE__THINGS: typing.ClassVar[org.eclipse.emf.ecore.EReference] = ...

class ModelChannel(ModelPropertyContainer):
    """
    Java class 'org.openhab.core.model.thing.thing.ModelChannel'
    
        Interfaces:
            org.openhab.core.model.thing.thing.ModelPropertyContainer
    
    """
    def getChannelKind(self) -> java.lang.String: ...
    def getChannelType(self) -> java.lang.String: ...
    def getType(self) -> java.lang.String: ...
    def setChannelKind(self, string: java.lang.String) -> None: ...
    def setChannelType(self, string: java.lang.String) -> None: ...
    def setType(self, string: java.lang.String) -> None: ...

class ModelThing(ModelPropertyContainer):
    """
    Java class 'org.openhab.core.model.thing.thing.ModelThing'
    
        Interfaces:
            org.openhab.core.model.thing.thing.ModelPropertyContainer
    
    """
    def getBridgeUID(self) -> java.lang.String: ...
    def getChannels(self) -> org.eclipse.emf.common.util.EList[ModelChannel]: ...
    def getLocation(self) -> java.lang.String: ...
    def getThingId(self) -> java.lang.String: ...
    def getThingTypeId(self) -> java.lang.String: ...
    def setBridgeUID(self, string: java.lang.String) -> None: ...
    def setLocation(self, string: java.lang.String) -> None: ...
    def setThingId(self, string: java.lang.String) -> None: ...
    def setThingTypeId(self, string: java.lang.String) -> None: ...

class ModelBridge(ModelThing):
    """
    Java class 'org.openhab.core.model.thing.thing.ModelBridge'
    
        Interfaces:
            org.openhab.core.model.thing.thing.ModelThing
    
    """
    def getThings(self) -> org.eclipse.emf.common.util.EList[ModelThing]: ...
    def isBridge(self) -> bool: ...
    def setBridge(self, boolean: bool) -> None: ...
