import java.lang
import org.antlr.runtime
import org.eclipse.emf.ecore
import org.eclipse.xtext.parser.antlr
import org.openhab.core.model.sitemap.services
import typing


class InternalSitemapLexer(org.eclipse.xtext.parser.antlr.Lexer):
    """
    Java class 'org.openhab.core.model.sitemap.parser.antlr.internal.InternalSitemapLexer'
    
        Extends:
            org.eclipse.xtext.parser.antlr.Lexer
    
      Constructors:
        * InternalSitemapLexer(org.antlr.runtime.CharStream)
        * InternalSitemapLexer()
        * InternalSitemapLexer(org.antlr.runtime.CharStream, org.antlr.runtime.RecognizerSharedState)
    
      Attributes:
        T__50 (int): final static field
        T__19 (int): final static field
        T__15 (int): final static field
        T__59 (int): final static field
        T__16 (int): final static field
        T__17 (int): final static field
        T__18 (int): final static field
        T__55 (int): final static field
        T__12 (int): final static field
        T__56 (int): final static field
        T__13 (int): final static field
        T__57 (int): final static field
        T__14 (int): final static field
        T__58 (int): final static field
        T__51 (int): final static field
        T__52 (int): final static field
        T__53 (int): final static field
        T__54 (int): final static field
        T__60 (int): final static field
        T__61 (int): final static field
        RULE_ID (int): final static field
        T__26 (int): final static field
        T__27 (int): final static field
        T__28 (int): final static field
        RULE_INT (int): final static field
        T__29 (int): final static field
        T__22 (int): final static field
        RULE_ML_COMMENT (int): final static field
        T__23 (int): final static field
        T__24 (int): final static field
        T__25 (int): final static field
        T__62 (int): final static field
        T__63 (int): final static field
        T__20 (int): final static field
        T__21 (int): final static field
        RULE_STRING (int): final static field
        RULE_SL_COMMENT (int): final static field
        T__37 (int): final static field
        T__38 (int): final static field
        T__39 (int): final static field
        T__33 (int): final static field
        T__34 (int): final static field
        T__35 (int): final static field
        T__36 (int): final static field
        EOF (int): final static field
        T__30 (int): final static field
        T__31 (int): final static field
        T__32 (int): final static field
        RULE_WS (int): final static field
        RULE_ANY_OTHER (int): final static field
        T__48 (int): final static field
        T__49 (int): final static field
        T__44 (int): final static field
        T__45 (int): final static field
        RULE_FLOAT (int): final static field
        T__46 (int): final static field
        T__47 (int): final static field
        T__40 (int): final static field
        T__41 (int): final static field
        T__42 (int): final static field
        T__43 (int): final static field
    
    """
    T__50: typing.ClassVar[int] = ...
    T__19: typing.ClassVar[int] = ...
    T__15: typing.ClassVar[int] = ...
    T__59: typing.ClassVar[int] = ...
    T__16: typing.ClassVar[int] = ...
    T__17: typing.ClassVar[int] = ...
    T__18: typing.ClassVar[int] = ...
    T__55: typing.ClassVar[int] = ...
    T__12: typing.ClassVar[int] = ...
    T__56: typing.ClassVar[int] = ...
    T__13: typing.ClassVar[int] = ...
    T__57: typing.ClassVar[int] = ...
    T__14: typing.ClassVar[int] = ...
    T__58: typing.ClassVar[int] = ...
    T__51: typing.ClassVar[int] = ...
    T__52: typing.ClassVar[int] = ...
    T__53: typing.ClassVar[int] = ...
    T__54: typing.ClassVar[int] = ...
    T__60: typing.ClassVar[int] = ...
    T__61: typing.ClassVar[int] = ...
    RULE_ID: typing.ClassVar[int] = ...
    T__26: typing.ClassVar[int] = ...
    T__27: typing.ClassVar[int] = ...
    T__28: typing.ClassVar[int] = ...
    RULE_INT: typing.ClassVar[int] = ...
    T__29: typing.ClassVar[int] = ...
    T__22: typing.ClassVar[int] = ...
    RULE_ML_COMMENT: typing.ClassVar[int] = ...
    T__23: typing.ClassVar[int] = ...
    T__24: typing.ClassVar[int] = ...
    T__25: typing.ClassVar[int] = ...
    T__62: typing.ClassVar[int] = ...
    T__63: typing.ClassVar[int] = ...
    T__20: typing.ClassVar[int] = ...
    T__21: typing.ClassVar[int] = ...
    RULE_STRING: typing.ClassVar[int] = ...
    RULE_SL_COMMENT: typing.ClassVar[int] = ...
    T__37: typing.ClassVar[int] = ...
    T__38: typing.ClassVar[int] = ...
    T__39: typing.ClassVar[int] = ...
    T__33: typing.ClassVar[int] = ...
    T__34: typing.ClassVar[int] = ...
    T__35: typing.ClassVar[int] = ...
    T__36: typing.ClassVar[int] = ...
    EOF: typing.ClassVar[int] = ...
    T__30: typing.ClassVar[int] = ...
    T__31: typing.ClassVar[int] = ...
    T__32: typing.ClassVar[int] = ...
    RULE_WS: typing.ClassVar[int] = ...
    RULE_ANY_OTHER: typing.ClassVar[int] = ...
    T__48: typing.ClassVar[int] = ...
    T__49: typing.ClassVar[int] = ...
    T__44: typing.ClassVar[int] = ...
    T__45: typing.ClassVar[int] = ...
    RULE_FLOAT: typing.ClassVar[int] = ...
    T__46: typing.ClassVar[int] = ...
    T__47: typing.ClassVar[int] = ...
    T__40: typing.ClassVar[int] = ...
    T__41: typing.ClassVar[int] = ...
    T__42: typing.ClassVar[int] = ...
    T__43: typing.ClassVar[int] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.CharStream): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.CharStream, state: org.antlr.runtime.RecognizerSharedState): ...
    def getGrammarFileName(self) -> java.lang.String: ...
    def mRULE_ANY_OTHER(self) -> None: ...
    def mRULE_FLOAT(self) -> None: ...
    def mRULE_ID(self) -> None: ...
    def mRULE_INT(self) -> None: ...
    def mRULE_ML_COMMENT(self) -> None: ...
    def mRULE_SL_COMMENT(self) -> None: ...
    def mRULE_STRING(self) -> None: ...
    def mRULE_WS(self) -> None: ...
    def mT__12(self) -> None: ...
    def mT__13(self) -> None: ...
    def mT__14(self) -> None: ...
    def mT__15(self) -> None: ...
    def mT__16(self) -> None: ...
    def mT__17(self) -> None: ...
    def mT__18(self) -> None: ...
    def mT__19(self) -> None: ...
    def mT__20(self) -> None: ...
    def mT__21(self) -> None: ...
    def mT__22(self) -> None: ...
    def mT__23(self) -> None: ...
    def mT__24(self) -> None: ...
    def mT__25(self) -> None: ...
    def mT__26(self) -> None: ...
    def mT__27(self) -> None: ...
    def mT__28(self) -> None: ...
    def mT__29(self) -> None: ...
    def mT__30(self) -> None: ...
    def mT__31(self) -> None: ...
    def mT__32(self) -> None: ...
    def mT__33(self) -> None: ...
    def mT__34(self) -> None: ...
    def mT__35(self) -> None: ...
    def mT__36(self) -> None: ...
    def mT__37(self) -> None: ...
    def mT__38(self) -> None: ...
    def mT__39(self) -> None: ...
    def mT__40(self) -> None: ...
    def mT__41(self) -> None: ...
    def mT__42(self) -> None: ...
    def mT__43(self) -> None: ...
    def mT__44(self) -> None: ...
    def mT__45(self) -> None: ...
    def mT__46(self) -> None: ...
    def mT__47(self) -> None: ...
    def mT__48(self) -> None: ...
    def mT__49(self) -> None: ...
    def mT__50(self) -> None: ...
    def mT__51(self) -> None: ...
    def mT__52(self) -> None: ...
    def mT__53(self) -> None: ...
    def mT__54(self) -> None: ...
    def mT__55(self) -> None: ...
    def mT__56(self) -> None: ...
    def mT__57(self) -> None: ...
    def mT__58(self) -> None: ...
    def mT__59(self) -> None: ...
    def mT__60(self) -> None: ...
    def mT__61(self) -> None: ...
    def mT__62(self) -> None: ...
    def mT__63(self) -> None: ...
    def mTokens(self) -> None: ...

class InternalSitemapParser(org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser):
    """
    Java class 'org.openhab.core.model.sitemap.parser.antlr.internal.InternalSitemapParser'
    
        Extends:
            org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser
    
      Constructors:
        * InternalSitemapParser(org.antlr.runtime.TokenStream, org.openhab.core.model.sitemap.services.SitemapGrammarAccess)
        * InternalSitemapParser(org.antlr.runtime.TokenStream)
        * InternalSitemapParser(org.antlr.runtime.TokenStream, org.antlr.runtime.RecognizerSharedState)
    
      Attributes:
        tokenNames ([Ljava.lang.String;): final static field
        T__50 (int): final static field
        T__19 (int): final static field
        T__15 (int): final static field
        T__59 (int): final static field
        T__16 (int): final static field
        T__17 (int): final static field
        T__18 (int): final static field
        T__55 (int): final static field
        T__12 (int): final static field
        T__56 (int): final static field
        T__13 (int): final static field
        T__57 (int): final static field
        T__14 (int): final static field
        T__58 (int): final static field
        T__51 (int): final static field
        T__52 (int): final static field
        T__53 (int): final static field
        T__54 (int): final static field
        T__60 (int): final static field
        T__61 (int): final static field
        RULE_ID (int): final static field
        T__26 (int): final static field
        T__27 (int): final static field
        T__28 (int): final static field
        RULE_INT (int): final static field
        T__29 (int): final static field
        T__22 (int): final static field
        RULE_ML_COMMENT (int): final static field
        T__23 (int): final static field
        T__24 (int): final static field
        T__25 (int): final static field
        T__62 (int): final static field
        T__63 (int): final static field
        T__20 (int): final static field
        T__21 (int): final static field
        RULE_STRING (int): final static field
        RULE_SL_COMMENT (int): final static field
        T__37 (int): final static field
        T__38 (int): final static field
        T__39 (int): final static field
        T__33 (int): final static field
        T__34 (int): final static field
        T__35 (int): final static field
        T__36 (int): final static field
        EOF (int): final static field
        T__30 (int): final static field
        T__31 (int): final static field
        T__32 (int): final static field
        RULE_WS (int): final static field
        RULE_ANY_OTHER (int): final static field
        T__48 (int): final static field
        T__49 (int): final static field
        T__44 (int): final static field
        T__45 (int): final static field
        RULE_FLOAT (int): final static field
        T__46 (int): final static field
        T__47 (int): final static field
        T__40 (int): final static field
        T__41 (int): final static field
        T__42 (int): final static field
        T__43 (int): final static field
        FOLLOW_1 (org.antlr.runtime.BitSet): final static field
        FOLLOW_2 (org.antlr.runtime.BitSet): final static field
        FOLLOW_3 (org.antlr.runtime.BitSet): final static field
        FOLLOW_4 (org.antlr.runtime.BitSet): final static field
        FOLLOW_5 (org.antlr.runtime.BitSet): final static field
        FOLLOW_6 (org.antlr.runtime.BitSet): final static field
        FOLLOW_7 (org.antlr.runtime.BitSet): final static field
        FOLLOW_8 (org.antlr.runtime.BitSet): final static field
        FOLLOW_9 (org.antlr.runtime.BitSet): final static field
        FOLLOW_10 (org.antlr.runtime.BitSet): final static field
        FOLLOW_11 (org.antlr.runtime.BitSet): final static field
        FOLLOW_12 (org.antlr.runtime.BitSet): final static field
        FOLLOW_13 (org.antlr.runtime.BitSet): final static field
        FOLLOW_14 (org.antlr.runtime.BitSet): final static field
        FOLLOW_15 (org.antlr.runtime.BitSet): final static field
        FOLLOW_16 (org.antlr.runtime.BitSet): final static field
        FOLLOW_17 (org.antlr.runtime.BitSet): final static field
        FOLLOW_18 (org.antlr.runtime.BitSet): final static field
        FOLLOW_19 (org.antlr.runtime.BitSet): final static field
        FOLLOW_20 (org.antlr.runtime.BitSet): final static field
        FOLLOW_21 (org.antlr.runtime.BitSet): final static field
        FOLLOW_22 (org.antlr.runtime.BitSet): final static field
        FOLLOW_23 (org.antlr.runtime.BitSet): final static field
        FOLLOW_24 (org.antlr.runtime.BitSet): final static field
        FOLLOW_25 (org.antlr.runtime.BitSet): final static field
        FOLLOW_26 (org.antlr.runtime.BitSet): final static field
        FOLLOW_27 (org.antlr.runtime.BitSet): final static field
        FOLLOW_28 (org.antlr.runtime.BitSet): final static field
        FOLLOW_29 (org.antlr.runtime.BitSet): final static field
        FOLLOW_30 (org.antlr.runtime.BitSet): final static field
        FOLLOW_31 (org.antlr.runtime.BitSet): final static field
        FOLLOW_32 (org.antlr.runtime.BitSet): final static field
        FOLLOW_33 (org.antlr.runtime.BitSet): final static field
        FOLLOW_34 (org.antlr.runtime.BitSet): final static field
        FOLLOW_35 (org.antlr.runtime.BitSet): final static field
        FOLLOW_36 (org.antlr.runtime.BitSet): final static field
        FOLLOW_37 (org.antlr.runtime.BitSet): final static field
        FOLLOW_38 (org.antlr.runtime.BitSet): final static field
        FOLLOW_39 (org.antlr.runtime.BitSet): final static field
        FOLLOW_40 (org.antlr.runtime.BitSet): final static field
        FOLLOW_41 (org.antlr.runtime.BitSet): final static field
        FOLLOW_42 (org.antlr.runtime.BitSet): final static field
    
    """
    tokenNames: typing.ClassVar[typing.List[java.lang.String]] = ...
    T__50: typing.ClassVar[int] = ...
    T__19: typing.ClassVar[int] = ...
    T__15: typing.ClassVar[int] = ...
    T__59: typing.ClassVar[int] = ...
    T__16: typing.ClassVar[int] = ...
    T__17: typing.ClassVar[int] = ...
    T__18: typing.ClassVar[int] = ...
    T__55: typing.ClassVar[int] = ...
    T__12: typing.ClassVar[int] = ...
    T__56: typing.ClassVar[int] = ...
    T__13: typing.ClassVar[int] = ...
    T__57: typing.ClassVar[int] = ...
    T__14: typing.ClassVar[int] = ...
    T__58: typing.ClassVar[int] = ...
    T__51: typing.ClassVar[int] = ...
    T__52: typing.ClassVar[int] = ...
    T__53: typing.ClassVar[int] = ...
    T__54: typing.ClassVar[int] = ...
    T__60: typing.ClassVar[int] = ...
    T__61: typing.ClassVar[int] = ...
    RULE_ID: typing.ClassVar[int] = ...
    T__26: typing.ClassVar[int] = ...
    T__27: typing.ClassVar[int] = ...
    T__28: typing.ClassVar[int] = ...
    RULE_INT: typing.ClassVar[int] = ...
    T__29: typing.ClassVar[int] = ...
    T__22: typing.ClassVar[int] = ...
    RULE_ML_COMMENT: typing.ClassVar[int] = ...
    T__23: typing.ClassVar[int] = ...
    T__24: typing.ClassVar[int] = ...
    T__25: typing.ClassVar[int] = ...
    T__62: typing.ClassVar[int] = ...
    T__63: typing.ClassVar[int] = ...
    T__20: typing.ClassVar[int] = ...
    T__21: typing.ClassVar[int] = ...
    RULE_STRING: typing.ClassVar[int] = ...
    RULE_SL_COMMENT: typing.ClassVar[int] = ...
    T__37: typing.ClassVar[int] = ...
    T__38: typing.ClassVar[int] = ...
    T__39: typing.ClassVar[int] = ...
    T__33: typing.ClassVar[int] = ...
    T__34: typing.ClassVar[int] = ...
    T__35: typing.ClassVar[int] = ...
    T__36: typing.ClassVar[int] = ...
    EOF: typing.ClassVar[int] = ...
    T__30: typing.ClassVar[int] = ...
    T__31: typing.ClassVar[int] = ...
    T__32: typing.ClassVar[int] = ...
    RULE_WS: typing.ClassVar[int] = ...
    RULE_ANY_OTHER: typing.ClassVar[int] = ...
    T__48: typing.ClassVar[int] = ...
    T__49: typing.ClassVar[int] = ...
    T__44: typing.ClassVar[int] = ...
    T__45: typing.ClassVar[int] = ...
    RULE_FLOAT: typing.ClassVar[int] = ...
    T__46: typing.ClassVar[int] = ...
    T__47: typing.ClassVar[int] = ...
    T__40: typing.ClassVar[int] = ...
    T__41: typing.ClassVar[int] = ...
    T__42: typing.ClassVar[int] = ...
    T__43: typing.ClassVar[int] = ...
    FOLLOW_1: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_2: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_3: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_4: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_5: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_6: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_7: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_8: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_9: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_10: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_11: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_12: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_13: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_14: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_15: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_16: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_17: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_18: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_19: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_20: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_21: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_22: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_23: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_24: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_25: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_26: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_27: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_28: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_29: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_30: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_31: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_32: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_33: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_34: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_35: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_36: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_37: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_38: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_39: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_40: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_41: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    FOLLOW_42: typing.ClassVar[org.antlr.runtime.BitSet] = ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.TokenStream): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.TokenStream, state: org.antlr.runtime.RecognizerSharedState): ...
    @typing.overload
    def __init__(self, input: org.antlr.runtime.TokenStream, grammarAccess: org.openhab.core.model.sitemap.services.SitemapGrammarAccess): ...
    def entryRuleBOOLEAN_OBJECT(self) -> java.lang.String: ...
    def entryRuleChart(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleColorArray(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleColorpicker(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleCommand(self) -> java.lang.String: ...
    def entryRuleDefault(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleFrame(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleGroup(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleGroupItemRef(self) -> java.lang.String: ...
    def entryRuleIcon(self) -> java.lang.String: ...
    def entryRuleImage(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleItemRef(self) -> java.lang.String: ...
    def entryRuleLinkableWidget(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleList(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleMapping(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleMapview(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleNonLinkableWidget(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleNumber(self) -> java.lang.String: ...
    def entryRuleSelection(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleSetpoint(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleSitemap(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleSitemapModel(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleSlider(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleSwitch(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleText(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleVideo(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleVisibilityRule(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleWebview(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleWidget(self) -> org.eclipse.emf.ecore.EObject: ...
    def entryRuleXState(self) -> java.lang.String: ...
    def getGrammarFileName(self) -> java.lang.String: ...
    def getTokenNames(self) -> typing.List[java.lang.String]: ...
    def ruleBOOLEAN_OBJECT(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleChart(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleColorArray(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleColorpicker(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleCommand(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleDefault(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleFrame(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleGroup(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleGroupItemRef(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleIcon(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleImage(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleItemRef(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleLinkableWidget(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleList(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleMapping(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleMapview(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleNonLinkableWidget(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleNumber(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
    def ruleSelection(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleSetpoint(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleSitemap(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleSitemapModel(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleSlider(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleSwitch(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleText(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleVideo(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleVisibilityRule(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleWebview(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleWidget(self) -> org.eclipse.emf.ecore.EObject: ...
    def ruleXState(self) -> org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken: ...
