import java.lang
import java.net
import org.openhab.core.config.core
import org.openhab.core.thing
import typing


class MagicBindingConstants(java.lang.Object):
    """
    Java class 'org.openhab.core.magic.binding.MagicBindingConstants'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * MagicBindingConstants()
    
      Attributes:
        BINDING_ID (java.lang.String): final static field
        THING_TYPE_EXTENSIBLE_THING (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_ON_OFF_LIGHT (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_DIMMABLE_LIGHT (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_COLOR_LIGHT (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_CONTACT_SENSOR (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_CONFIG_THING (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_DELAYED_THING (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_LOCATION (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_THERMOSTAT (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_FIRMWARE_UPDATE (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_CHATTY_THING (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_ROLLERSHUTTER (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_PLAYER (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_IMAGE (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_ACTION_MODULE (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_DYNAMIC_STATE_DESCRIPTION (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_ONLINE_OFFLINE (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_BRIDGE_1 (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_BRIDGE_2 (org.openhab.core.thing.ThingTypeUID): final static field
        THING_TYPE_BRIDGED_THING (org.openhab.core.thing.ThingTypeUID): final static field
        CHANNEL_SWITCH (java.lang.String): final static field
        CHANNEL_BRIGHTNESS (java.lang.String): final static field
        CHANNEL_COLOR (java.lang.String): final static field
        CHANNEL_CONTACT (java.lang.String): final static field
        CHANNEL_LOCATION (java.lang.String): final static field
        CHANNEL_TEMPERATURE (java.lang.String): final static field
        CHANNEL_SET_TEMPERATURE (java.lang.String): final static field
        CHANNEL_SYSTEM_COMMAND (java.lang.String): final static field
        CHANNEL_SIGNAL_STRENGTH (java.lang.String): final static field
        UPDATE_MODEL_PROPERTY (java.lang.String): final static field
        MODEL_ALOHOMORA (java.lang.String): final static field
        MODEL_COLLOPORTUS (java.lang.String): final static field
        MODEL_LUMOS (java.lang.String): final static field
        MODEL_NOX (java.lang.String): final static field
        CHANNEL_IMAGE (java.lang.String): final static field
    
    """
    BINDING_ID: typing.ClassVar[java.lang.String] = ...
    THING_TYPE_EXTENSIBLE_THING: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_ON_OFF_LIGHT: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_DIMMABLE_LIGHT: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_COLOR_LIGHT: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_CONTACT_SENSOR: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_CONFIG_THING: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_DELAYED_THING: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_LOCATION: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_THERMOSTAT: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_FIRMWARE_UPDATE: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_CHATTY_THING: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_ROLLERSHUTTER: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_PLAYER: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_IMAGE: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_ACTION_MODULE: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_DYNAMIC_STATE_DESCRIPTION: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_ONLINE_OFFLINE: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_BRIDGE_1: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_BRIDGE_2: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    THING_TYPE_BRIDGED_THING: typing.ClassVar[org.openhab.core.thing.ThingTypeUID] = ...
    CHANNEL_SWITCH: typing.ClassVar[java.lang.String] = ...
    CHANNEL_BRIGHTNESS: typing.ClassVar[java.lang.String] = ...
    CHANNEL_COLOR: typing.ClassVar[java.lang.String] = ...
    CHANNEL_CONTACT: typing.ClassVar[java.lang.String] = ...
    CHANNEL_LOCATION: typing.ClassVar[java.lang.String] = ...
    CHANNEL_TEMPERATURE: typing.ClassVar[java.lang.String] = ...
    CHANNEL_SET_TEMPERATURE: typing.ClassVar[java.lang.String] = ...
    CHANNEL_SYSTEM_COMMAND: typing.ClassVar[java.lang.String] = ...
    CHANNEL_SIGNAL_STRENGTH: typing.ClassVar[java.lang.String] = ...
    UPDATE_MODEL_PROPERTY: typing.ClassVar[java.lang.String] = ...
    MODEL_ALOHOMORA: typing.ClassVar[java.lang.String] = ...
    MODEL_COLLOPORTUS: typing.ClassVar[java.lang.String] = ...
    MODEL_LUMOS: typing.ClassVar[java.lang.String] = ...
    MODEL_NOX: typing.ClassVar[java.lang.String] = ...
    CHANNEL_IMAGE: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...

class MagicService(org.openhab.core.config.core.ConfigOptionProvider):
    """
    Java class 'org.openhab.core.magic.binding.MagicService'
    
        Interfaces:
            org.openhab.core.config.core.ConfigOptionProvider
    
      Attributes:
        CONFIG_URI (java.net.URI): final static field
    
    """
    CONFIG_URI: typing.ClassVar[java.net.URI] = ...
