import java.lang
import typing


class HttpWhiteboardConstants(java.lang.Object):
    """
    Java class 'org.osgi.service.http.whiteboard.HttpWhiteboardConstants'
    
        Extends:
            java.lang.Object
    
      Attributes:
        HTTP_WHITEBOARD_CONTEXT_NAME (java.lang.String): final static field
        HTTP_WHITEBOARD_DEFAULT_CONTEXT_NAME (java.lang.String): final static field
        HTTP_WHITEBOARD_CONTEXT_PATH (java.lang.String): final static field
        HTTP_WHITEBOARD_CONTEXT_INIT_PARAM_PREFIX (java.lang.String): final static field
        HTTP_WHITEBOARD_CONTEXT_SELECT (java.lang.String): final static field
        HTTP_WHITEBOARD_SERVLET_NAME (java.lang.String): final static field
        HTTP_WHITEBOARD_SERVLET_PATTERN (java.lang.String): final static field
        HTTP_WHITEBOARD_SERVLET_ERROR_PAGE (java.lang.String): final static field
        HTTP_WHITEBOARD_SERVLET_ASYNC_SUPPORTED (java.lang.String): final static field
        HTTP_WHITEBOARD_SERVLET_INIT_PARAM_PREFIX (java.lang.String): final static field
        HTTP_WHITEBOARD_FILTER_NAME (java.lang.String): final static field
        HTTP_WHITEBOARD_FILTER_PATTERN (java.lang.String): final static field
        HTTP_WHITEBOARD_FILTER_SERVLET (java.lang.String): final static field
        HTTP_WHITEBOARD_FILTER_REGEX (java.lang.String): final static field
        HTTP_WHITEBOARD_FILTER_ASYNC_SUPPORTED (java.lang.String): final static field
        HTTP_WHITEBOARD_FILTER_DISPATCHER (java.lang.String): final static field
        HTTP_WHITEBOARD_FILTER_INIT_PARAM_PREFIX (java.lang.String): final static field
        HTTP_WHITEBOARD_LISTENER (java.lang.String): final static field
        DISPATCHER_REQUEST (java.lang.String): final static field
        DISPATCHER_INCLUDE (java.lang.String): final static field
        DISPATCHER_FORWARD (java.lang.String): final static field
        DISPATCHER_ASYNC (java.lang.String): final static field
        DISPATCHER_ERROR (java.lang.String): final static field
        HTTP_WHITEBOARD_RESOURCE_PATTERN (java.lang.String): final static field
        HTTP_WHITEBOARD_RESOURCE_PREFIX (java.lang.String): final static field
        HTTP_WHITEBOARD_TARGET (java.lang.String): final static field
    
    """
    HTTP_WHITEBOARD_CONTEXT_NAME: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_DEFAULT_CONTEXT_NAME: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_CONTEXT_PATH: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_CONTEXT_INIT_PARAM_PREFIX: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_CONTEXT_SELECT: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_SERVLET_NAME: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_SERVLET_PATTERN: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_SERVLET_ERROR_PAGE: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_SERVLET_ASYNC_SUPPORTED: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_SERVLET_INIT_PARAM_PREFIX: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_FILTER_NAME: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_FILTER_PATTERN: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_FILTER_SERVLET: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_FILTER_REGEX: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_FILTER_ASYNC_SUPPORTED: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_FILTER_DISPATCHER: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_FILTER_INIT_PARAM_PREFIX: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_LISTENER: typing.ClassVar[java.lang.String] = ...
    DISPATCHER_REQUEST: typing.ClassVar[java.lang.String] = ...
    DISPATCHER_INCLUDE: typing.ClassVar[java.lang.String] = ...
    DISPATCHER_FORWARD: typing.ClassVar[java.lang.String] = ...
    DISPATCHER_ASYNC: typing.ClassVar[java.lang.String] = ...
    DISPATCHER_ERROR: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_RESOURCE_PATTERN: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_RESOURCE_PREFIX: typing.ClassVar[java.lang.String] = ...
    HTTP_WHITEBOARD_TARGET: typing.ClassVar[java.lang.String] = ...
