import java.io
import java.lang
import org.osgi.framework
import typing


class AttributeDefinition(java.lang.Object):
    """
    Java class 'org.osgi.service.metatype.AttributeDefinition'
    
      Attributes:
        STRING (int): final static field
        LONG (int): final static field
        INTEGER (int): final static field
        SHORT (int): final static field
        CHARACTER (int): final static field
        BYTE (int): final static field
        DOUBLE (int): final static field
        FLOAT (int): final static field
        BIGINTEGER (int): final static field
        BIGDECIMAL (int): final static field
        BOOLEAN (int): final static field
        PASSWORD (int): final static field
    
    """
    STRING: typing.ClassVar[int] = ...
    LONG: typing.ClassVar[int] = ...
    INTEGER: typing.ClassVar[int] = ...
    SHORT: typing.ClassVar[int] = ...
    CHARACTER: typing.ClassVar[int] = ...
    BYTE: typing.ClassVar[int] = ...
    DOUBLE: typing.ClassVar[int] = ...
    FLOAT: typing.ClassVar[int] = ...
    BIGINTEGER: typing.ClassVar[int] = ...
    BIGDECIMAL: typing.ClassVar[int] = ...
    BOOLEAN: typing.ClassVar[int] = ...
    PASSWORD: typing.ClassVar[int] = ...
    def getCardinality(self) -> int: ...
    def getDefaultValue(self) -> typing.List[java.lang.String]: ...
    def getDescription(self) -> java.lang.String: ...
    def getID(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getOptionLabels(self) -> typing.List[java.lang.String]: ...
    def getOptionValues(self) -> typing.List[java.lang.String]: ...
    def getType(self) -> int: ...
    def validate(self, string: java.lang.String) -> java.lang.String: ...

class MetaTypeProvider(java.lang.Object):
    """
    Java class 'org.osgi.service.metatype.MetaTypeProvider'
    
      Attributes:
        METATYPE_PID (java.lang.String): final static field
        METATYPE_FACTORY_PID (java.lang.String): final static field
    
    """
    METATYPE_PID: typing.ClassVar[java.lang.String] = ...
    METATYPE_FACTORY_PID: typing.ClassVar[java.lang.String] = ...
    def getLocales(self) -> typing.List[java.lang.String]: ...
    def getObjectClassDefinition(self, string: java.lang.String, string2: java.lang.String) -> 'ObjectClassDefinition': ...

class MetaTypeService(java.lang.Object):
    """
    Java class 'org.osgi.service.metatype.MetaTypeService'
    
      Attributes:
        METATYPE_DOCUMENTS_LOCATION (java.lang.String): final static field
        METATYPE_CAPABILITY_NAME (java.lang.String): final static field
        METATYPE_SPECIFICATION_VERSION (java.lang.String): final static field
    
    """
    METATYPE_DOCUMENTS_LOCATION: typing.ClassVar[java.lang.String] = ...
    METATYPE_CAPABILITY_NAME: typing.ClassVar[java.lang.String] = ...
    METATYPE_SPECIFICATION_VERSION: typing.ClassVar[java.lang.String] = ...
    def getMetaTypeInformation(self, bundle: org.osgi.framework.Bundle) -> 'MetaTypeInformation': ...

class ObjectClassDefinition(java.lang.Object):
    """
    Java class 'org.osgi.service.metatype.ObjectClassDefinition'
    
      Attributes:
        REQUIRED (int): final static field
        OPTIONAL (int): final static field
        ALL (int): final static field
    
    """
    REQUIRED: typing.ClassVar[int] = ...
    OPTIONAL: typing.ClassVar[int] = ...
    ALL: typing.ClassVar[int] = ...
    def getAttributeDefinitions(self, int: int) -> typing.List[AttributeDefinition]: ...
    def getDescription(self) -> java.lang.String: ...
    def getID(self) -> java.lang.String: ...
    def getIcon(self, int: int) -> java.io.InputStream: ...
    def getName(self) -> java.lang.String: ...

class MetaTypeInformation(MetaTypeProvider):
    """
    Java class 'org.osgi.service.metatype.MetaTypeInformation'
    
        Interfaces:
            org.osgi.service.metatype.MetaTypeProvider
    
    """
    def getBundle(self) -> org.osgi.framework.Bundle: ...
    def getFactoryPids(self) -> typing.List[java.lang.String]: ...
    def getPids(self) -> typing.List[java.lang.String]: ...
